### ISSUE TITLE
Add option to disable workspaces

### ISSUE THREAD

**Issue by diocletiann** [nikitabobko/AeroSpace#105]
Thank you for the amazing tool, finally i3-like window management on Mac. I wrote my own wrapper for yabai but this is so much better. 

I was wondering if you'd be open to an option to disable workspaces - I'm still fond of swiping when I don't have both hands on the keyboard, and I don't mind using yabai with tiling disabled to kill the animation when using the keyboard and assign windows to spaces.

**Comment by nikitabobko** [comment]
> I was wondering if you'd be open to an option to disable workspaces

Very unlikely. That might require usage of private APIs, and it requires significant changes in AeroSpace architecture. I'm not interested in exploring this direction.

If anybody manages to implement this in a not hacky way, and without the usage of private APIs => PRs are open

> I'm still fond of swiping when I don't have both hands on the keyboard

Starting from the next version, you will be able to switch workspaces on the monitor where the mouse currently belongs to:
```
aerospace list-workspaces --on-monitors mouse | aerospace workspace next

aerospace list-workspaces --on-monitors mouse | aerospace workspace prev
```

You can use BetterTouchTool or similar to attach these commands to trackpad gestures

**Comment by diocletiann** [comment]
@nikitabobko Just to make sure were on the same page, are you saying that _not_ managing workspaces requires private APIs? My request was to have a feature that would arrange windows only within the active macOS space.

**Comment by nikitabobko** [comment]
Yes, we are on the same page.

That **might** require usage of private APIs. You need to remember the state of window trees for each Space => you need to understand what Spaces windows belong to or/and what Space is currently active. 

That is a cooperation with Spaces which **might** require private APIs.

I didn't explore it so I might be wrong

**Comment by diocletiann** [comment]
Makes sense, thank you.
