### ISSUE TITLE
Implement equalize / balance / even command

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#114]
Add a command that would make sizes of windows equal

Name brainstorming:
- `equalize-weights`
- `equalize-sizes`
- `even-horizontal`/`even-vertical` (like in tmux. I don't like it)
- `balance-weights`
- `balance-sizes`

**Comment by karadnik-flutterint** [comment]
@nikitabobko taking this

**Comment by nikitabobko** [comment]
Implemented in 0.13.0-Beta by @karadnik-flutterint
