### ISSUE TITLE
Cycle through containers of active workspace

### ISSUE THREAD

**Issue by moritzuehling** [nikitabobko/AeroSpace#119]
My usecase is the following: 

1. I use one workspace (workspace 2) for my communication apps (Slack, Discord, Mumble, Telegram, ...)
2. They are in a stacked layout

So, when I use alt-2, I switch to that workspace, which is great. But if the wrong app is in foreground, I have to reach over to alt-k to switch containers. 

Sure, I could remap this binding to e.g. alt-e (that's unusued in my config), but I would love if I could just keep hitting alt-2. 

You can approximate it with 

```
alt-2 = ['workspace 2', 'focus down']
```

but that means that whever I go back to workspace 2, I get a new random app. 

The best alternative I've found is to swap those commands:

```
alt-2 = ['focus down', 'workspace 2']
```

But that means if I have another layout stacked somewhere, it breaks that before leaving, which is annoying. 

Essentially, what I want is that `focus down` is only executed if the active workspace is already workspace 2.

**Comment by moritzuehling** [comment]
Thank you for making it possible ❤️

**Comment by moritzuehling** [comment]
Hm,

I've been playing around with this, but I can't get it to work, and I think it's the bash part that's wrong. The script seems to be working fine if I execute it with `bash -c`, but not even the simple case of this works:

```
alt-2 = 'exec-and-forget aerospace workspace 2'
```

Nothing happens. I'm not sure what i'm doing wrong

**Comment by nikitabobko** [comment]
1. Try to specify the full path to `aerospace` binary (on Apple Silicon Macs it's `/opt/homebrew/bin/aerospace`)
2. You can add Homebrew to GUI apps `$PATH` https://docs.brew.sh/FAQ#my-mac-apps-dont-find-homebrew-utilities

**Comment by moritzuehling** [comment]
Ah, perfect, I suspected it was something like this, but struggled to find the full path. I'm a bit new to macOS, coming from a windows/linux/freebsd background, 

Thanks, it works perfectly now. It's actually a really convenient way to cycle through apps now that I'm actually trying it.
