### ISSUE TITLE
why `--no-quarantine` is necessary when installing with brew

### ISSUE THREAD

**Issue by mrasputin** [nikitabobko/AeroSpace#129]
> The `--no-quarantine` flag in a `brew` command is Homebrew-specific and is used to bypass the Gatekeeper quarantine on macOS. Gatekeeper is a security feature of macOS that checks downloaded software for known security issues before it's run. Using `--no-quarantine` tells Homebrew to skip this check for the specific cask being installed.

**Comment by nikitabobko** [comment]
This flag is a shorthand for "right click -> open" in Finder https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer

I'd need to notarize AeroSpace. Notarization costs $99 a year and requires Apple's review process. Neither I want to pay Apple for the privilege of developing macOS apps, nor do I want to go through the review process.

I provide an alternative security guarantee - the app is open-source. You can read the source code and compile it yourself if you want to be extra cautious

**Comment by mrasputin** [comment]
claro, makes complete sense, thanks for the explanation! I was not aware of the (ridiculous) Notarization cost...

**Comment by tonyarnold** [comment]
Sorry to necro-post, but you've made a few statements about notarization being tied to review: 

> and requires Apple's review process

_It doesn't_. Yes, you currently need to pay the Developer Membership fee to notarize apps (and that's an issue for OSS projects like this one), but there's no review involved at all.

**Comment by gritse** [comment]
@nikitabobko Hey, I have an active Apple Developer account and can help with releasing notarized apps if that would benefit the project.
