### ISSUE TITLE
BUG: apps spawning new windows break window management until killed

### ISSUE THREAD

**Issue by jorgevds** [nikitabobko/AeroSpace#13]
Adopted this yesterday, enjoying it so far. :)

I currently have two apps per layout that I cycle between. Number one has my terminal and Brave browser, number two has teams and Firefox. I keep both layouts in accordion mode.

Today I noticed that Microsoft Teams broke layout 2 when I entered a meeting. Everything worked just fine when entering the meeting, but when I left and the window was of course removed, I had a gap between the active Teams window and the edge of my screen, which showed my desktop. 

I tried focusing Firefox and refocusing Teams, but the gap stayed. I also tried moving Teams to a random number like 8. This solved layout 2 in that Firefox took up the whole screen. But then if I moved back to layout 8 and tried moving it back to layout 2, the indicator at the stop still said 8. And then if I navigated to layout 2, it would still show as layout 8 and focus the Teams app.

This problem went away when I quit Teams and reopened it.

**Comment by nikitabobko** [comment]
I never used Microsoft Teams so it's hard to reproduce for me. I see that there are two versions of teams: "classic" and "new teams".

I tried to reproduce this with "new teams" by creating a meeting with myself. It worked okay

- What teams app do you use? 
- Can you please give a screenshot/more elaborate steps on what exact "meeting" window it is reproducible in?

**Comment by jorgevds** [comment]
I use Teams classic, so that could be related.

It seems to happen specifically when clicking on the dialog "confirm" option that shows up when someone calls you or when someone starts a meeting. That dialog won't always show up as a window itself, for example in accordion mode where it will be minimized. Clicking "confirm" i.e. answering a call will mess up the layout, as will clicking "Join meeting" when someone else has started a meeting.

I'll work in the new Teams version and see if I can still reproduce the issue. If not, this problem may solve itself as I'm sure Teams is not going to support their classic version forever. :)

**Comment by jorgevds** [comment]
Happy to report that this bug can no longer be reproduced once you move to the new Teams application.
