### ISSUE TITLE
Keyboard shortcuts wonky

### ISSUE THREAD

**Issue by alper** [nikitabobko/AeroSpace#132]
I've upgraded my machine to 14.3 and see that I'm also on 0.8.1 now and some things have changed.

I have my shortcuts setup as:

```
ctrl-alt-left = 'focus left'
ctrl-alt-down = 'focus down'
ctrl-alt-up  = 'focus up'
ctrl-alt-right = 'focus right'

alt-cmd-left = 'join-with left'
alt-cmd-down = 'join-with down'
alt-cmd-up  = 'join-with up'
alt-cmd-right = 'join-with right'

ctrl-cmd-alt-left = 'move left'
ctrl-cmd-alt-down = 'move down'
ctrl-cmd-alt-up = 'move up'
ctrl-cmd-alt-right = 'move right'
```

And as far as I can tell the join and move commands are working but for some reason the focus command just does not arrive and I can't rotate through windows anymore.

Did something change that could explain that? I ran ShortcutDetective which seems to pick up Aerospace of the second two sets, but not for the `ctrl-alt` shortcuts.

**Comment by alper** [comment]
It seems my `ctrl-cmd-alt-right` command is also misbehaving because if I give the command through the terminal, the thing I expect to happen works perfectly.

Is there a way for me to enable verbose logging on aerospace to see what commands it is getting in?

**Comment by alper** [comment]
OK. I think something is squatting on these combinations.

I remapped the actions to `ctrl-alt-{1,2,3,4}` and then they do work.

Not an Aerospace issue but still very annoying.

**Comment by alper** [comment]
OK. Figured out what it was. 

The reboot fired up [skhd](https://github.com/koekeishiya/skhd) which was setup to catch many of the same shortcuts and was still lingering on my machine after trying out Yabai.

**Comment by gplusplus314** [comment]
For anyone else ending up here, I had `ctrl-(arrows)` bound to `focus (arrows)` and they didn't work. They're actually bound by default in a fresh macOS installation for some Mission Control actions, which takes precedence over AeroSpace's hotkey handling.

Here's the delicious copy/pasta for dotfiles or if you just want to fix it via the CLI:

```
# Disable Ctrl + Left Arrow (Mission Control: Move left a space)
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 79 "<dict><key>enabled</key><false/></dict>"
# Disable Ctrl + Right Arrow (Mission Control: Move right a space)
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 80 "<dict><key>enabled</key><false/></dict>"
# Disable Ctrl + Up Arrow (Mission Control: Mission Control)
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 32 "<dict><key>enabled</key><false/></dict>"
# Disable Ctrl + Down Arrow (Mission Control: Application windows)
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 33 "<dict><key>enabled</key><false/></dict>"
```
