### ISSUE TITLE
Feature: move-node-to-monitor

### ISSUE THREAD

**Issue by canadaduane** [nikitabobko/AeroSpace#133]
I have two monitors, and at any given time, I would like the ability to "splat" a window to the other monitor--in other words, I don't particularly care which workspace is currently on that monitor, I just want the window to be moved to whatever workspace is current there.

In addition, I'd like to be able to use directional motions, similar to `focus --boundaries all-monitors-outer-frame <dir>`.

Would it be possible to add `move-node-to-monitor [left | right | down | up]` ?

**Comment by nikitabobko** [comment]
I agree that it'd be nice to have this command

I suggest the following synopsis:
```
USAGE: move-node-to-monitor (left|down|up|right)
   OR: move-node-to-monitor [--wrap-around] (next|prev)
   OR: move-node-to-monitor <monitor-pattern>...

ARGUMENTS:
  <monitor-pattern>     Find the first monitor pattern in the list that
                        doesn't describe the current monitor and moves the window
                        to the appropriate monitor. Monitor pattern as in
                        workspace-to-monitor-force-assignment
```

---

For the reference, that's how it's implemented in i3 https://i3wm.org/docs/userguide.html#move_to_outputs 
```
move container to output left|right|down|up|current|primary|nonprimary|next|<output1> [output2]…
```

**Comment by yshenfab** [comment]
Same here. Multi-monitor support is not very intuitive (change focus between monitors, move nodes to monitor with left/right options, etc.). For now, the easy way is to use two external monitors as workspaces, then you can easily switch workspaces, change focus, or move containers.

**Comment by nikitabobko** [comment]
`move-node-to-monitor` is introduced in 0.9.0
