### ISSUE TITLE
Keeping a window on all workspaces

### ISSUE THREAD

**Issue by alberteddu** [nikitabobko/AeroSpace#139]
Hello! I have been trying to keep a window on all workspaces, but this does not seems to be possible.

I have tried with:

```
[[on-window-detected]]
...
run = ['move-node-to-workspace $AEROSPACE_FOCUSED_WORKSPACE']
```

but it isn't supported (I think `move-node-to-workspace` expects a literal workspace here, and the variable might not event be set outside of the `workspace-changed` event).

I though of moving the window when the workspace changes, but aerospace does not have commands to act on arbitrary windows (only on focused ones)

Am I missing something?

**Comment by nikitabobko** [comment]
It's not possible yet

Duplicate of #2

**Comment by ghost** [comment]
Here is how I did it for the Picture-in-Picture window when I pop a video out of my browser (Firefox):

In my ~/.config/aerospace/aerospace.toml:
```
exec-on-workspace-change = [
    '/bin/bash', '-c',
    '~/.config/aerospace/pip-move.sh',
]
```

~/.config/aerospace/pip-move.sh (handles FF and Edge):
```
#!/bin/bash
# Get current workspace
current_workspace=$(aerospace list-workspaces --focused)
# Move PiP windows to current workspace (handles both "Picture-in-Picture" and "Picture in Picture")
aerospace list-windows --all | grep -E "(Picture-in-Picture|Picture in Picture)" | awk '{print $1}' | while read window_id; do
    if [ -n "$window_id" ]; then
        aerospace move-node-to-workspace --window-id "$window_id" "$current_workspace"
    fi
done
```
