### ISSUE TITLE
[Bug] Cannot focus on a window after throwing it from another monitor

### ISSUE THREAD

**Issue by XOR-op** [nikitabobko/AeroSpace#142]
## Description
This bug happens when move a window from workspace on one monitor to another workspace on another monitor.

Considering the following setup: we have monitors M1 and M2, and assigned workspace S1 to M1, S2 to M2. When we have only one window W1 on S1, the indicator on status bar shows the currently focused monitor is M1. When we use keyboard shortcut to move W1 to S2, now we have no window on S1 in M1, and W1 on S2 in M2. But the currently focused monitor is still M1, even after I clicked W1 for multiple times. Only if we drag the titlebar of W1 can the focus change correctly.

## Reproduction

I have demonstrated one setup above. And:
- Initially W1 on S1 and W2 on S2, throwing W1 to S2; now no window on S1 in M1 and W1, W2 on S2 in M2. I cannot focus on W1, but can focus on W2.
- Initially W1, W3 on S1 and W2 on S2, throwing W1 to S2; now W3 on S1 in M1 and W1, W2 on S2 in M2. I can focus on W1.
- Initially W1, W2 on S1 and no window on S2, throwing W1 to S2; now W2 on S1 in M1 and W1 on S2 in M2. I can focus on W1.

## Possible Reasons
I guess something is not handled correctly with corner case of no window remaining in a workspace. And maybe the window-monitor mapping? Also, I did not test the scenario when S1 and S2 have no force assignment.

## Version
Tested on 0.8.3-beta

**Comment by XOR-op** [comment]
Another observation: I cannot focus on a empty workspace. I'm not sure if it's by design or not, but probably has some internal relationship with this bug.

**Comment by nikitabobko** [comment]
It's somewhat "by design". When focusing an empty workspace, AeroSpace keeps the previous window focused

I didn't find the API to "defocus" window. I tried to focus the desktop but failed (though I didn't spend a lot of time on it to claim that it's impossible)

Since the previous app stays focused, you can spawn new windows with cmd+n, so this "bug" can be considered a feature.

In a single monitor setup, I actually like the current behavior. I understand that the behavior might be confusing in a multi-monitor setup

**Comment by XOR-op** [comment]
Thank you for your explanation, it appears that my follow-up observation seems to have no relation with my original issue. And I think for focusing an empty workspace, I could try to manually focus that workspace as a workaround. 

So what about the bug I brought up initially? I find that, when I moved one window to another monitor, if the focus still remains on the original monitor, I cannot do anything with that window (e.g. move that window back, resize). Is that also somewhat "by design" or a real bug?

**Comment by nikitabobko** [comment]
> But the currently focused monitor is still M1, even after I clicked W1 for multiple times

It's a bug

**Comment by nikitabobko** [comment]
Fixed in `main` branch https://github.com/nikitabobko/AeroSpace/commit/67b78c5e74abc9750e79f66e14b2247fa69b026f

**Comment by nikitabobko** [comment]
The fix is released in 0.10.0
