### ISSUE TITLE
Customize Workspaces

### ISSUE THREAD

**Issue by AlJohri** [nikitabobko/AeroSpace#144]
Two related questions for customizing workspaces:

1. I am currently using Workspaces with Sketchybar which runs `aerospace list-workspaces --all`. Is there a way I can customize to have fewer workspaces? Or start with fewer workspaces and dynamically increase to more similar to Mission Control? I don't love having the menu bar full of 0-9 + A-Z if I am only using the first few. If that's not possible maybe I can create an indicator to color if a workspace has any windows attached to it.

2. Is there a way to start the workspaces from 1 instead of 0? I am frequently using the keyboard shortcuts of alt+0 and alt+1 to switch between workspaces and it would be easier to switch between 1 and 2 compared to 0 and 1. If possible, I would like to make the default workspace be 1 and increment from there. Alternatively I can likely change the keybindings to make alt+1 go to workspace 0.

**Comment by nikitabobko** [comment]
> Or start with fewer workspaces and dynamically increase to more similar to Mission Control?

You can call `aerospace move-node-to-workspace name-that-didnt-exist-before` and it will create workspace `name-that-didnt-exist-before` and move the window to the newly created workspace. Workspaces are created on the fly

> If that's not possible maybe I can create an indicator to color if a workspace has any windows attached to it.

`aerospace list-workspaces --on-monitor focused --empty no`

> I don't love having the menu bar full of 0-9 + A-Z

> Is there a way to start the workspaces from 1 instead of 0?

#100 
#32

**Comment by AlJohri** [comment]
I can't believe it was that simple, thanks @nikitabobko!
