### ISSUE TITLE
Possible to use , and . in key bindings?

### ISSUE THREAD

**Issue by strbrgr** [nikitabobko/AeroSpace#148]
I would like to use the following key bindings to switch between workspaces:

``` 
alt-ctrl-shift-, = 'workspace 2'
alt-ctrl-shift-. = 'workspace 3'
```

These two result in parsing errors due to the use of , and .
I wonder if there is a workaround?

**Comment by XOR-op** [comment]
Use comma and period, e.g. `alt-shift-comma`. You can see all supported special characters in the default config.

**Comment by strbrgr** [comment]
Thank you very much. Link to [config](https://nikitabobko.github.io/AeroSpace/config-examples.html#default-config) for anyone in need of other chars.
