### ISSUE TITLE
High cpu usage for WindowServer process

### ISSUE THREAD

**Issue by svatem1** [nikitabobko/AeroSpace#154]
probably a bug or limitation of the design decision to not to use native workspaces

on my setup, where I have 10 windows opened, WindowServer process uses 35%+ nonstop

**Comment by nikitabobko** [comment]
Well, WindowServer process uses 0% in my setup. I didn't get even a little spike by closing, opening windows. I have 8 windows opened: Spotify, Telegram, AppCode, AppCode, System Settings, Alacritty, Google Chrome, Xcode

<img width="789" alt="image" src="https://github.com/nikitabobko/AeroSpace/assets/20517828/fcdca177-5d7f-433d-90fd-38345fc69950">

You need to debug the problem on your side. In its current state, there is nothing useful that can be done with this issue

1. Is the problem reproducible with 0 windows?
2. Do you have several monitors? Have you tried to reduce the number of monitors to one? 
3. Try closing windows one by one to see if the problem goes away
4. Try to reboot

**Comment by svatem1** [comment]
I already uninstalled the app, the main issues being unreliability (some windows not being detected and managed sometimes), non-robustness (i could get it to malfunction just by using keyboard shortcuts from default example config) and the switching of workspaces is or feels slower than native one. So I cannot really give you clear answers. Weird thing I see immediately here is mine WindowServer is reported to use ~800MB RAM according to Activity Monitor, while your tool shows 0.0%.

**Comment by otoniel-isidoro** [comment]
Try to enable reduce motion and reduce transparency under the accessibility settings on OSX. That solved performance issues for me on OSX Sonoma.
