### ISSUE TITLE
Add more options to move-workspace-to-monitor

### ISSUE THREAD

**Issue by varunaswal** [nikitabobko/AeroSpace#158]
The use case that I am interested in is "summoning" a workspace to the monitor that I am currently looking at. We would probably need to add `--workspace` and `--monitor` flags to the command to achieve this. It would be particularly useful if we could use `monitor.primary` (or similar) as a value for the monitor flag.

My current workflow for this is switching to the desired workspace and then moving it to the desired monitor with the current behaviour of `move-workspace-to-monitor`.

**Comment by xiexingwu** [comment]
> My current workflow for this is switching to the desired workspace and then moving it to the desired monitor with the current behaviour of move-workspace-to-monitor.

If your current workflow works, then sounds like it can be worked around by chaining commands to a binding, i.e.:
```toml
<your-binding> = ['workspace 1', 'move-workspace-to-monitor next']
```

It would be cool if we could designate a monitor directly by name/direction instead of by `prev|next`. I think much of that ground work would be laid out in #133.

**Comment by nikitabobko** [comment]
Duplicate of #186
