### ISSUE TITLE
Assign application to specific workspace

### ISSUE THREAD

**Issue by nick79** [nikitabobko/AeroSpace#159]
Hi,

Is it possible to somehow permanently assign some application (for example Slack) to the specific workspace (for example Workspace 2)? I checked both provided configurations but didn't find any example, nor did I find it in the provided documentation. Probably, I miss something.

Thanks in advance.

**Comment by nikitabobko** [comment]
https://nikitabobko.github.io/AeroSpace/guide.html#on-window-detected-callback

```
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace S'
```
