### ISSUE TITLE
Problem moving windows into a waorkspace.

### ISSUE THREAD

**Issue by ashneyderman** [nikitabobko/AeroSpace#160]
I noticed that moving a window that has multiple tabs (for example Chrome) into a workspace that has another window in it already makes those windows appear one at a time and no proper resizing of them actually works. 

I use tabs for my chrome browsing and those tend to change titles with the change of the active tab. But I also have sort of the same problem with alacrity which I use with tmux and every time I switch to different session it tends to change its title. 

So I am not sure if this is the reason but it is an odd experience. I was curious if this is a known issue?

**Comment by nikitabobko** [comment]
> it already makes those windows appear one at a time and no proper resizing of them actually works

Sorry, it's unclear what you mean

**Comment by ashneyderman** [comment]
i will close it for now. i upgraded aerospace, rearranged everything and can not reproduce it anymore. if I have time later I will try to record a video ...
