### ISSUE TITLE
Ignore the notch

### ISSUE THREAD

**Issue by khoi** [nikitabobko/AeroSpace#176]
On the built in Retina display, is there a way to ignore the notch and expand to the full height of the screen?

Currently I have `gaps.outer.top = [{ monitor."Studio Display" = 8 }, 6]` and the `6` is counted from the notch's bottom.

A negative value doesn't seem to work and it the same as 0

**Comment by nikitabobko** [comment]
macOS doesn't allow to put arbitrary windows above the notch's bottom line

**Comment by khoi** [comment]
got it, let's close this then

**Comment by aymericbeaumet** [comment]
@nikitabobko: Alacritty is able to ignore the notch with the `SimpleFullscreen` option ([documentation](https://alacritty.org/config-alacritty.html)). Is that something that AeroSpace can mimic or does it have to be implemented at the app level?
