### ISSUE TITLE
Question: Is it possible to have some workspaces in tiling mode and some workspaces in accordion mode?

### ISSUE THREAD

**Issue by isaacraja** [nikitabobko/AeroSpace#181]
Is it possible to have some workspaces in tiling mode and some workspaces in accordion mode? For example, I might want to have all my terminal windows in workspace 3 and tiled. But all my different browsers windows in workspace 3 to be h_accordion or v_accordion. 

There is this `default-root-container-layout = 'accordion'` but i couldn't see it applied to all workspaces on start(may be i'm understanding it wrong)

**Comment by nikitabobko** [comment]
You can use `after-startup-command` to set different layouts per-workspace 
```
after-startup-command = [
    'workspace 3', 'layout h_tiles', 'workspace-back-and-forth',
    'workspace 4', 'layout h_accordion', 'workspace-back-and-forth'
]
```

**Comment by isaacraja** [comment]
Thanks! That worked.
