### ISSUE TITLE
Can I have Aerospace log the keyboard shortcuts its receiving?

### ISSUE THREAD

**Issue by alper** [nikitabobko/AeroSpace#182]
I have a weird situation where up/down work but left/right don't work anymore for this setting:

```
ctrl-cmd-alt-left = 'move left'
ctrl-cmd-alt-down = 'move down'
ctrl-cmd-alt-up = 'move up'
ctrl-cmd-alt-right = 'move right'
```

Can I see whether Aerospace is receiving these shortcuts?

Not sure how to get it to log or to print out verbose messages.

**Comment by nikitabobko** [comment]
Right now, there is no logging, it might be added in the future

Meanwhile, I just checked your bindings, and they work on my machine, so I think something intercepts the keys in your environment.

Please make sure that skhd, karabiner, or similar, don't intercept the keys
