### ISSUE TITLE
Big Sur support?

### ISSUE THREAD

**Issue by HeiA1** [nikitabobko/AeroSpace#189]
Are there any plans or possibilities on making AeroSpace work for OS versions older than ventura?
i would love to have this on my MBP from early 2014

**Comment by nikitabobko** [comment]
macOS 12 Monterey support request #147 

Big Sur is even older - it's macOS 11

---

I don't have plans to support older macOS myself. AeroSpace already depends on macOS 13 runtime support. See #147

Attempts from the community are welcome
