### ISSUE TITLE
`move-workspace-to-display next` doesn't' use all displays

### ISSUE THREAD

**Issue by mike1808** [nikitabobko/AeroSpace#19]
# Description

`move-workspace-to-display next`  doesn't cycle through all monitors and only switches between two.

# Details
I have 3 monitors and whenever I need to move a workspace to a different monitor I have to perform the following actions:
1. If I need to move workspace A to monitor 2 from monitor 1, I'll do `move-workspace-to-display next`.
2. If it worked. It's done. 
3. If it didn't work and instead moved to monitor 3. I'll do `move-workspace-to-display next` again. It moves the workspace back to monitor 1.
4. I go to a workspace on the monitor 2 and move it to the other one.
5. I go back to a workspace A and do `move-workspace-to-display next` and it works.

**Comment by nikitabobko** [comment]
Sanity check: are your monitors ("monitor 1", "monitor 2", "monitor 3") ordered in the same order as they mentioned in the AeroSpace tray icon?

> If it worked. It's done.

Are you saying that sometimes it works and sometimes it doesn't?

**Comment by nikitabobko** [comment]
No worries, I managed to reproduce it

**Comment by nikitabobko** [comment]
It will be fixed in 0.5.0-Beta

**Comment by nikitabobko** [comment]
Actually, it's really easy to release a fix update

I just published a 0.4.3-Beta. It contains the fix for this bug

**Comment by mike1808** [comment]
> Actually, it's really easy to release a fix update
> 
> I just published a 0.4.3-Beta. It contains the fix for this bug

Not sure if this is brew recipe or brew issue itself, but I'm unable to upgrade:

```bash
==> Backing App 'AeroSpace.app' up to '/usr/local/Caskroom/aerospace/0.4.1-Beta/AeroSpace-v0.4.1-Beta/AeroSpace.app'
==> Removing App '/Applications/AeroSpace.app'
==> Moving App 'AeroSpace.app' to '/Applications/AeroSpace.app'
==> Backing App 'AeroSpace.app' up to '/usr/local/Caskroom/aerospace/0.4.3-Beta/AeroSpace-v0.4.3-Beta/AeroSpace.app'
==> Removing App '/Applications/AeroSpace.app'
==> Purging files for version 0.4.3-Beta of Cask aerospace
==> Purging files for version 0.4.3-Beta of Cask aerospace
Warning: Reverting upgrade for Cask aerospace
==> Moving App 'AeroSpace.app' to '/Applications/AeroSpace.app'
Error: nikitabobko/tap/aerospace: It seems there is already a Binary at '/usr/local/bin/aerospace'.
```

**Comment by mike1808** [comment]
@nikitabobko I assume this was not intentional:

```
$ aerospace -v
dyld[94041]: Symbol not found: _$sSa12_endMutationyyFyXl_Ts5
  Referenced from: <096B2A2B-2F45-3F73-8DAB-87999038DAA8> /usr/local/Caskroom/aerospace/0.4.3-Beta/AeroSpace-v0.4.3-Beta/aerospace (built for macOS 14.0 which is newer than running OS)
  Expected in:     <087DADAD-D590-35EA-AC4D-7B0E966804EB> /usr/lib/swift/libswiftCore.dylib
[1]    94041 abort      aerospace -v
```

**Comment by nikitabobko** [comment]
> built for macOS 14.0 which is newer than running OS

Hmm, interesting, I didn't change anything in Xcode project and build scripts between 0.4.3-Beta and 0.4.1-Beta...

https://github.com/nikitabobko/AeroSpace/compare/v0.4.1-Beta...v0.4.3-Beta

**Comment by nikitabobko** [comment]
I suppose that AeroSpace.app doesn't launch as well?

**Comment by nikitabobko** [comment]
I think it's only cli that didn't work. Probably I built 0.4.1 release when I was on macOS 13. Now I pin the macOS deployment target for cli as well https://github.com/nikitabobko/AeroSpace/commit/378ff452290245869c14fd3e73050c82819c6213

I pushed 0.4.4-Beta with the fix

Thanks for the quick reaction

**Comment by mike1808** [comment]
@nikitabobko sorry, I already upgraded to 14.

**Comment by mike1808** [comment]
And the fix works. Thank you for the quick fix!

**Comment by vitor-alves** [comment]
Thanks for fixing this. I was having issues and started suspecting it might be a bug.

**Comment by vitor-alves** [comment]
@mike1808 
Try the following:

[workspace-to-monitor-force-assignment]
0 = 'built-in'
1 = 'secondary'
2 = 'secondary'
and so on.....

Basically you have to remove the "workspace_name_" prefix.

the text on the left should be the actual name of the workspace, which is most cases is 1,2,3,4.....

**Comment by mike1808** [comment]
> @mike1808 Try the following:
> 
> [workspace-to-monitor-force-assignment] 0 = 'built-in' 1 = 'secondary' 2 = 'secondary' and so on.....
> 
> Basically you have to remove the "workspace_name_" prefix.
> 
> the text on the left should be the actual name of the workspace, which is most cases is 1,2,3,4.....
> 
> Maybe the documentation could make it clearer. I had the same issue, before I figured this out.

Thanks! That helped. But also, I needed to be more specific about the monitors since the `built-in` and `secondary` got mixed up since my `main` is set on external display.

```
0 = 'built-in'
1 = ['p2720dc', 'secondary']
2 = ['p2720dc', 'secondary']
3 = ['p2720dc', 'secondary']
4 = ['p2720dc', 'secondary']
5 = ['p2723qe', 'main']
6 = ['p2723qe', 'main']
7 = ['p2723qe', 'main']
8 = ['p2723qe', 'main']
9 = ['p2723qe', 'main']
```

**Comment by nikitabobko** [comment]
I changed the documentation, now it should be better https://github.com/nikitabobko/AeroSpace/commit/a193cd8446af7bca1b97349cfaeb06bae7fe06d2

> But also, I needed to be more specific about the monitors since the built-in and secondary got mixed up since my main is set on external display.

@mike1808 sanity check: it's the quirk of your setup, it's not an AeroSpace bug, right?

**Comment by mike1808** [comment]
> @mike1808 sanity check: it's the quirk of your setup, it's not an AeroSpace bug, right?

Yes, but i'll test more :) 
Thanks for the docs update.
