### ISSUE TITLE
bug: support for 4 modifier keys / super key

### ISSUE THREAD

**Issue by srsholmes** [nikitabobko/AeroSpace#192]
It seems when i try and set my config to something like 

```
ctrl-alt-cmd-shift-left = 'focus left'
```
It does not work. 

It works fine with 

```
ctrl-alt-cmd-left = 'focus left'
```

I have caps lock remapped to `ctrl-alt-cmd-shift` with karibaner elements, aka a super key. 

It would be really handy to allow this in AeroSpace. 

Thanks for your hard work on this project, I am really enjoying it! I think it will replace yabai as my daily driver. 🔥

**Comment by nikitabobko** [comment]
I've just checked `ctrl-alt-cmd-shift-left` binding and it works in my environment. Sonoma, AeroSpace 0.9.2

Please check that there is no other software running that may intercept this shortcut (e.g. skhd, karabiner)

**Comment by srsholmes** [comment]
My mistake! I still had skhd service running from my yabai setup. 

Apologies once again, thanks for getting back to me.
