### ISSUE TITLE
Doesn't place nice with Maccy

### ISSUE THREAD

**Issue by prestonr83** [nikitabobko/AeroSpace#194]
When trying to open maccy even when it is set in floating mode it immediately closes the window.

```
[[on-window-detected]]
if.app-id = 'org.p0deje.Maccy'
check-further-callbacks = true
run = ['layout floating']
```

![output](https://github.com/nikitabobko/AeroSpace/assets/5903168/4f0a425e-3919-4a5b-83f3-d972a9d8c0d8)

**Comment by nikitabobko** [comment]
I can't reproduce it, please make sure that it's AeroSpace who steals the focus

**Comment by prestonr83** [comment]
Ah you are correct it was front_app in sketchybar

Adding following to front_app.sh resolved the issue

```
if [ "$INFO" = "Maccy"  ]; then
  exit
fi
```

Thanks
