### ISSUE TITLE
How to enable automatic sizing reset for containers

### ISSUE THREAD

**Issue by RollerMatic** [nikitabobko/AeroSpace#197]
I was wondering if it's possible to enable resetting the sizing of windows automatically through the .toml configuration

For example, 
If there were 3 windows on my screen 
![image](https://github.com/nikitabobko/AeroSpace/assets/74332704/15010d24-4da6-4718-bb25-089d0a9e1289)

and I minimized one , I wanted my final screen configuration to have the windows auto adjust the sizes
![image](https://github.com/nikitabobko/AeroSpace/assets/74332704/e3ad67f0-b158-4476-bd98-dda274759de9)

Currently, the windows retain their original sizing 
![image](https://github.com/nikitabobko/AeroSpace/assets/74332704/3c8b1ea0-1608-4487-9630-31c46703ed2c)

I read through the documentation [here](https://nikitabobko.github.io/AeroSpace/guide), and it seems like "enable-normalization-flatten-containers=True" should already enable this. It's possible I didn't understand the intent quite correctly because I haven't used i3 before.
Here is my [current configuration.](https://pastebin.com/zgjdx9DQ), and I am using MacOS Sonoma 14.4.1.

**Comment by nikitabobko** [comment]
What version do use? It should work the way you describe it since 0.9.0. See #18

**Comment by RollerMatic** [comment]
Works, thanks @nikitabobko !
