### ISSUE TITLE
[bug] Horizontal accordion sub layout spacing is off.

### ISSUE THREAD

**Issue by PrestonCS** [nikitabobko/AeroSpace#203]
When using accordion layout horizontally it leaves a space at the top where the vertical accordion overlap would be. Push both windows down. Example

![layoutIssue](https://github.com/nikitabobko/AeroSpace/assets/147094508/51d401cb-e929-41e4-88fd-970c45ea6c5f)

**Comment by nikitabobko** [comment]
Please see #96 

I plan to drop the default "indentation" in the next release, but right now you can disable it manually `indent-for-nested-containers-with-the-same-orientation = 0`

My other recommendation is to keep normalizations enabled. Normalizations keep you away from weird layouts

**Comment by PrestonCS** [comment]
Thanks
