### ISSUE TITLE
Qutebrowser with `window.hide_decoration` setting enabled broken

### ISSUE THREAD

**Issue by aslak01** [nikitabobko/AeroSpace#208]
#204 seems to have broken this setting to hide the top status bar of Qutebrowser. With the setting enabled the browser just floats as it likes and doesn't respect keybindings.

**Comment by nikitabobko** [comment]
Yes, qutebrowser is a very misbevahing app https://github.com/nikitabobko/AeroSpace/issues/166#issuecomment-1953215560

When `window.hide_decoration` is enabled AeroSpace can't distinguish dialogs from non-dialogs.

You can try to write your custom `on-window-detected` rule

**Comment by aslak01** [comment]
Oh yeah, https://github.com/nikitabobko/AeroSpace/issues/166#issuecomment-1953201605 works to solve the issue. Thanks!

**Comment by aslak01** [comment]
Sad to hear qutebrowser is so annoying to deal with, the vim bindings and vim like behaviours it implements are really amazing, but it's a little bit rough around the edges in the UI.
