### ISSUE TITLE
[Feature Request] Provide alternative path for configuration file in `.config/`

### ISSUE THREAD

**Issue by XOR-op** [nikitabobko/AeroSpace#21]
For modern CLI (and not CLI) app, storing the configuration directly under the home directory is no longer a trend. Storing it under `.config/` will be much tidier. And considering AeroSpace won't introduce big breaking change for configuration, I believe it will be beneficial if we can have a second configuration location, i.e. `~/.config/aerospace.toml` (simplest) or `~/.config/aerospace/config.toml` (if you want to add other configuration files in the future, e.g. subconfigs, external assets). If `.aerospace.toml` doesn't exist, then AeroSpace will read files under `.config/`.

**Comment by nikitabobko** [comment]
I expected that somebody would submit this issue one day or another

The reasons why I didn't implement it "properly" from the beginning:
- It's unclear whether I should respect `XDG_CONFIG_HOME` environment variable (some apps respect it and others don't)
  - The decision on supporting it should be based on how easy it is to add environment variables for GUI apps in macOS (I never tried doing so, so I don't know it yet)
- Normally, macOS uses `$HOME/Library/Preferences` or `$HOME/Library/Application Support`. I have not decided yet on whether I want to support them as alternative paths

**Comment by XOR-op** [comment]
>     * It's unclear whether I should respect `XDG_CONFIG_HOME` environment variable (some apps respect it and others don't)

Considering it could be a good option, but I don't see a lot of users setting this up. Instead, I see many applications either hardcoding `.config`, or supporting both version of configs.

>     * Normally, macOS uses `$HOME/Library/Preferences` or `$HOME/Library/Application Support`. I have not decided yet on whether I want to support them as alternative paths

Since AeroSpace uses the minimum amount of GUI, I would rather think it's a CLI app, which will usually not follow macOS's tradition but have more similarity with Linux's.

If we support multiple alternatives for config path, I don't think these concerns would become a issue since we can support them all. And I don't think the order will matter since typically users will only put their configuration at one place and they have to do it manually.

**Comment by sxyazi** [comment]
Agree with @XOR-op. To me, AeroSpace feels more like a CLI program - it has no interactive UI and relies on users to edit configurations manually.

I believe respecting `XDG_CONFIG_HOME` and checking `~/.aerospace.toml`, `$XDG_CONFIG_HOME/.config/aerospace.toml` in turn would be a reasonable choice.

Thank you so much for creating AeroSpace; I love it, especially since it doesn't need to disable SIP <3

**Comment by januz** [comment]
Another vote for allowing alternative locations. My preference would be `~/.config/aerospace/config.toml` as mentioned above

**Comment by nikitabobko** [comment]
Released in 0.8.0-Beta
