### ISSUE TITLE
keep app in workspace  in after-startup command

### ISSUE THREAD

**Issue by glepnir** [nikitabobko/AeroSpace#214]
currently i use this config, it will open kitty and chrome on workspace 3 because seems like it start application async when i open kitty current workspace is focused on 3 , but i want keep the kitty in workspace 1 chrome in workspace 3. 

```conf
after-startup-command = [
  'workspace 1',
  'exec-and-forget open -n /Applications/kitty.app',
  'workspace 3',
  'exec-and-forget open -n /Applications/Google\ Chrome.app',
]
```

**Comment by nikitabobko** [comment]
You can do this:
```
after-startup-command = [
  'exec-and-forget open -n /Applications/kitty.app && sleep 1 && aerospace move-node-to-workspace 1 ',
  'exec-and-forget open -n /Applications/Google\ Chrome.app && sleep 1 && workspace 3',
]
```

Please note `sleep 1`. It's needed because `open` finishes faster than the window appears. Please follow #226 for updates on "sleep 1" problem

**Comment by glepnir** [comment]
make sense.
