### ISSUE TITLE
I have created a Raycast Extension

### ISSUE THREAD

**Issue by limonkufu** [nikitabobko/AeroSpace#215]
Hi @nikitabobko ,

Thank you very much for the awesome window support that your app brings. I myself struggle a lot remembering shortcuts so I went ahead and created a small raycast application and menubar extension to help myself to search for things easily until it becomes muscle memory.

I don't know whether you'd like to mention in anywhere in the docs or so that I can contribute it the docs myself.

You can check it out here: https://www.raycast.com/limonkufu/aerospace

Let me know what you think and again thanks for the awesome app.

**Comment by nikitabobko** [comment]
Very cool, thank you! I'm glad to see such contributions

> I don't know whether you'd like to mention in anywhere in the docs or so that I can contribute it the docs myself.

I'm 100% for mentioning all the cool stuff around AeroSpace. There is a special page for it https://nikitabobko.github.io/AeroSpace/goodness

I've mentioned the extension in the docs https://github.com/nikitabobko/AeroSpace/commit/22c958fb9a87b8a540559fbb2fef4f58e0cef983 

Feel free to submit a PR if you prefer a different wording/advertisement

It will appear on the site when I rebuild the site

---

**Note 1.** I've left a few questions in the Raycast PR https://github.com/raycast/extensions/pull/12122

**Note 2.** I notice that you parse the `~/.aerospace.toml` file by yourself in the extension (and users also need to manually pick the location of the file).

Would the extension benefit from CLI commands that allow querying AeroSpace config state? I can introduce "plumbing" commands like `aerospace list-bindings --mode <mode>`, `aerospace list-modes`. The commands can be made to output the data in JSON format with `--json` flag for easier consumption by the extension

**Note 3.** I notice that you try to run command by triggering the bindings with AppleScript. It's fragile and it didn't work on my machine:

<img width="375" alt="image" src="https://github.com/nikitabobko/AeroSpace/assets/20517828/428fc5a7-c85a-4325-a2a6-a39de5942ee7">

I can introduce the CLI command to run aerospace commands by bindings. Like `aerospace trigger-binding alt-1`. Will it be possible for the extension to use those commands? WDYT?

---

Again, thank you!

**Comment by limonkufu** [comment]
Yes I can make those changes so that I can use aerospace itself properly instead of AppleScript or parsing the config file. That would be great 👍 
I was at unease since I wasn't using aerospace itself at all in the extension

**Comment by limonkufu** [comment]
I am glad you like it 😊  Also, i will reply to your comments on the MR and improve it 👍

**Comment by nikitabobko** [comment]
0.11.0-Beta comes with the following:
- (1) `reload-config` now also prints errors to stdout. `reload-config` now returns correct exit code
- (2) Add `[--no-gui]` `[--dry-run]` flags to `reload-config`.
- (3) Introduce `config` command to query AeroSpace config state.
- (4) Introduce `trigger-binding` "plumbing" command to trigger AeroSpace binding as if they were pressed by user.

You can use (1) and (2) to validate the config without reloading it https://github.com/raycast/extensions/pull/12122#discussion_r1602676990

**Comment by limonkufu** [comment]
@nikitabobko Great! I think I can push a new version during next week and will ping you in the new MR :)

**Comment by nikitabobko** [comment]
@limonkufu please note that 0.12.0-Beta comes with the breaking change for `config` command. Output format is slightly different

https://github.com/nikitabobko/AeroSpace/commit/fdc143c71fca94c65c1d21eefea81c51b851a901

Since Raycast extension doesn't depend on this API yet, I think it's fine to break it

The new output better aligns with future embedded shell-like combinators https://github.com/nikitabobko/AeroSpace/issues/278

**Comment by limonkufu** [comment]
> @limonkufu please note that 0.12.0-Beta comes with the breaking change for `config` command. Output format is slightly different
> 
> https://github.com/nikitabobko/AeroSpace/commit/fdc143c71fca94c65c1d21eefea81c51b851a901
> 
> Since Raycast extension doesn't depend on this API yet, I think it's fine to break it
> 
> The new output better aligns with future embedded shell-like combinators https://github.com/nikitabobko/AeroSpace/issues/278

Thanks for letting me know. I had some personal issues but i will update the plugin this week 👍👍

**Comment by thewinger** [comment]
Hi!
I've published a PR to the extension that adds the functionality to change between apps in the current workspace.

PR: https://github.com/raycast/extensions/pull/14886

The motivation is that I have multiple windows of the same app across multiple workspace (alacritty or Arc browser in main workspace and in work workspace, for example), and sometimes if I CMD+TAB, it takes me to a different workspace, I think depending on the last window of the app that it was active. 
So, I thought to create this command and assign it ALT+TAB to change between apps in the current workspace.

I was going to publish it as a different extension but saw in Raycast's guidelines that they favor grouping all commands of an app under one extension.

Hope you don't mind.
