### ISSUE TITLE
All keys are ignored

### ISSUE THREAD

**Issue by tluyben** [nikitabobko/AeroSpace#223]
I use i3 on Linux exclusively as window manager, so I thought I give this ok. Install goes well (following the brew install from the manual), I added the .aerospace.toml i3 config and it starts, shows the application in the top bar, but nothing works keyboard wise. 

What am I missing / doing wrong? It just does nothing, no matter what I press alt-1, alt-j, etc. I tried the other modifier keys but nothing works. Must be something silly I am overlooking? I am on Sonoma.

**Comment by 0xFlo** [comment]
same here I think it's just conflicting with existing keybindings from other apps / macos because some work some don't but overall it's a bit frustrating as a beginner trying to figure out working keybindings.

**Comment by tluyben** [comment]
Hopefully someone has a workaround because I don’t have any global apps running that catch keys as far as I know. I guess there must be a way to shut down keybindings one by one and see which app it is?

**Comment by tluyben** [comment]
Reopen.

**Comment by tluyben** [comment]
Alright, so for some reason (however strange as this is a new laptop), in the Keyboard shortcut system settings, Option was set to 'No Action'. After changing Option = Option, everything works as expected.
