### ISSUE TITLE
Feature Request: Option to alternate layouts when opening windows

### ISSUE THREAD

**Issue by paulodiovani** [nikitabobko/AeroSpace#228]
I want to be able to alternate layouts (vertical, horizontal, vertical...) when opening new windows, similar to what this i1 plugin do: https://github.com/olemartinorg/i3-alternating-layout

Is there a way to achieve this today?
If not, can we add as a feature request?

**Comment by nikitabobko** [comment]
> Is there a way to achieve this today?

No, it's not possible yet

> If not, can we add as a feature request?

Once the on-focus-changed callback is introduced #230 and the command to query the tree is introduced #16, it should be possible to implement a similar alternate layouts script

**Comment by paulodiovani** [comment]
Another (even better) option would be to have a layout that prioritize a single window, always giving it the biggest piece of the screen.

Similar to [Hyperland `master` layout](https://wiki.hyprland.org/Configuring/Master-Layout/) or [Amethyst `tall` layout](https://ianyh.com/amethyst/#tall)

**Comment by cornz** [comment]
This would be a great addition as I'm also very used to have a layout like this on my second monitor on all workspaces:
<img width="116" alt="image" src="https://github.com/user-attachments/assets/c40fd790-6894-4270-b78d-f82c9989fe95">


This works flawlessly by default on yabai and would be great to have on aerospace, too

**Comment by nikitabobko** [comment]
I'm closing this issue in favor of two others:
- AeroSpace already supports `on-focus-changed`. Once `tree` command is supported #16, I think the "alternate" layouts can be hacked by external plugins (like i3 does it)
- A better alternative is to explore the idea of declarative normalizations #260

**Comment by paulodiovani** [comment]
Hi again,
I got close to make this work with a keybinding.

![Screen Recording 2024-09-04 at 16 43 59](https://github.com/user-attachments/assets/244216cc-f963-4bae-be0c-d6f331dbbde6)

I'm using `exec-and-forget` to count how many windows are opened to decide which if `join-with` should be called with `up` or `left`.

```toml
[mode.main.binding]
cmd-shift-h = 'join-with up'
cmd-shift-v = 'join-with left'
cmd-shift-e = '''exec-and-forget if [ $(expr $(aerospace list-windows --workspace focused | wc -l) % 2) -eq 0 ]; then
  aerospace join-with up;
else
  aerospace join-with left;
fi
'''
```

Of course, rely on window count is a terrible solution and will break if there are floating windows around, but I plan to rewrite this using `tree` when #16 is available.

I wanted to use with `on-window-detected` callback, but it does not accept `exec-and-forget`.

**Comment by 8o8inCodes** [comment]
@paulodiovani can you share your final solution if you managed to do it?
