### ISSUE TITLE
Feature: on-focus-changed callback

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#230]
AeroSpace already has two callbacks: `on-window-detected` and `exec-on-workspace-changed`

It'd be cool to have one more callback to track when the focus changes

**Comment by garo** [comment]
I have another use case where this would probably be useful: I'd like to define a minimum window size for some applications, so that on-focus event would enlarge the app window to be at least the defined minimum size. I guess this would also require an additional command or an option to `resize` command to support the at-least principle.

**Comment by nikitabobko** [comment]
@garo why can't you use `on-window-detected` for that? Set the minimum size once and don't touch it anymore

**Comment by garo** [comment]
> @garo why can't you use `on-window-detected` for that? Set the minimum size once and don't touch it anymore

I have this especially with how I'm using Slack: I like to keep Slack in one Workspace together with a browser and I'm often shrinking Slack to have more space for the browser. Then when I do focus Slack I'd like it to grow bigger. I've just switched from Amethyst and that somehow supported this out-of-the-box and I noticed I'm missing this feature. I figured out I probably could emulate this with the hypotechical on-focus callback and `move` command.

**Comment by nikitabobko** [comment]
Implemented in 0.13.0-Beta

**Comment by tobiasgiese** [comment]
@nikitabobko using `on-focus-changed` in combination with `aerospace list-windows --workspace $ws` is pretty slow as it uses alot of resources.
My current implementation is:

`.aerospace.toml`
```toml
on-focus-changed = [
    'exec-and-forget sketchybar --trigger aerospace_workspace_change FOCUS_CHANGE=true'
]
```

my event script:
```bash
if [[ "$FOCUS_CHANGE" == "true" ]]; then
    FOCUSED_WORKSPACE="$(aerospace list-workspaces --focused)"
    if [[ "$NAME" = "space.$FOCUSED_WORKSPACE" ]]; then
        rewriteSketchybar "$FOCUSED_WORKSPACE"
    fi
fi
```

Is it maybe possible to add the focused workspace to every event? This would reduce alot of aerospace queries.
Also the focused monitor would be helpful. WDYT?

**Comment by nikitabobko** [comment]
> Is it maybe possible to add the focused workspace to every event? This would reduce alot of aerospace queries.
Also the focused monitor would be helpful. WDYT?

Yes, that makes sense. I planned to expose it to the callbacks as an environment variable. Feel free to open a tracking issue for it
