### ISSUE TITLE
question: anyway to list all apps and their workspace ids?

### ISSUE THREAD

**Issue by PoiScript** [nikitabobko/AeroSpace#232]
hi, thanks you for the hard work on areospace, it is a great tool!

I'm now migrating from yabai to areospace. But I cannot to find an equivalent for the `yabai -m query --windows` command, which returns all applications and their workspace ids. 

In my setup, this command is essential to build an app switch bar in sketchybar, which looks like: 

<img width="610" alt="image" src="https://github.com/nikitabobko/AeroSpace/assets/17513314/1d0a650b-6b38-49d1-b383-2e5adc364e0d">

**Comment by nikitabobko** [comment]
You can do several CLI invocations:
```
for workspace in $(aerospace list-workspaces --monitor all --empty no); do
    echo "Workspace: $workspace"
    aerospace list-windows --workspace $workspace
    echo
done
```
Output example:
```
Workspace: C
1693 | Calendar | Calendar

Workspace: T
52 | Alacritty | /Users/Nikita.Bobko $ t
```

But there is a tracking issue to support `tree` command that would allow to get structure of all monitors, workspaces and windows tree in one go #16

**Comment by PoiScript** [comment]
thanks for your quick reply! i'm going to close this issue and keep an eye on #16.

**Comment by nikitabobko** [comment]
In 0.12.0-Beta, `list-windows` comes with the `--format` flag that can be used to print to windows with their workspaces
