### ISSUE TITLE
Option to hide windows instead of resizing them into the corner

### ISSUE THREAD

**Issue by microBob** [nikitabobko/AeroSpace#235]
Some applications take a long time to resize (for example, the Unity Editor) because it's graphically intense for some reason. This makes switching workspaces and doing operations extremely slow (several seconds of delay) because the app waits for Unity to resize into the corner (or come back out).

It would be great if there could be an option for windows not in the active workspace to be hidden cmd+h style rather than be made smaller and pushed to the corner. This will make it faster to hide and re-open them when transitioning workspaces.

Thanks!

**Comment by nikitabobko** [comment]
AeroSpace doesn't resize windows when it hides them. All the apps are sensitive to resizing, not only Unity Editor

Question: do you have several monitors?

Because what I think you observe is that the window is pushed to the bottom right corner of the most right monitor, and monitors have different resolutions. See #149

**Comment by kjy5** [comment]
Ah, that makes sense. It’s not window resizing but monitor switching with different resolutions that is slowing things down. 

Regardless, is there a reason why windows are pushed into the corner rather than hidden or minimized? Can there be an option to do it this way?

**Comment by microBob** [comment]
Ah good to know. It was definitely having a second monitor at a different resolution. Either ways, is there an option to hide windows or minimize them instead of putting them in the corner?

**Comment by nikitabobko** [comment]
> Either ways, is there an option to hide windows or minimize them instead of putting them in the corner?

Not yet, but that is the area that is yet to be investigated. The tracking issue for this feature is #149

**Comment by microBob** [comment]
Got it. Thank you.
