### ISSUE TITLE
Feature Request: Maximized Layout

### ISSUE THREAD

**Issue by parker789** [nikitabobko/AeroSpace#249]
I know this is meant to mimic i3 and other tiling WMs, but would it be difficult to implement another `maximized` layout type similar to other dynamic WMs?

Just to clarify the behavior, I'm looking to have `n` apps within a single workspace, and when in `maximized` layout, all apps are forced into `fullscreen`, and you can switch between them with `focus left` & `focus right`. 

Awesome project nonetheless, setup and install were much easier than yabai/skhd, and I haven't noticed any weird flicker or window behavior yet.

**Comment by nikitabobko** [comment]
accordion layout already does what you want

You can also set accordion-padding to zero to get completely "maximized" experience

**Comment by parker789** [comment]
Oh, awesome! I cycled through using the default config, but the padding was throwing me off. Thanks! Closing this.
