### ISSUE TITLE
A different approach for workspace management

### ISSUE THREAD

**Issue by lajoskvcs** [nikitabobko/AeroSpace#253]
Hey everyone! 👋 
First and foremost, thank you for this amazing piece of work! I truly missed something like this on macos, since other alternatives are not usable in strict work environment, due to system integrity protection. This application is Godsend! 

I was thinking about how to solve the visible application on the bottom right corner problem.

I read in the docs, that:
> For better or worse, macOS doesn’t allow to place windows outside the visible area entirely. You will still be able to see a few pixels of "hidden" windows in the bottom right corner of your screen. That means, that if AeroSpace crashes badly you will still be able to manually "unhide" the windows by dragging these few pixels to the center of the screen.

And the reasoning behind that is:
> Apple doesn’t provide public API to communicate with Spaces (create/delete/reorder/switch Space and move windows between Spaces)

I checked the state of this in hammerspoon, since I remembered, that I managed that somehow before and it's still doable:
https://github.com/Hammerspoon/hammerspoon/issues/3111

Do you think moving the currently invisible applications into a different space would do the trick? I don't mind to have two different spaces (1. the actual visible space where I manage my AeroSpace workspaces and 2. the space where all the non-visible windows are)

Thanks in advance!

If you are happy with the proposed solution, I'm more than happy to open a PR in the following weeks!

**Comment by nikitabobko** [comment]
Moving windows between macOS Spaces requires private API usage, it goes against values of the project.

You may also heard that Apple broke those private APIs in a recent macOS 14.5 update and all the apps that were using them had been broken until they found a workaround.

I agree that the current approach of hiding windows can be improved though, see: #149 #219
