### ISSUE TITLE
General feedback on v0.5

### ISSUE THREAD

**Issue by aimran-adroll** [nikitabobko/AeroSpace#26]
Thank you for the wonderful tool. Its definitely a breath of fresh air for those of us on macos with i3 envy!

I spent 2 days with it (v0.5beta) and figured I detail my experience in case its useful (take it with a pinch of salt given my inexperience with the tool):

Good
1. docs are really nice and to the point
2. installation is a breeze  (esp not having to deal with SIP shenanigans)
3. I love the minimal menu-bar

Needs-work
1. configurations are hit and miss. Reload would sometime take but say missed half the time. If lucky then there would be a parser error. Otherwise nothing but silent fail.
2. focus stopped working randomly  (alt-h works but alt-l mysteriously stops working)
3. Re-mappings did not always work. E.g. I can remap alt-enter. But exact same command with `alt-t` refuses to work. I double checked there are no duplicates or anything. `alt-t` keeps taking me to workspace=T. It would be helpful if I could make it dump out current key mappings for debugging.
4. Relaunching causes quite a bit of mess. I suppose I can use the after-startup command to clean things up a bit
5. alt-0 sometime refuses to go to workspace 0. I'd say 3 out of 5 times. I have to use the menubar to go there -- sometime even that does not work (then I click on the app that I _know_ is in space 0 on the dock)
6. docs mention v0.6 (e.g callback), but I could not find that version on the release page.

Once again, thank you for your hard work.

**Comment by aimran-adroll** [comment]
Did some digging. Looks like my default browser wezterm was blocking while spawning a new window. So that was messing up aerospace. So I will retract (2) and (3) 😌

**Comment by nikitabobko** [comment]
Thanks for the feedback!

> Reload would sometime take but say missed half the time. If lucky then there would be a parser error. Otherwise nothing but silent fail.

I'd be happy if you could provide a reproducer. Normally, if something fails during config parsing, a terminal should open up with the error message:

<img width="682" alt="image" src="https://github.com/nikitabobko/AeroSpace/assets/20517828/9eb25583-d1e8-4c71-8b79-99b352aa2080">

> Relaunching causes quite a bit of mess

Well, yes. Right now, AeroSpace doesn't preserve the layout during relaunch. Please open an issue, if you think that's a problem. Normally, you shouldn't be relaunching the AeroSpace

> alt-0 sometime refuses to go to workspace 0. I'd say 3 out of 5 times. I have to use the menubar to go there -- sometime even that does not work (then I click on the app that I know is in space 0 on the dock)

That's weird. Is it specifically about workspace 0? Can you please rename the workspace 0 and see if the problem happens with the new lexically smallest workspace?

Are you sure that you don't have any other app that intercepts alt-0 shortcut?

> docs mention v0.6 (e.g callback), but I could not find that version on the release page.

0.6.0-Beta version is in development. It's in `main` branch, it's not yet released.

**Comment by alper** [comment]
> Otherwise nothing but silent fail.

It would be nice if the major mode switches would flash a quick toast as feedback. Especially in the beginning this is very useful to get to know the thing after wich you should be able to disable it.
