### ISSUE TITLE
Tray icon not appearing

### ISSUE THREAD

**Issue by alexander-turner** [nikitabobko/AeroSpace#262]
I'm on macOS 14.5 and I don't see any icon in the top-right. Am I supposed to enable a setting?
<img width="709" alt="image" src="https://github.com/nikitabobko/AeroSpace/assets/3458070/d5523918-4384-446b-b741-3a056bc1ae10">

**Comment by nikitabobko** [comment]
> Am I supposed to enable a setting?

No, it should work out of the box

---

I suspect that you simply don't have enough room to show all tray icons

https://discussions.apple.com/thread/253984123?sortBy=rank

> You only have so much room up there. Remove less valuable menubar item to make room for your application of choice.
> 
> Use the Command key if necessary to drag off menu items or re-arrange them.

**Comment by adoolaard** [comment]
For me the icon isn't showing either. Whilst i have more than enough space left in the menu bar. Im using the MacOS Sequoia public beta.

**Comment by adoolaard** [comment]
@alexander-turner Did you manage to resolve this issue? I’ve noticed that the icon appears for about 3 seconds when I boot up my Mac, but then it disappears. Unfortunately, I can't seem to get the icon back without logging out or rebooting. Even force-quitting Aerospace and reopening it doesn't bring the icon back. Any insights?

**Comment by MatanRubin** [comment]
I'm having the same issue. From OP's screenshot, I see he's using Hidden Bar. I'm using Hidden Bar too, so that might be a clue for what's causing this issue.

Any idea why this happens?

**Comment by MatanRubin** [comment]
> Did you manage to resolve this issue?

I had the same issue, and eventually I found out that I had a BetterTouchTool configuration to hide certain items on the menu bar. If you're using BTT, Hide, or any other app that can manipulate the menu bar - start by shutting down that app and see if it resolves the issue
