### ISSUE TITLE
Windows on external main display overlay sketchybar

### ISSUE THREAD

**Issue by alvaroaleman** [nikitabobko/AeroSpace#265]
Hi there,

I have a multi-monitor setup where I use an external display as primary monitor. The MacOS menubar is configured to autohide. Windows that are on this external primary display are on top of sketchybar so that it isn't visible anymore. If I open an empty workspace I can see that it is there.

This does not happen on the main display, windows are sized in a way where sketchybar is visible.

Please let me know if there is anything I can provide that would help with understanding this and thank you for making aerospace!

**Comment by nohzafk** [comment]
You should setup something like this to use different gap for different monitor 

[gaps]
outer.top = [
  { monitor."Built-in" = 4 },
  { monitor."DELL" = 32 },
  32
]

execute `aerospace list-monitors` to see the monitor name.

**Comment by alvaroaleman** [comment]
@nohzafk thank you very much for the quick response, configuring the gap for the external display helped! What confuses me is that for the Built-In display it semms `0` is the correct config and this only has to be setup for the external display. Do you know if that is intended?

**Comment by nohzafk** [comment]
0 for built-in is fine. i set up 4 for some spaces to display the [border](https://github.com/FelixKratz/JankyBorders)
