### ISSUE TITLE
aerospace list-workspaces --focused returns multiple workspace

### ISSUE THREAD

**Issue by roycefanproxy** [nikitabobko/AeroSpace#268]
aerospace somehow created extra workspace when I connects my mac to external monitor. 
![image](https://github.com/nikitabobko/AeroSpace/assets/12816613/8e1bb6d3-317c-419b-9ec4-99cb9959b8bb)

But after I removed the monitor, the extra workspace  still remains there. Is it a bug?

**Comment by nikitabobko** [comment]
Yes, it's a known bug

You can switch to the "phantom" workspace and back to make it disappear

**Comment by nikitabobko** [comment]
Released in 0.15.0
