### ISSUE TITLE
Feature request: Use any key as modifier

### ISSUE THREAD

**Issue by FriedSnowman** [nikitabobko/AeroSpace#274]
Currently, only specific keys are seem to be supported as modifier. Is it possible to have any arbitrary key work as a modifier? In my use case, I have my caps key remapped to F19 (through `hidutil`) and I would like to use this key as a modifier.

```
f19-1 = 'workspace 1'
f19-2 = 'workspace 2'
f19-3 = 'workspace 3'
```

```
Failed to parse /Users/{user}/.aerospace.toml
mode.main.binding.f19-1: Can't parse modifiers in 'f19-1' binding
mode.main.binding.f19-2: Can't parse modifiers in 'f19-2' binding
mode.main.binding.f19-3: Can't parse modifiers in 'f19-3' binding
```

**Comment by nikitabobko** [comment]
Underlying macOS API doesn't allow that

**Comment by FriedSnowman** [comment]
I see, I guess I just assumed that this app was listening for all keypresses. Thanks for the explanation :)

**Comment by n8henrie** [comment]
FWIW Hammerspoon supports this (https://www.hammerspoon.org/docs/hs.hotkey.modal.html) -- I also use a caps -> F19 via hidutil and thereafter use caps as my non-conflicting hyper key across macos / linux systems.

If this is a must-have, users might consider using HS to call the aerospace CLI as a workaround (untested -- I'm new to aerospace).
