### ISSUE TITLE
Feature request: zoom command

### ISSUE THREAD

**Issue by karadnik-flutterint** [nikitabobko/AeroSpace#281]
Hello there, first of all - awesome work!

I want to propose a `zoom` command.

- Like the `fullscreen` command, `zoom` will be toggling the app between two sizes.
- Unlike the `fullscreen` command, `zoom` will be increasing the app size by certain amount ( say 400 by default and can be provided as a param )

**Use case:** When I have several apps opened and tiled to my liking, I sometimes want to focus more on one app. `fullscreen` is useful most of the time, but sometimes I just need to be able to see the other apps as well. I can use `resize`, but then i need to `resize` it back. Also, sometimes I forget how many times I resized and it takes effort to return it to perfect size.

**Alternative approaches:**

1. Use `resize` ( what I do now ): `alt-z = 'resize smart +400'` and `alt-x = 'resize smart -400'`
- Downsides:
  - need two hotkeys
  - user can zoom in more than once by accident

2. Possibly use `fullscreen`, but add a number argument ( and if provided, also accept a smart|width|height ), if provided - use it, if not - go fullscreen.

**Synopsis**
```
USAGE: zoom [-h|--help] (smart|width|height) <number>

OPTIONS:
  -h, --help             Print help

ARGUMENTS:
  (smart|width|height)   Dimension to resize
  <number>               Number
```

I am not a swift guy at all, but I am willing to work on this feature if it will be useful, Let me know!

**Comment by nikitabobko** [comment]
First of thanks for reading `CONTRIBUTING.md`!

But sorry, the suggested command tries to optimize very specific and unclear use case, it's too adhoc. I don't think that it will be useful for enough number of people to include a behavior like that

In general, size management is not something I want people to spend their time on. Keep it simple: If you want windows side by side, put them on the same workspace; if you want them fullscreen, put them on different workspaces
