### ISSUE TITLE
Feature Request: Keep focus on node after move `move-node-to-monitor`

### ISSUE THREAD

**Issue by shih-chris** [nikitabobko/AeroSpace#283]
This project is amazing! I just started configuring today, so this could very well be user error, but I've set up a shortcut to do `move-node-to-monitor prev` and `move-node-to-monitor next`.

It works great to move the node, however, after the node moves, I would've expected to keep focus on that node, but instead it seems like the focus moves to another node on the previous monitor.

**Comment by nikitabobko** [comment]
https://github.com/nikitabobko/AeroSpace/issues/196#issuecomment-2035246297
