### ISSUE TITLE
Bindings not working on my plugged in keyboard

### ISSUE THREAD

**Issue by alper** [nikitabobko/AeroSpace#286]
I'm not sure exactly how to debug this but it's been a bit of an annoyance recently.

I use Shift-Option-F for instance to change my window settings. This works fine on my Macbook's own keyboard (both on Dvorak and US layouts). But on my plugged in mechanical keyboard this won't work. Not sure why.

**Comment by nikitabobko** [comment]
The problem is somewhere in your configuration. It's not an AeroSpace issue
