### ISSUE TITLE
exec-and-forget not working

### ISSUE THREAD

**Issue by suvasanket** [nikitabobko/AeroSpace#287]
so i'm using emacs with
```toml
after-startup-command = [
    'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar',
    'exec-and-forget /usr/local/bin/emacs --daemon'
]
```
this for running the daemon
and to open a new frame
```toml
alt-e = ['workspace 1','exec-and-forget emacsclient -a "" -c "$@"']
```
everything was working just fine but after some restarts of aerospace
it doesn't seems to opening the "emacs frame" anymore
the daemon is running fine though

**Comment by suvasanket** [comment]
Great, just a tip if you want to open the client right from the launchpad or any app launcher like alfred you can create a automator application workflow then you can set a keybind to open that or just use it like any other app

**Comment by lentil32** [comment]
Refer to my config if you are using Nix:

```nix
file."${config.xdg.configHome}/aerospace/aerospace.toml".text = ''
      # Some configs...

      # open programs
      [mode.programs.binding]
      e = [ 'exec-and-forget ${pkgs.emacs}/bin/emacsclient -ca ""', 'mode main' ]
      f = [ 'exec-and-forget open -na "Firefox Developer Edition"', 'mode main' ]
      a = [ 'exec-and-forget open -na Alacritty', 'mode main' ]
      enter = 'mode main'
      esc = 'mode main'

      # Some configs...
''
```

I'm on MacOS nix-darwin + nix home-manager setting. Emacs is installed through nix.
It works for me.

**Comment by cristian-heredia** [comment]
> Refer to my config if you are using Nix:
> 
> ```nix
> file."${config.xdg.configHome}/aerospace/aerospace.toml".text = ''
>       # Some configs...
> 
>       # open programs
>       [mode.programs.binding]
>       e = [ 'exec-and-forget ${pkgs.emacs}/bin/emacsclient -ca ""', 'mode main' ]
>       f = [ 'exec-and-forget open -na "Firefox Developer Edition"', 'mode main' ]
>       a = [ 'exec-and-forget open -na Alacritty', 'mode main' ]
>       enter = 'mode main'
>       esc = 'mode main'
> 
>       # Some configs...
> ''
> ```
> 
> I'm on MacOS nix-darwin + nix home-manager setting. Emacs is installed through nix. It works for me.

@lentil32 did you install aerospace with nix? If so can you share your flake file?

**Comment by lentil32** [comment]
> > Refer to my config if you are using Nix:
> 
> > 
> 
> > ```nix
> 
> > file."${config.xdg.configHome}/aerospace/aerospace.toml".text = ''
> 
> >       # Some configs...
> 
> > 
> 
> >       # open programs
> 
> >       [mode.programs.binding]
> 
> >       e = [ 'exec-and-forget ${pkgs.emacs}/bin/emacsclient -ca ""', 'mode main' ]
> 
> >       f = [ 'exec-and-forget open -na "Firefox Developer Edition"', 'mode main' ]
> 
> >       a = [ 'exec-and-forget open -na Alacritty', 'mode main' ]
> 
> >       enter = 'mode main'
> 
> >       esc = 'mode main'
> 
> > 
> 
> >       # Some configs...
> 
> > ''
> 
> > ```
> 
> > 
> 
> > I'm on MacOS nix-darwin + nix home-manager setting. Emacs is installed through nix. It works for me.
> 
> 
> 
> @lentil32 did you install aerospace with nix? If so can you share your flake file? 

I installed AeroSpace with `brew`, but it's declaratively configured in `apps.nix`. Please refer to my repository:
https://github.com/lentil32/dotfiles-nix/blob/main/modules/apps.nix

**Comment by cristian-heredia** [comment]
> https://github.com/lentil32/dotfiles-nix/blob/main/modules/apps.nix
@lentil32 thank you!
