### ISSUE TITLE
[Feature Request] workspace next | prev

### ISSUE THREAD

**Issue by BayerSe** [nikitabobko/AeroSpace#29]
Thank you very much for AeroSpace! I've been testing it since tonight and I'm really enjoying it so far, I already prefer it over my yabai setup.

The only thing I'm missing from my i3 setup is the ability to move between adjacent workspaces with a single key which is possible in i3 using workspace next | prev, https://i3wm.org/docs/userguide.html#_changing_named_workspaces_moving_to_workspaces. Would be nice if that was available, then my setup would be complete.

**Comment by nikitabobko** [comment]
Released in 0.7.0

**Comment by BayerSe** [comment]
Many thanks!

**Comment by nikitabobko** [comment]
cc @mike1808 I think you will find this command useful for the "swap touchpad to switch workspaces" thing you wanted to do with BetterTouchTool

**Comment by mike1808** [comment]
@nikitabobko thanks! It works ok with one monitor but with multiple I need a way to change the workspace on a monitor where the mouse is. So being able to somehow do that will be awesome (ie, focus follows the mouse, get the display under the mouse, get the workspaces list under the mouse, etc).

**Comment by nikitabobko** [comment]
@mike1808 see https://nikitabobko.github.io/AeroSpace/goodness.html#use-trackpad-gestures-to-switch-workspaces (available since 0.8.0-Beta)

**Comment by mike1808** [comment]
> @mike1808 see https://nikitabobko.github.io/AeroSpace/goodness.html#use-trackpad-gestures-to-switch-workspaces (available since 0.8.0-Beta)

I appreciate the effort! It works perfectly now!

**Comment by mike1808** [comment]
Just to add one thing. After I upgraded from 0.7.0 to 0.8.1 the CLI now gets marked as malicious by CrowdStrike antivirus.
