### ISSUE TITLE
Question: how to split workspace into horizontal halves and efficiently manage vertical accordion layout in each?

### ISSUE THREAD

**Issue by jwintersinger** [nikitabobko/AeroSpace#294]
Hi! I'm a longtime `i3` and `sway` user, and I'm loving AeroSpace -- it's the only thing that has made macOS tolerable. In `sway`, my typical workflow is to have two containers placed side-by-side, then put each in `stacking` layout. As I open new windows, each is then placed on whichever horizontal half of the workspace has focus, where the new window becomes part of the container's stacking layout. How can I replicate this in AeroSpace?

Desired workflow:

1. Have empty root container with default layout of vertical accordion
2. Open first window, have it take up entirety of workspace
3. Open second window, have it appear as vertical accordion beneath first (which works), taking up almost entirety of workspace
4. Move the second window right, have the two windows shown side-by-side (which works). The second window has focus.
5. Open a third window, have it appear in vertical accordion on right half of workspace, below the second window. This doesn't work -- instead, the third window appears to the right of the second, and the screen is split horizontally into thirds.

Is this behaviour possible?

**Comment by nikitabobko** [comment]
I don't understand your question. The desired workflow is not possible in i3 either. In i3, when you have three windows side by side, you need to join two windows together to create a stacking container (or you have to call `split` command before opening the third question)

It all works exactly the same in AeroSpace. You either need to call `split` command before opening the third window, or your join two windows together with `join-with` command

If you want it to happen automatically, it's not possible in i3 AFAIK (don't know about sway). For AeroSpace, there is a proposal #260
