### ISSUE TITLE
list-windows --all behaves unlike --monitor all 

### ISSUE THREAD

**Issue by UddipakBhuyan** [nikitabobko/AeroSpace#297]
Using - 
```
aerospace CLI client version: 0.12.0-Beta 9cf82feb0c85bea77fedcdc6b8cdba75b5bbf1f8
AeroSpace.app server version: 0.12.0-Beta 9cf82feb0c85bea77fedcdc6b8cdba75b5bbf1f8
```
Below command behaves as expected:
```aerospace list-windows --monitor all --app-bundle-id org.mozilla.firefox```
However, 
```aerospace list-windows --all --app-bundle-id org.mozilla.firefox```
produces
```--all conflicts with "filtering" flags``` 
even when --all is suppose to alias --monitor all.

**Comment by nikitabobko** [comment]
It's by design

From the human perspective, `--all` reads weird together with "filtering" flags, because in the end not all windows will be printed, but the flag states otherwise

I agree that the error message could be improved to mention that the alias should be expanded
