### ISSUE TITLE
Set workspace as floating

### ISSUE THREAD

**Issue by caseycronyn** [nikitabobko/AeroSpace#298]
Hello Nikita this is an excellent tiling manager, thanks for the hard work.

I was wondering if it's possible to assign a workplace as floating for all windows? For instance setting workplace 0 so that none of the windows snap there.

All best,
Casey.

**Comment by davibe** [comment]
I thought the same. To map this request to existing concepts it could be that the configuration has a new callback like this

```
[on-window-change-workspace]
if.workspace_to = "x"
run = "layout float horizontal"
```
