### ISSUE TITLE
Feature request: support for left and right modifiers

### ISSUE THREAD

**Issue by zerogtiger** [nikitabobko/AeroSpace#313]
I'd like to request support for distinctions of left and right modifiers such that if a hyper key is mapped to, say, right shift + right command + right control + right option, there is still the possibility of hyper + left shift to execute a command.

**Comment by nikitabobko** [comment]
Please search for duplicates before reporting

**Comment by zerogtiger** [comment]
Not sure how your comment was helpful to the issue aside from pointing me to https://github.com/nikitabobko/AeroSpace/issues/31 (and not even that, since you never linked anything). 

Your comment in that post wasn't helpful at all either. 

For those who landed here, the verdict seems to be that it'll this feature will not be supported natively.
