### ISSUE TITLE
distinct wallpaper per workspace

### ISSUE THREAD

**Issue by marconetto** [nikitabobko/AeroSpace#314]
Hello,

I've been using yabai for a few years now and today I started to try out AeroSpace. Congrats for the work, it is amazing! I had a moment of joy when moved the focus to different workspaces without any delay and animation :) 

My question: I understand that by using Aerospace, the idea is that I will (probably) have a single space, and multiple workspaces. Is there a way to have a distinct wallpaper per workspace? Or all workspaces will need to have the same wallpaper?

The use case here is that I don't use menubar. My menubar is just date/clock. And for a few spaces I use different backgrounds so I know where I am.

**Comment by nikitabobko** [comment]
You can try to change wallpaper in exec-on-workspace-change callback. But I don't expect it to work responsive enough

**Comment by marconetto** [comment]
thanks for the suggestion @nikitabobko. I need that different wallpaper for just one workspace that I don't use very often. So the solution is ok (delay is not that bad for my use case).
