### ISSUE TITLE
Small windows in mission control

### ISSUE THREAD

**Issue by microBob** [nikitabobko/AeroSpace#315]
With certain window layouts and workspace configurations, the window preview in mission control become super tiny like this:
![small](https://github.com/nikitabobko/AeroSpace/assets/16888236/f9b2b4ce-d514-4bab-a543-48e6e90e8777)

The expected view should have been like this:
![big](https://github.com/nikitabobko/AeroSpace/assets/16888236/de0db4b1-f3f2-4daa-af13-e9946cbe3128)

To reproduce:
1. Have one window be in it's own workspace
2. Have two or more windows be in another workspace (possibly in a split layout of some sort)
3. When entering mission control from the workspace with 2+ windows, you get the tiny windows shown above. When entering mission control from the workspace with 1 window it looks normal (expected behavior).

I like to use mission control to see an overview of my apps and switch to them sometimes (in addition to using the workspace shortcuts). Would appreciate it if this could be fixed!

**Comment by nikitabobko** [comment]
https://nikitabobko.github.io/AeroSpace/guide#a-note-on-mission-control

**Comment by microBob** [comment]
lol thanks 🤦
