### ISSUE TITLE
alt-shift-NUMBER stopped working

### ISSUE THREAD

**Issue by lampewebdev** [nikitabobko/AeroSpace#318]
hej,

first of all thank you for this amazing piece of software! 

I don't know when and why suddenly moving windows with alt-shift-NUMBER stopped working. alt-shift-A or alts-shift-J and so on works great. Moving with alt-1 to a workspace also works.

- I'm using the default config.
- I have uninstalled and installed aerospace.
- I have quit all apps i can think of that can take over these shortcuts

Is there a way how I can debug that? 

- AeroSpace version:  v0.12.0-Beta 9cf82feb0c85bea77fedcdc6b8cdba75b5bbf1f8
- MacBook Pro M3
- MacOS version: 14.5 (23F79)

**Comment by jiwidi** [comment]
Having the same issue!

**Comment by nic0dk** [comment]
have you solved this?

**Comment by nic0dk** [comment]
if i remap my shift to ctrl, it works - not sure why shift isnt working with numbers

**Comment by exsesx** [comment]
> if i remap my shift to ctrl, it works - not sure why shift isnt working with numbers
> 
> edit: figured out that i had skhd running.. after disabled it everything works fine :)
> 
> `skhd --stop-service`

Thank. You. 🙏🏼

**Comment by x61** [comment]
Is the solution here to not use skhd along with aerospace? Is it possible to use both simultaneously?

**Comment by exsesx** [comment]
> Is the solution here to not use skhd along with aerospace? Is it possible to use both simultaneously? 

It depends on the configuration, I guess? However, I believe the issue is not related to aerospace.

**Comment by msvechla** [comment]
I have the same issue, and I'm not running skhd. If I am in a text box and pressing e.g. `alt-shift-2` it prints a `€` sign, but workspace switching is not happening
