### ISSUE TITLE
Debug mode to listen/test keybinds

### ISSUE THREAD

**Issue by jiwidi** [nikitabobko/AeroSpace#319]
Hi!

First time user here, I just installed aerospace, copied the basic confic as in docs and reloaded it and some of the bindings are not working for me.

None of the move node to workspace or change focus work for me. They do work when i run the command in the terminal so its about detecting the keybind. Is there any debug mode that could "listen" to keybinds and just print in the terminal what is recognized from aerospace? This way i can more easily debug what's going on.

Also, is there any posible numerical indicator to what workspace are you on right now? Would be nice to have an icon on the topbar with it, didnt find anything on docs.

Ty

**Comment by nikitabobko** [comment]
Please check that there is no other software running that may intercept this shortcut (e.g. skhd, karabiner)

> Is there any debug mode that could "listen" to keybinds and just print in the terminal what is recognized from aerospace? This way i can more easily debug what's going on.

```toml
alt-1 = 'exec-and-forget touch > ~/triggered'
```

> Also, is there any posible numerical indicator to what workspace are you on right now? Would be nice to have an icon on the topbar with it, didnt find anything on docs.

Please read the docs. It's mentioned in https://nikitabobko.github.io/AeroSpace/guide#emulation-of-virtual-workspaces

> AeroSpace shows the name of currently active workspace in its tray icon (top right corner), to give users a visual feedback on what workspace is currently active.

**Comment by alper** [comment]
Hey, half my key binds are not doing anything. It would really be good to have a log output somewhere?
