### ISSUE TITLE
Run back-and-forth when selecting current workspace

### ISSUE THREAD

**Issue by JonasVautherin** [nikitabobko/AeroSpace#322]
I know https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth exists, which allows me to have a shortcut to go back and forth between workspaces (that's what I had in AwesomeWM with "meta + escape").

In i3wm, if I remember correctly, it was slightly different: there was no "back-and-forth" shortcut, but trying to go to the current workspace would actually go to the previous one. E.g. I would be on workspace 2, do "meta + 5" and move to workspace 5. Hitting "meta + 5" again would bring me back to the last one (workspace 2), and so forth, resulting in the "back and forth" behaviour.

In Sway, I actually have both 😊.

Is there a way in Aerospace to get the second behaviour? I haven't found it.

**Comment by nikitabobko** [comment]
`workspace --auto-back-and-forth`

**Comment by JonasVautherin** [comment]
I don't really get how to use it. I don't want to call `$aerospace workspace --auto-back-and-forth 2` from the command line, I would like it to happen when I do "alt + 2" 🤔.

Can I somehow enable `workspace --auto-back-and-forth` in the config file?

**Comment by JonasVautherin** [comment]
Oh, just got it, with something like:

```
alt-1 = 'workspace --auto-back-and-forth 1'
alt-2 = 'workspace --auto-back-and-forth 2'
alt-3 = 'workspace --auto-back-and-forth 3'
alt-4 = 'workspace --auto-back-and-forth 4'
alt-5 = 'workspace --auto-back-and-forth 5'
alt-6 = 'workspace --auto-back-and-forth 6'
alt-7 = 'workspace --auto-back-and-forth 7'
alt-8 = 'workspace --auto-back-and-forth 8'
alt-9 = 'workspace --auto-back-and-forth 9'
alt-0 = 'workspace --auto-back-and-forth 10'
```

Thanks a lot!
