### ISSUE TITLE
move and follow the window

### ISSUE THREAD

**Issue by smoh** [nikitabobko/AeroSpace#324]
Hi there,

Is there any configuration that allows me to move the focused window to workspace X and follow that window (switch to that workspace)?

From docs, it seems not but I wanted to check. Thanks!

**Comment by nikitabobko** [comment]
```
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
```

**Comment by ipstone** [comment]
I tried to use the --focus-follows-window option in my aerospace setup, but my aerospace (0.14.2-Beta) complains that this is an uknown option. Guess this combined commands is the current solution for now - 

```
move-node-to-workspace [-h|--help] [--focus-follows-window] [--wrap-around]
                       (next|prev)
move-node-to-workspace [-h|--help] [--focus-follows-window] [--fail-if-noop]
                       [--window-id <window-id>] <workspace-name>
```
