### ISSUE TITLE
Spotlight switches workspace 

### ISSUE THREAD

**Issue by carlduevel** [nikitabobko/AeroSpace#328]
This is not a bug description but rather a usability issue I hope there is a solution for:

I'd like to organize workspaces around contexts: So, for example one per task I am currently working on. 
Often this involves creating a new window of e. g. Chrome in a workspace where there has not been one before. But if I then tell Spotlight to open Chrome the workspace gets switched to the one I last used Chrome in. Is there any possibility of opening the new Chrome window in the current workspace? 

Thanks for this great piece of software btw!

**Comment by nikitabobko** [comment]
People achieve this using AppleScript https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript

I don't think it's possible to make spotlight work the way you want to. But Raycast/Alfred might be capable of doing it

**Comment by carlduevel** [comment]
Thanks! I missed that in the manual.
