### ISSUE TITLE
Feature Request: change menu bar opacity

### ISSUE THREAD

**Issue by mil-ad** [nikitabobko/AeroSpace#330]
Are there plans/Does it make sense to add support for changing menubar opacity to AeroSpace? yabai has recenly [added it](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc) and it's useful

**Comment by nikitabobko** [comment]
AeroSpace is focused on practical features. The project only care about workflows. "look and feel" is out of scope of the project. Please see the values in the readme.

I want to neither implement nor support appearance features
