### ISSUE TITLE
Long setup jitter when plugging in multiple monitors together

### ISSUE THREAD

**Issue by Solomonz** [nikitabobko/AeroSpace#333]
Context:

❯ aerospace -v
aerospace CLI client version: 0.11.1-Beta a8fe49f8103c7840f2e2b5497bade7f63535c139
AeroSpace.app server version: 0.11.1-Beta a8fe49f8103c7840f2e2b5497bade7f63535c139

[.aerospace.toml](https://github.com/user-attachments/files/16273167/aerospace.toml.txt)

I have two monitors (both are Samsung LF32TU874VNXGO Thunderbolt T3/USB-C 3850x2160), A and B. My desk setup is I have A in a vertical orientation on the left (code monitor), connected via thunderbolt 4 daisychain to B in a horizontal orientation in the middle (main monitor), connected via thunderbolt 4 to my laptop on the right (messaging, spotify, etc). This means that when I sit down at my desk, I can just plug my laptop in to the single thunderbolt cable, and get charging, both monitors, ethernet (plugged into B), and my USB A keyboard (also plugged into B).

Repro:

Video: https://github.com/user-attachments/assets/2b9643af-ccf2-4ef0-9819-b2c5e7d02a6f

As you can see, B is detected first, and there's no issue there. However, A is quickly detected afterwards, and when Aerospace tries to redistribute windows at that point, it gets into this frustrating loop that takes a while to get past. In this example, it took around 16 seconds from detecting the third monitor to finishing the setup jitter, but other times it has taken even longer, sometimes even taking a full 45-60 seconds before settling down. I did find that unplugging A from B, plugging B into my laptop, waiting a few seconds, and then plugging A into B does significantly reduce the jitter time, but that isn't a great solution.

At first I thought this was related to #289, but I see that that seems to have been isolated to a change after 0.11.2, whereas I am having this issue on 0.11.1.

Let me know if there's any more info I can provide, and thank you for this (otherwise) amazing tool!

**Comment by nikitabobko** [comment]
Wow, that's crazy. I use only a single external monitor and I regularly plug and unplug it, I have never seen a problem like this

1. Is the problem reproducible only with a single external monitor?
2. Is the problem reproducible if you disable "Displays have separate spaces"?
3. Is the problem reproducible if you drop `workspace-to-monitor-force-assignment` from the config?

**Comment by Solomonz** [comment]
1. No, I only see this with the two monitors together. When I unplug A from B, plug in B (alone), wait a few seconds, and then plug A into B, the result is much milder, only lasting a couple of seconds, but does still happen.
2. I will check in a second and update this answer, I have to log out to change that setting. I'll check it and then update this comment with the result in a few minutes.
3. Yes, I don't see any change after commenting out that section of my config.

**Comment by nikitabobko** [comment]
> Yes, I don't see any change after commenting out that section of my config.

But windows don't need to travel to other monitors, why would they jitter. Do windows jitter on the laptop monitor? Did you reload the config?

**Comment by Solomonz** [comment]
2. Ah, this does seem to dramatically improve the issue. I also see that the rest of Aerospace seems much snappier with this change (I have been seeing mild performance issues). Interesting!

What exactly does this setting control? What do I lose by using this to mitigate this issue?

**Comment by Solomonz** [comment]
> But windows don't need to travel to other monitors, why would they jitter. Do windows jitter on the laptop monitor? Did you reload the config?

Yep, I made sure to reload the config. Some of the workspaces seemed to go to the other monitors instead and jitter there. I have B set as my main monitor -- maybe workspaces default to the primary monitor?

**Comment by nikitabobko** [comment]
> What exactly does this setting control? What do I lose by using this to mitigate this issue?

To my knowledge, the only drawback of disabling it is that your two other monitors will become unusable black screens once you enter a fullscreen on the third. https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces

IMO, everything else just becomes better if you disable it. I observe people having weird issues if "Displays have separate spaces" is enabled https://github.com/nikitabobko/AeroSpace/issues/247#issuecomment-2144000604 https://github.com/nikitabobko/AeroSpace/issues/101

I had only one issue if you disable this setting https://github.com/nikitabobko/AeroSpace/issues/143 luckily it's already fixed

> maybe workspaces default to the primary monitor?

Got it. Yes, without the `workspace-to-monitor-force-assignment` all the workspaces will try to stick with the "main" monitor

> I have been seeing mild performance issues

You might be running into this problem https://github.com/nikitabobko/AeroSpace/issues/149 (especially with 3 monitors)

**Comment by Solomonz** [comment]
Wow, thank you for all of this! I guess I'll just keep the setting off in that case. I have no need for fullscreen applications, especially when using all 3 monitors at once.

> You might also be running into this problem #149 (especially with 3 monitors)

Maybe, but it seems like the symptom was different. I wasn't seeing windows flash resizing, I was just seeing a slight delay between inputting the command for focusing the next window and the next window actually being focused. But after turning off displays have separate spaces, I no longer notice a delay. Aerospace is snappier across the board, and I don't have the weird setup jitter anymore! :)

**Comment by jack4git** [comment]
#594 is a showstopper for disabling "Displays have separate spaces"
