### ISSUE TITLE
How to trigger the `join` command by dragging the mouse

### ISSUE THREAD

**Issue by Mdbg** [nikitabobko/AeroSpace#337]
This my current layout 
![1](https://github.com/user-attachments/assets/0a1cfca7-55ae-4e74-b72d-7db166e8370e)

i want to move  window 3 to the new postion by dragging  , how to do that
<img width="3198" alt="image" src="https://github.com/user-attachments/assets/57a5e2d2-fcea-4d23-8ac0-574a00937949">

**Comment by dagrlx** [comment]
I do this by selecting window 2 and then use the key combination:

 alt-shift-right = ['join-with-right', 'mode main']

[Guide Join.with](https://nikitabobko.github.io/AeroSpace/commands#join-with)

I still find it hard to understand the use of aerospace and i3 in terms of window management.

**Comment by nikitabobko** [comment]
@Mdbg It's not possible to "join" two windows using mouse. I know that other tiling window managers allow it, but I don't have plans to support it in AeroSpace.

I like the simplicity of the way dragging/resizing with mouse currently works in AeroSpace. AeroSpace is keyboard centric, and people are supposed to use keyboard to "join" windows. The only reason why I implemented moving/resizing with mouse is to make onboarding of new users easier.

**Comment by dudeofawesome** [comment]
As a new user watching the [YouTube 91 sec Demo](https://www.youtube.com/watch?v=UOl7ErqWbrk), I was definitely under the impression that joining leafs was possible via mouse (at [0:18](https://youtu.be/UOl7ErqWbrk?t=18)). 

I really like AeroSpace so far, but I do feel that joining leafs via mouse would increase the usability significantly.
