### ISSUE TITLE
Aerospace sees a new finder tab as a new window

### ISSUE THREAD

**Issue by 27medkamal** [nikitabobko/AeroSpace#345]
# Issue

1. Open a finder window. It joins the layout just fine.
1. Open a new tab in the same finder window. Aerospace thinks it's a new window and adds it to the layout, but because it's not a window, there's empty space in its place, and when you navigate between windows using `focus` `left` and `right` it switches between those 2 tabs and moves the window between the 2 available slots in the layout.

**Comment by pszypowicz** [comment]
https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript

**Comment by pszypowicz** [comment]
Ah it looks like its a duplicate for #68

**Comment by 27medkamal** [comment]
It is a duplicate. Closing
