### ISSUE TITLE
automatic extra workspace?

### ISSUE THREAD

**Issue by fschlegelone** [nikitabobko/AeroSpace#348]
Hi together, 
I just ran `aerospace list-workspaces --all` and noticed that aerospace is creating one extra workspace on top of the one's you configure. Why is that? Is there a way to get rid of this? 
Usually I wouldn't care, but I display the workspaces in my sketchybar, so it really is a problem for me.

**Comment by xuyixin1996** [comment]
I have the same symptom(I'd like to say it is a symptom instead of issue because it is kinda expected to me) when using one external monitor together with built in monitor, and I'm using sketchybar too. 

Do you have 2 monitors?

**Comment by nikitabobko** [comment]
I presume you have more than 1 monitor. It works as @xuyixin1996 described it, and it was programmed this way on purpose. See #222 

You can configure `workspace-to-monitor-force-assignment` for your external monitor, to avoid the creation of the "phantom" workspaces.

If you have any arguments why the current AeroSpace behavior is incorrect please elaborate. But please read the thread in #222 first
