### ISSUE TITLE
Aerospace stops recognizing new windows after some time

### ISSUE THREAD

**Issue by acutebar** [nikitabobko/AeroSpace#353]
Hi,

An issue I've been facing over the last week or so. After sometime of using it, Aerospace stops working newly opened windows and does not recognize them, but it continues to work for already opened windows. Running `aerospace list-windows --all` does not list the new windows. It used to work flawlessly before this. 

I'm using AeroSpace-v0.13.4-Beta and macOS Sonoma Version 14.5. 

Thanks!

**Comment by nikitabobko** [comment]
Please restart AeroSpace.app after updates. See #352

**Comment by acutebar** [comment]
Thank you so much - this was indeed the issue.
