### ISSUE TITLE
Create the icon. Help wanted!

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#37]
Right now, AeroSpace doesn't have an icon, but it would be cool to design one.

I would appreciate it if someone skilled from the community could contribute to the project by creating the icon. I can draw a basic icon on my own, but it would likely resemble a simplistic drawing made by a 5-years-old using GIMP.

For inspiration: 
1. The "Aero**Space**" name means a **space** for your windows without friction (the "aero" part). 
2. I myself consider the virtual emulation of workspaces to be the strongest feature of the AeroSpace. If I could disable the workspace switching animation in yabai or Amethyst (with SIP enabled, of course), I'd probably not bother myself creating AeroSpace. That's what the "space" part in the app name means. It resembles the strongest feature of AeroSpace - work**spaces**

In my opinion, an absolute must for the icon is that it must be related to windows / window managers. Everything else is optional (it's not even necessary to be related to "AeroSpace" name in any way)

If you submit your icon, firstly thank you for your work! **But** please be prepared that I might reject it without any comments. Beautiful icon is a highly subjective topic, I have nothing but my subjective taste to use

**Comment by mike1808** [comment]
Are you looking for an icon that will be displayed in the tray or the one used in Applications menu?

**Comment by nikitabobko** [comment]
Mainly for the application menu

It makes sense to also create an icon for the tray when the app is "disabled" (right now, AeroSpace shows the ⏸️ emoji). Probably the icon should be grayed out in that case.

When the app is "enabled", the tray shows the workspace status and I have no plans to change that

**Comment by mike1808** [comment]
<img width="489" alt="image" src="https://github.com/nikitabobko/AeroSpace/assets/3942554/56a02bd8-26e5-4ef2-8ac0-cc2adb837bb3">

**Comment by nikitabobko** [comment]
Well, it reflects nothing :) It looks more like a satellite rather than the window manager 

The best icon I saw so far was the Lasso App https://thelasso.app/ But the author clearly designed the app name and icons together

yabai and Amethyst icons are also meh, in my opinion

**Comment by nikitabobko** [comment]
@ctruett it would help if you could give examples of modern vs traditional icons, simple vs complex icons

Googling "modern vs traditional icon" and "simple vs complex icons" doesn't help

But generally, I think I don't care

In my opinion, an absolute must for the icon is that it must be related to windows / window managers. Everything else is optional (it's not even necessary to be related to "AeroSpace" name in any way)

**Comment by DonaldoSoWell** [comment]
Hi !
Here is another set of AI generated ones to add some design ideas
![Unknown-2](https://github.com/nikitabobko/AeroSpace/assets/60661694/5afe802f-7458-46ad-97b2-22910a5597ee)
![Unknown-3](https://github.com/nikitabobko/AeroSpace/assets/60661694/b7d1b133-389d-4156-bb54-70a0337af0c4)
![Unknown-4](https://github.com/nikitabobko/AeroSpace/assets/60661694/79f75211-b655-4003-a986-c25f62244ecf)
![Unknown-5](https://github.com/nikitabobko/AeroSpace/assets/60661694/5965c73a-af9a-4444-b786-0d3d93d83c4d)
![Unknown-6](https://github.com/nikitabobko/AeroSpace/assets/60661694/1e889038-af58-4d65-965d-5faad56ee737)
![Unknown](https://github.com/nikitabobko/AeroSpace/assets/60661694/9844a917-65e9-4a71-841c-b5a366ef5355)
