### ISSUE TITLE
Implement `fullscreen --no-outer-gaps`

### ISSUE THREAD

**Issue by jomag** [nikitabobko/AeroSpace#373]
When in (non-native) fullscreen mode, I typically want to disable gaps to maximize screen usage. It would be nice if gaps could be customized for fullscreen, just like they can with monitor patterns.

Related, it would also be nice to optionally treat workspaces with a single window as fullscreen, removing gaps.

**Comment by nikitabobko** [comment]
But why?

If users use gaps for practical purposes to distinguish between windows then they can only use the inner gaps and set outer gaps to zero

If users use gaps for aesthetic purposes then users will use both outer and inner gaps

Related: #54

**Comment by jomag** [comment]
Good point. My reason for wanting this functionality is somewhere in between: I want gaps for separation of windows. However, having only inner gaps does not look great IMO.

So for fullscreen or single-window workspaces, I don't want gaps as they add no practical value. In all other cases, I want gaps between windows for practical reasons, and around them for aesthetics.

**Comment by nikitabobko** [comment]
I don't mind if somebody adds a `fullscreen --no-outer-gaps` flag

It's a minor priority for me, and it's a good-first-issue so PRs are welcome

**Comment by nikitabobko** [comment]
> Related, it would also be nice to optionally treat workspaces with a single window as fullscreen, removing gaps.

It will be fixed semi-automatically with #278 Please see https://github.com/nikitabobko/AeroSpace/issues/60#issuecomment-2170067042

**Comment by nikitabobko** [comment]
Alternative name: `fullscreen --ignore-gaps`

**Comment by vrumger** [comment]
fixed in #472 🎉

**Comment by nikitabobko** [comment]
Released in 0.15.0-Beta
