### ISSUE TITLE
Custom settings per workspace

### ISSUE THREAD

**Issue by jomag** [nikitabobko/AeroSpace#374]
I've searched but not been able to find any way to add default settings per workspace. For example, I have a few workspaces that have specific purposes: browser workspace, terminal workspace, chat workspace, and I would want them to have different layouts depending on their purpose.

**Comment by nikitabobko** [comment]
```
after-startup-command = [
    'workspace 1', 'layout tiles', 'workspace-back-and-forth'
    'workspace 2', 'layout accordion', 'workspace-back-and-forth'
]
```

**Comment by nikitabobko** [comment]
Once #186 is implemented it will be even simplier:
```
after-startup-command = [
    'layout --workspace 1 tiles',
    'layout --workspace 2 accordion'
]
```

**Comment by thewinger** [comment]
Would it be possible to specify a deeper tree? so workspace 1 could be:

```
V_tiles
|- Window 1 (browser)
|- V_accordion
    |- window 2
    |- window 3
    |- window 4
    ...
```

**Comment by theherk** [comment]
@nikitabobko: Is it possible to set `accordion-padding` per workspace somehow? I can't see setting it aside from the general attribute, but it would be nice. Reason being Zed editor opens several windows but has its own project switching. So I put them all on the same workspace, but don't need the accordion padding.

I didn't want to open another issue as this doesn't really seem like a bug and is closely related to this question.
