### ISSUE TITLE
Allow list of app ID's

### ISSUE THREAD

**Issue by jomag** [nikitabobko/AeroSpace#375]
I've setup `on-window-detected` to automatically move my browser to a specific workspace. However, I have multiple browsers (Firefox, Chrome, etc) and would like all to be moved to the same workspace.

It would be great if `if.app-id` accepted a list of app ID's instead of having multiple `on-window-detected` sections.

**Comment by nikitabobko** [comment]
Since 0.21.0-Beta, it's possible to write this:

```toml
on-window-detected = [
    {
        if = '''
        test %{app-bundle-id} = org.mozilla.firefoxdeveloperedition \
            || test %{app-bundle-id} = org.mozilla.firefox \
            || test %{app-bundle-id} = org.mozilla.com.zen.browser \
            || test %{app-bundle-id} = org.chromium.Chromium \
            || test %{app-bundle-id} = com.microsoft.edgemac
        ''',
        run = 'move-node-to-workspace 3',
    }
]
```

See the updated docs: https://nikitabobko.github.io/AeroSpace/guide#shell + https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
