### ISSUE TITLE
Sharing a window in multiple workspaces

### ISSUE THREAD

**Issue by LandonSchropp** [nikitabobko/AeroSpace#378]
I'm thinking about my workspaces as "contexts" where I perform different tasks. Often, many of my contexts, such as "coding" or "messaging" will involve the use of a browser window.

I was thinking, it'd be cool if I could share the _same_ browser window between multiple workspaces. This would allow me to switch back and forth between contexts, but not lose any in-progress information inside my browser.

Is something like this possible with AeroSpace?

**Comment by nikitabobko** [comment]
No, it's not possible, and I don't believe it will ever be possible. Monitors contain workspaces, workspaces contain windows. The whole structure forms a tree. It's a strong invariant that a lot of logic is built on top of. And it would be extremely hard to change this logic, and it would be a breaking change of some of the existing functionality. It may be easier to build a new window manager with this functionality than changing AeroSpace.

Consider the following feature interactions:
- `aerospace list-windows --format %{workspace}` will break
- What if the window belongs to workspace that are simultaneously visible on the both of the monitors? It's not possible to render window twice at the same time
- The "duplicated window" may have different sizes on different workspaces. Switching between the workspaces will lead to the window jiggering.
- What workspace should get activated if the user switches to the window via cmd-tab?
- `move-node-to-workspace` will either have to change its semantics or it will become semantically broken
- etc...

By allowing windows to belong to several workspaces, the structure stops being a tree and becomes a graph. And graphs are noticably more complicated to deal with than trees (both from the implementation perspective and users perspective)

I also speak from my experience, I once was a AwesomeWM user on Linux. AwesomeWM allows windows to belong to several workspaces, and I don't remember it being useful 

Your best bet is "sticky windows". Sticky windows belong not to the workspaces but directly to the monitors #2 

Sorry, but I am closing the issue. This "limitation" is something that we have to accept.

**Comment by LandonSchropp** [comment]
Understood. It sounds like sticky windows might be more what I was looking for anyway.

Thank you!
