### ISSUE TITLE
Control corner for hiding windows

### ISSUE THREAD

**Issue by clarkadamp** [nikitabobko/AeroSpace#382]
> Since AeroSpace needs a free space to hide windows in, please make sure to arrange monitors in a way where every monitor has free space in the bottom right or left corner.

It would be good to have the ability to customize corners which are assigned to hiding.  My natural monitor configuration is to have a the center monitor high, then others placed below the main on each side, this allows my to use the mouse and move naturally between screens.

I have re-arranged my monitors so that hidden windows don't impact the other screens, now my habbits about moving the mouse means they run into walls rather than moving to the monitor.

Something like:
```
[corners]
main = ['top-right', 'top-left']
secondary = 'bottom-left'
'^built-in retina display$' = ['top-left', 'bottom-right'] 
```

**Comment by nikitabobko** [comment]
> My natural monitor configuration is to have a the center monitor high, then others placed below the main on each side

Even if AeroSpace provided this configuration, there would be no corner for your middle monitor to hide windows in.

**Comment by clarkadamp** [comment]
With this arrangement  would the top corners be available?
![Monitor Arrangement](https://github.com/user-attachments/assets/d86f96b8-84dd-4882-a7b9-9d7ff174c6ae)

**Comment by nikitabobko** [comment]
It's not possible to move windows "above the monitor". It's only possible to move them below the monitor. It's a macOS restriction

> Is more than one corner needed, or can they all be stacked into one?

Every monitor should have at least one free bottom corner. Hiding windows in monitors they don't belong to leads to performance problems (#149) and macOS bugs (#289)

**Comment by clarkadamp** [comment]
> It's only possible to move them below the monitor

Ahh, so it wasn't a design choice for below only.  

All good, thanks for your quick response, I'll work on my arrangements to see if I can come up with a compromise.

**Comment by clarkadamp** [comment]
Happy to close this, thanks for the quick response

**Comment by ELLIOTTCABLE** [comment]
I'd ask that this be re-opened; I just spent some time writing up #666, which is pretty close to a duplicate of this.

Further arguments I didn't include there:

- some of the performance concerns can be avoided in many users' scenarios; i.e. if the use selects a hiding-monitor that is the same DPI and/or size as their main monitor, or if the user doesn't move screens to/from the 'odd-one-out' display with a weird DPI very often
- something like #623 may be the _only_ solution for some setups that isn't entirely untenable (i.e. creating virtual displays to match different sizes/DPIs of monitor, to counter the above flickering/resizing issues), and that's only possible with custom configuration

I'm willing to try and implement the patch, if it's likely to be accepted. I understand the argument against configuration bloat; I'm all there with you for the most part - big fan of opinionated tools. However, in this specific case, the blessed behaviour actually _entirely prevents_ a class of users from accessing the tool, which is exactly where an option is the correct choice. (=
