### ISSUE TITLE
Disable window dropshadow

### ISSUE THREAD

**Issue by th4lmain** [nikitabobko/AeroSpace#383]
Is there a way to disable the default MacOS dropshadow? I know it can be disabled in Yabai, but that was through disabling SIP. Should I just follow how Yabai does it, or is there an existing AeroSpace-y solution that preferably doesn't require disabling SIP?

Sorry if this question has already been asked, I couldn't find other mentions of this.

**Comment by soyoh** [comment]
https://github.com/nikitabobko/AeroSpace/issues/11#issuecomment-1805513357

> The ability to change the appearance of windows (shadows, borders, titles) requires using private APIs. Using private APIs to implement features that are not practical goes against [the values](https://github.com/nikitabobko/AeroSpace#values-of-the-project) of the project. If someone will find a way to implement these features without using private APIs and will bring a PR, I'd be happy to consider it. But I myself certainly won't work on implementing these features.
