### ISSUE TITLE
Broken for non-us keyboard users by default

### ISSUE THREAD

**Issue by ricardomatias** [nikitabobko/AeroSpace#385]
> I've removed every alt entry from the config and still I cannot use my keyboard properly, because the `alt` keybindings somehow are still being configured to switch workspaces and such. 
> 
> This should be removed from the default config since most of the world uses non-us keyboard and we need the alt key to write special characters.

Apparently I had 2 .aerospace.toml config files created on install, since I saw one under .config I assumed that was it. I suggest only creating one on install so that situations like this can be avoided.

**Comment by nikitabobko** [comment]
AeroSpace doesn't create config files automatically
