### ISSUE TITLE
join-with causes the screen to flicker

### ISSUE THREAD

**Issue by jacqueminv** [nikitabobko/AeroSpace#388]
Hi,

I love AeroSpace, thanks for developing and maintaining this <3

I try to join 2 windows in a vertical layout and I think it basically works but unfortunately the result is unusable as the screen is flickering completely.

To reproduce:
1. I open 2 windows: 1 finder, 1 iterm
2. In iterm I type: `aerospace join-with left`
3. the 2 windows are displayed now vertically but the screen is flickering I have to quit iterm to stop that or do `aerospace move right`

Any hint on how to fix that?

aerospace version: 
`➜  ~ aerospace -v
aerospace CLI client version: 0.12.0-Beta 9cf82feb0c85bea77fedcdc6b8cdba75b5bbf1f8
AeroSpace.app server version: 0.12.0-Beta 9cf82feb0c85bea77fedcdc6b8cdba75b5bbf1f8`

**Comment by nikitabobko** [comment]
1. Sorry, I can't reproduce. Works on my machine
2. Please try to update to the latest 0.14.1 version. It fixed some of the flickering issues in multi monitor setup
3. Is the issue reproducible if you disable `Displays have separate spaces`? https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces

**Comment by jacqueminv** [comment]
`brew upgrade` indeed fix the issue, sorry to have bothered you without trying that first. 

I’ll read the doc about setting you mention now.
