### ISSUE TITLE
Newbie questions about gaps and resizing

### ISSUE THREAD

**Issue by willian** [nikitabobko/AeroSpace#392]
First of all, thanks for all the work on the app.
I've been using yabai + skhd for the past couple of years, but I always struggle with yabai limitations and wierdness when controlling windows, which sometimes was breaking my workflow.

I tried to find two things that I would like to add to my configuration, but I could not:

1. How to toggle on/off the gaps?
For example, if I press `Alt + G` and the gaps are set to 10, it toggles them off (set gaps to `0`), and if I press `Alt + G` again, it sets them back to `10`.
2. How to set a window size to a third of the screen/monitor size? Is it possible?

Thanks in advance for all the help!

**Comment by nikitabobko** [comment]
1. It's not possible to toggle on/off gaps. The tracking issue is #355 
2. Not possible yet. The tracking issue is #397

**Comment by willian** [comment]
Thanks for answering, @nikitabobko
