### ISSUE TITLE
Bottom right corner creeping a shadow

### ISSUE THREAD

**Issue by samholmes** [nikitabobko/AeroSpace#393]
<img width="725" alt="Screenshot 2024-08-12 at 1 22 00 PM" src="https://github.com/user-attachments/assets/77877833-e680-4ff9-a1e2-8bc27ed49873">

Because all the windows are moved out of the visible monitor boundary at the bottom right and left corners, we'll see a shadow start to appear when there are lot of windows stacked in the bottom right corner.

To fix this, I'd assume adding some extra x and y offset padding to the positioning outside of the monitor viewport.

**Comment by nikitabobko** [comment]
> adding some extra x and y offset padding to the positioning outside of the monitor viewport

It's not possible to move windows completely outside of the monitor viewport. It's a macOS restriction

Related: #66 

Workarounds:
1. Use dark wallpaper
2. Turn on Dock auto hiding
