### ISSUE TITLE
Aerospace Guide Video On Youtube

### ISSUE THREAD

**Issue by josean-dev** [nikitabobko/AeroSpace#394]
Hello!

I really love your project! Recently, I put together a complete guide on Youtube going into how it works and how to get started with it. Wanted to let you guys know. You can find the video [here](https://youtu.be/-FoWClVHG5g). Not sure if you'd like to add it to the project's README, but you are welcome to do so if you like.

All the best!

**Comment by nikitabobko** [comment]
Hi!

Great video! Thank you for increasing the AeroSpace popularity and a great video guide!

The README will definitely benefit from a link to your video d8fffe2a9dfd57131949cb9392b373a0ff827dc2, thanks for the suggestion

Please let me know if you want to change anything about the way your link is presented in the README

Cheers!

**Comment by josean-dev** [comment]
Awesome! Link looks great to me! Happy to hear you liked the video! Thanks for the awesome project you've put together with Aerospace 🙏🏽
