### ISSUE TITLE
Disable tiling for specific user-defined apps

### ISSUE THREAD

**Issue by Shock9616** [nikitabobko/AeroSpace#398]
Hey there, just trying out AeroSpace for the first time today and I'm really liking it so far!

Just a quick thought I had: I thought it may be helpful to be able to define a list of `app-id`s to be ignored. I have I have a few apps that I don't want to be tiled and I haven't been able to find a way to do that so far. Is this already possible? If not would you consider adding it in the future?

Thanks for your great work! I'm looking forward to using this project more!

**Comment by Shock9616** [comment]
Never mind, I just found how to accomplish this. Sorry about that

**Comment by ProHaller** [comment]
Could you share how to disable specific app-id from being handled by Aerospace?

**Comment by Shock9616** [comment]
Use this code block for each app you want to float by default:
```toml
[[on-window-detected]]
if.app-id = "com.exampleco.ExampleApp"
    run = "layout floating"
```
you can find the `app-id` by running
```
$ aerospace list-apps
```
while the desired app is open
