### ISSUE TITLE
Detect other running window managers

### ISSUE THREAD

**Issue by eugeneotto** [nikitabobko/AeroSpace#40]
When I first started Aerospace, I was already running Yabai (having found both in the same HN thread), and the two started competing, which resulted in some windows flickering as they were continuously resized/repositioned.

Not sure the best solution, but it seems like a probably-common scenario for people experimenting with new window management software. Two ideas:

1. Some sort of debouncing algorithm.
2. Detect other window managers and alert the user.

**Comment by nikitabobko** [comment]
I don't think that this problem is widespread enough to address it in AeroSpace
