### ISSUE TITLE
Option to disable built-in spaces

### ISSUE THREAD

**Issue by Shutruk** [nikitabobko/AeroSpace#408]
Hi, first of all, thanks for the amazing work on this project.

I was wondering if it's possible to disable some aerospace's workspaces to disable the numbered ones, commenting/deleting the commands won't make them dissapear.
This is specially useful for spanish layouts (es-es) where alt+numbers are used for "@" "#" etc... and the default behaviour is opening aerospace on space 1.

Maybe there's an easier alternative of doing this? 
Thanks.

**Comment by tobiasgiese** [comment]
If you remove the `alt-1` etc. commands this will work. Reloading the config should be sufficient, you can also restart aerospace.
