### ISSUE TITLE
Problem With Callback 'exec-on-workspace-change'

### ISSUE THREAD

**Issue by s4Dt0y** [nikitabobko/AeroSpace#414]
I am on aerospace `AeroSpace v0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd`.

I copy and pasted the following sketchybar event trigger script from the [Aerospace Goodness](https://nikitabobko.github.io/AeroSpace/goodness#show-aerospace-workspaces-in-sketchybar) web page:
```
# Notify Sketchybar about workspace change
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]
```

When I switch workspaces, my label is not updated. Note that running the command directly (e.g. `sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=10`) works.

**Comment by s4Dt0y** [comment]
Upon further debugging, it seems as though the event is not even being triggered.

Can anyone help?

**Comment by agenttank** [comment]
mine looks like this
taken from there: https://github.com/forteleaf/sketkchybar-with-aerospace

the only real difference that i spot, is the absolute path 

```
# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]
```

**Comment by s4Dt0y** [comment]
yesssss ty. The problem was the absolute path.

(as a side note, the commas were added by the lua autoformatter...which leads me to believe that trailing commas are conventional in lua)
