### ISSUE TITLE
Sketchybar only shows workspaces after I manually reload sketchybar

### ISSUE THREAD

**Issue by jacobrreed** [nikitabobko/AeroSpace#417]
![image](https://github.com/user-attachments/assets/515d90fe-2605-4b95-8e47-f39e13d5cdfd)

Currently I have sketchybar setup as described in aerospace docs, it works but when i first start computer it doesn't show workspaces for some reason, i have to manually `sketchybar --reload` to get it working

## Checklist

- [X ] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - sketchybar
- [ X] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [X ] I've searched in the documentation. My search queries were:
  - sketchybar

```
aerospace CLI client version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd
AeroSpace.app server version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd
```

Here is my relevant aerospace config portion:
```
# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true
```

Here is relevant sketchybar config:
```
sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        label.color=0xff04d1f9 \
        label.font.size=18.0 \
        background.corner_radius=5 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done
```

and finally my relevant aerospace sketchybar script:
```
#!/usr/bin/env bash

if [ "$1" = "1" ]; then
  sketchybar --set $NAME label=" "
elif [ "$1" = "2" ]; then
  sketchybar --set $NAME label=" "
elif [ "$1" = "3" ]; then
  sketchybar --set $NAME label="󰇮 "
elif [ "$1" = "4" ]; then
  sketchybar --set $NAME label=" "
elif [ "$1" = "s" ]; then
  sketchybar --set $NAME label=" "
fi

if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
  sketchybar --set $NAME label.color=0xff37f499
else
  sketchybar --set $NAME label.color=0xff04d1f9
fi

```

After manually calling `sketchybar --reload` :

![image](https://github.com/user-attachments/assets/5ea645e6-4b1c-4a50-90c1-46e778f602a0)

**Comment by FelixKratz** [comment]
I suspect you start sketchybar as a service prior to it being launched by aerospace, such that aerospace is not running when sketchybar is started. Try:
```sh
brew services stop sketchybar
```
and then reboot.

Alternatively, you could keep launching sketchybar as a service and then simply do:
```toml
after-startup-command = ['exec-and-forget sketchybar --reload']
```
to always reload the config (and (re)create the relevant spaces once aerospace (re)starts)

**Comment by jacobrreed** [comment]
Ah ok thank you, let me try that

**Comment by jacobrreed** [comment]
Works thanks
