### ISSUE TITLE
Feature Request: focus across visible workspaces

### ISSUE THREAD

**Issue by mike1808** [nikitabobko/AeroSpace#42]
In i3 if you have multiple monitors it's possible to focus windows by just positional focus commands. For instance, if I have two monitors positioned vertically near each other I can move from the left monitor to the right monitor by using `focus right` on the most-right window on the left monitor.

**Comment by nikitabobko** [comment]
This issue will be fixed together with the #23 

The current work-in-progress syntax to allow `focus` command to go to other monitors will be:
```
focus.boundaries = 'all_monitors_union'
```
See: https://github.com/nikitabobko/AeroSpace/issues/23#issuecomment-1843393552
