### ISSUE TITLE
Center workspace single application

### ISSUE THREAD

**Issue by marcoskichel** [nikitabobko/AeroSpace#420]
Hi, thanks so much for this amazing tiling window manager, I am a brand new user and I am falling in love with it!

I have a small question, I am usually working on a wide screen monitor, so something that I would really enjoy would be to have Aerospace automatically centering applications (with around 60% of the screen width) when there are no other open applications in the same workspace. Alternatively a shortcut for that could also work.

I wonder if there is built-in way to do that, or maybe some API that I can explore to implement a script that I can run when switching workspaces?

I tried working with `aerospace resize width -x` but that won't work for some reason.

**Comment by nikitabobko** [comment]
Please don't ignore the checklist
