### ISSUE TITLE
Contradiction with config omitted key documentation?

### ISSUE THREAD

**Issue by LandonSchropp** [nikitabobko/AeroSpace#421]
I noticed a comment in `default-config.toml` and the AeroSpace Guide seem to contradict each other. 

In [`default-config.toml`](https://github.com/nikitabobko/AeroSpace/blob/main/docs/config-examples/default-config.toml#L3-L4), it says this:

``` toml
# In your config, you can drop keys you don't care about
# The absent keys will fallback to their default values
```

However, the [AeroSpace guide](https://nikitabobko.github.io/AeroSpace/guide#default-config) says this:

> The default config is not merged into your custom config. That’s why you can drop key bindings by dropping their declaration from your custom config.

It seems like one of these might need to be updated. 😃 

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - default config
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - default config

```
aerospace CLI client version: 0.14.0-Beta 96ae7a761f5f969b21e00345629558e005d125c5
AeroSpace.app server version: 0.14.0-Beta 96ae7a761f5f969b21e00345629558e005d125c5
```

**Comment by LandonSchropp** [comment]
As a side note, I am just a bit confused on which keys are needed and which ones can be discarded. For example, I can't drop the workspace keyboard shortcuts, but I can drop the gaps ones without consequences.

**Comment by nikitabobko** [comment]
> For example, I can't drop the workspace keyboard shortcuts

What makes you think so?

**Comment by LandonSchropp** [comment]
Sorry, I wasn't clear. What I meant was that I can drop the workspace keyboard shortcuts without any consequences (as in dropping them will not fall back onto default values), but I can drop the gaps section and the config still seems to be fine.

What's not clear to me is which keys will fall back to defaults, and which won't.

**Comment by nikitabobko** [comment]
It should be better now https://nikitabobko.github.io/AeroSpace/guide#default-config

**Comment by LandonSchropp** [comment]
@nikitabobko Awesome! Thank you. 🙂
