### ISSUE TITLE
feature request: preserve fullscreen when switching focus

### ISSUE THREAD

**Issue by volomas** [nikitabobko/AeroSpace#422]
I have a workspace with multiple windows. I go to fullscreen (not native) with one of them.
When I change the focus to other window (be it alt-hjkl or cmd+`), it pops out of fullscreen to whatever layout I have.

Is it possible to be in fullscreen mode all the time and switch between windows without exiting it?

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - fullscreen
  - focus

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
- Please don't ignore the checklist in the issue template
- Please describe why your use case is valid (I don't think that it's valid)
- Consider using accordion layout for your use case.

**Comment by volomas** [comment]
> * Please don't ignore the checklist in the issue template
> * Please describe why your use case is valid (I don't think that it's valid)
> * Consider using accordion layout for your use case.

- added checklist, sorry for that
- I guess it's more applicable for those who have small screens (laptop-only). Sometime I want to be fullscreen all the time. That means, when I switch windows in same workspace, I need to do alt-h + alt-f, then alt-l + alt-f, etc., which is extra keystrokes
- accordion is indeed close to what I want, but it waistes a bit of space on the screen (especially when you are on laptop). Usually I know what other windows I have, I don't need to see them all the time.

**Comment by nikitabobko** [comment]
> but it waistes a bit of space on the screen

```
accordion-padding = 0
```

**Comment by volomas** [comment]
> > but it waistes a bit of space on the screen
> 
> ```
> accordion-padding = 0
> ```

Perfect, exactly what I was looking for, thanks a lot
Loving this tool so far, great job!

**Comment by apasias** [comment]
> > but it waistes a bit of space on the screen
> 
> ```
> accordion-padding = 0
> ```

This is not trully fullscreen. If you have joined two windows you get half full screen (See screenshot in arccordin layout with 0 padding for joined windows)
In the figure below Gmail is joined with Google calendar (which is hidden). So this trick with accordion-paddin=0 works only if you do not have joined windows together.


![image](https://github.com/user-attachments/assets/aec5cf65-2a9a-44a8-aebd-fd9fd620ed99)
