### ISSUE TITLE
Feature Request: Implement `focus --dfs-index`

### ISSUE THREAD

**Issue by Perlten** [nikitabobko/AeroSpace#427]
Hi great project, love to see a window manager that avoids using MacOs spaces. 

Some Linux window managers, such as [Qtile](https://github.com/qtile/qtile/blob/223200df0113e3ad4680c84cd6a7b0239b302fc2/libqtile/group.py#L533), provide the ability to switch between windows using an "index" system, similar to how workspace switching currently works. The method for assigning these indices is flexible, but one approach could be to start from the top-left corner as index 1 and proceed in a left-to-right, top-to-bottom order, similar to reading a book. Implementing this feature would allow users to consistently switch to a specific window without needing to consider the current focused window's position relative to the desired window.

For an accordion layout, the index could initially be determined by the order in which windows first appear in the workspace. However, it would be even more user-friendly if users could set the index for each window themselves and have the option to change it using keybinds

I hope this makes sense, and thank you for the amazing work!

**Comment by nikitabobko** [comment]
Please don't ignore the checklist in the issue template.

The request itself makes sense, and matches nicely with #248 

I don't mind if somebody will implement it in the following way:
```
aerospace focus --dfs-index <index>
```

I don't plan to work on it.

**Comment by Perlten** [comment]
Seems like a good solution using dfs. I could implement the feature and submit a PR.

**Comment by nikitabobko** [comment]
Released in 0.15.0-Beta
