### ISSUE TITLE
LSP Support

### ISSUE THREAD

**Issue by joshmedeski** [nikitabobko/AeroSpace#431]
As a user, I want autocomplete support while editing the toml file, so I can ensure accuracy and receive feedback on my configuration before saving it.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were: "lsp" and "autocomplete"

## Details

The [taplo](https://taplo.tamasfe.dev/) project supports defining a json definition to allow for a richer experience while working with toml files. We could replicate similar details to your code comments on the default config.

I can work on this, but I wanted your feedback before I started working on it.

**Comment by alexandru0-dev** [comment]
personally I like this, tho this would only be used for LSP. Do you know how the toml is parsed and validated inside the project?
taplo is a great tool to remedy the fact that toml doesn't support schemas (at the time of writing), but you need to have a json schema, how do you plan to update it?

**Comment by joshmedeski** [comment]
I've been meaning to implement this on one of my projects, but I think it can be updated with the Homebrew tap

**Comment by alexandru0-dev** [comment]
i meant the json schema file, do you plan to map every option manually?

**Comment by nikitabobko** [comment]
I do not plan to provide any kind of LSP out of the box, but you are welcome to provide it yourself in a third party package.

The third party package could be mentioned in the Goodness page.

My personal take: LSP completion based on json schema won't be very useful because the significant part of the config is key bindings and AeroSpace commands. I doubt that taplo json schema can express that.

**Comment by joshmedeski** [comment]
Fair enough, thanks for the quick feedback.
