### ISSUE TITLE
Add usefull boundary actions for switch workspace when there is no window to be focused

### ISSUE THREAD

**Issue by vitusli** [nikitabobko/AeroSpace#433]
Hi! Since I am not allowed to disable SIP on my working computer I checked out Aerospace which is such a pleasure to read through the docs. Thanks for this amazing work.

I love having dedicated boundary actions in your the aerospace config. In Yabai I had to set them up with [|| operators](https://github.com/nikitabobko/AeroSpace/issues/278) which works fine: when I come to the right boundary of my workspace and there is no next window to focus my WM focuses the next workspace. Same for upper direction: if there is no upper window it focusses the next monitor. I love this feature and want to suggest additional boundary actions for the use case mentioned above.

```
focus (left|right) --boundaries workspace --boundary-action workspace (prev|next)
focus (down|up) --boundaries all-monitors-outer-frame --boundary-action focus-monitor (prev|next)
```

I have read many issues and could not find a solution for this even though I found many others. I started with Aerospace in the morning and brought it pretty far with docs + this repo. 

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
Please don't ignore the checklist in the issue template

I won't be adding new `boundaries-action`s since it significantly complicates the CLI. The feature you're asking is going to be covered by #278

**Comment by vitusli** [comment]
Sorry, fully understand. I tried to put as much of the needed informationen from the checklist into the text but added now the checklist. Thanks for the fast response. 

I solved this basically by using different 'modes' for tiling and accordion layout.
