### ISSUE TITLE
Provide a command to forget a window

### ISSUE THREAD

**Issue by graywolf** [nikitabobko/AeroSpace#435]
Hi,

would you please consider adding a command to make aerospace forget a window?  It sometimes happens to me that aerospace thinks that window is still present despite the application being closed.

`list-apps` *does not* show the application, but `list-windows` *does* show the window.  When I modify the format for `list-windows` to include a process id, I can see that there is *no process with such PID*.  Hence I believe the window in question just someone got stuck when I closed the application.

Right now I solve this by restarting aerospace, but that is somewhat clunky.  Would be nice to be able just run something like `aerospace forget-window WIN_ID` instead.

I tried `aerospace close-all-windows-but-current` and am told `Can't close 'Emacs' window. Probably the window doesn't have a close button`.  But even if that worked, sometimes I do not want to close all windows :)

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - kill window
  - forget window
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - close

```
both are 0.14.2-Beta, but I am writing this from non-mac so cannot copy&paste
```

**Comment by nikitabobko** [comment]
I'm closing this issue in favor of #445
