### ISSUE TITLE
Add documentation for the menu bar

### ISSUE THREAD

**Issue by DjebbZ** [nikitabobko/AeroSpace#439]
Hello,

The AeroSpace documentation is quite exhaustive regarding the installation and configuration, but doesn't mention at all anything related to the menu bar.

I'm creating this issue because after some (?) manipulation I noticed a `[s]` appeared, no idea how and what it is.

As I don't know this menu bar nor Swift I can't dig in and write the docs myself, but I'm gently asking for documenation about everything related to the menu bar.

Happy to help reviewing/writing it if possible.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too): `menubar`, `bar`, `menu`
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were: `bar`, `menu`

``` shell
~ aerospace --version
aerospace CLI client version: 0.12.0-Beta 9cf82feb0c85bea77fedcdc6b8cdba75b5bbf1f8
AeroSpace.app server version: 0.12.0-Beta 9cf82feb0c85bea77fedcdc6b8cdba75b5bbf1f8
```

**Comment by DjebbZ** [comment]
You mean, when one switches to a mode other than main, the first letter
appears in square brackets?

If so, this is exactly the kind of behavior that needs documentation.

**Comment by danfbfern** [comment]
> You mean, when one switches to a mode other than main, the first letter appears in square brackets? If so, this is exactly the kind of behavior that needs documentation.

That is precisely the case, but its not documented like you said.
On this note, I would even prefer to see an option to show the full mode name instead of just the first letter or even more customisation regarding the menubar and remove the need of sketchybar to show information about opened workspaces for example.

**Comment by Grezzo** [comment]
> this is exactly the kind of behavior that needs documentation

You don't need to be a developer to contribute to the docs. Fork the repo, create a branch, update the docs (e.g. at docs/guide.adoc in the repo) then issue a pull request.

The dev has clearly put a lot of time into this project and released it for us to use at no cost. From doing some dev work myself I know that writing docs is the least fun and motivating part of the work. The docs are good but are not perfect, as you've pointed out. If you have the time but not the dev skills to fix bugs or make other enhancements then it would be great if you could contribute to the project by adding whatever you see as missing in the docs :-)

**Comment by DjebbZ** [comment]
Ok, I may try adding docs for the menubar item some time this week (hopefully).

Leaving the issue opened for my (hopefully) upcoming PR.

**Comment by nikitabobko** [comment]
I think that the menu bar is self-describing and it doesn't require documentation. Adding _more_ documentation is not strictly better. The documentation shouldn't be overwhelming.

There always will be things that some people don't understand, but others find obvious. So far I saw only one user confused by the menubar behavior.
