### ISSUE TITLE
Bar Integration

### ISSUE THREAD

**Issue by schneider-inc** [nikitabobko/AeroSpace#44]
It would be useful for macOS ricers to be able to integrate Aerospace into macOS bars such as SketchyBar (in my case), so maybe a CLI command to get the current active workspace - and all workspaces for that matter?

**Comment by MatthiasGrandl** [comment]
I updated my sketchybar config based on the new (as of right now unreleased) `list-workspaces` command. Maybe this saves somebody a bit of work. it is limited by the event system. obviously `space_change` only applies to mission control spaces not aerospace workspaces, but for my usecase the `front_app_switched` works well enough. for some reason there is a small delay when changing spaces though, haven't debugged that yet.

sketchybarrc:

```bash
for sid in $(aerospace list-workspaces); do
  color="$INACTIVE"
  sketchybar --add item space.$sid left \
    --subscribe space.$sid front_app_switched \
    --subscribe space.$sid space_change \
    --set space.$sid \
    icon="􀀁" \
    background.drawing=off \
    label.drawing=off \
    icon.color="$color" \
    icon.font.size=12 \
    icon.align=center \
    padding_left=0 \
    padding_right=6 \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_DIR/aerospace.sh $sid"
done
```

plugins/aerospace.sh:

```bash
#!/usr/bin/env bash

SID=$1
FOCUSED=$(aerospace list-workspaces --focused)
bg="0xff585b70"
if [ "$SID" = "$FOCUSED" ]; then
  bg="0xffb4befe"
fi
sketchybar \
  --animate sin 10 \
  --set $NAME \
  icon.color="$bg"
```

**Comment by nikitabobko** [comment]
BTW, it would be nice if someone could describe a basic setup with any of the existing bars (sketchybar, uebersicht) in [AeroSpace Goodness page](https://nikitabobko.github.io/AeroSpace/goodness.html). The source code for the page is https://github.com/nikitabobko/AeroSpace/blob/main/docs/goodness.adoc

Just saying :)

**Comment by MatthiasGrandl** [comment]
I can take care of that (for sketchybar). I’ll open a PR with a minimal setup, once the CLI is released.

**Comment by MatthiasGrandl** [comment]
@nikitabobko Should I be able to get updates through the unix socket? For example workspace changes? Then I could implement a proper sketchybar event, which would be nicer than just polling for changes.

**Comment by nikitabobko** [comment]
@MatthiasGrandl please create an issue. It'd be nice to include the info on what would be the best format to integrate with sketchybar

I can see several ways on how it can be done:
- TOML Config option `on-workspace-changed = 'on-workspace-changed sketchybar update'`
- CLI command `aerospace on-workspace-changed sketchybar update`
- Both

Note: `sketchybar update` is a placeholder. I don't know what command sketchybar uses

**Comment by MatthiasGrandl** [comment]
@nikitabobko done, thank you #76

**Comment by MatthiasGrandl** [comment]
> BTW, it would be nice if someone could describe a basic setup with any of the existing bars (sketchybar, uebersicht) in [AeroSpace Goodness page](https://nikitabobko.github.io/AeroSpace/goodness.html). The source code for the page is https://github.com/nikitabobko/AeroSpace/blob/main/docs/goodness.adoc
> 
> I don't use bars, that's why I want someone else to do it
> 
> Just saying :)

Done #81 ! It depends on PR #80 to be merged and released.

**Comment by diogox** [comment]
Unfortunately, from `v0.14.0-Beta`, the `Displays have separate Spaces` setting is recommended as disabled and Sketchybar will not start unless it's enabled.

Any other options out there?

**Comment by noctuid** [comment]
(For anyone coming here in the future, sketchybar works with "Displays have separate spaces" disabled now)
