### ISSUE TITLE
Keybinding for Moving Finder to Current Workspace in AeroSpace Beta

### ISSUE THREAD

**Issue by LockeAG** [nikitabobko/AeroSpace#441]
I found that persisting a floating window across workspaces is not supported (as noted in [Issue #2](https://github.com/nikitabobko/AeroSpace/issues/2)).

I use Finder a lot and I've been trying to create a custom solution to move it to the current workspace with a keybinding. I've managed to make it work, but the process still feels a bit clunky. I could really use a smoother solution.

`cmd-shift-alt-down = "exec-and-forget ~/.dotfiles/.aerospace/finder_move.sh"`

```
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

current_workspace=$(aerospace list-workspaces --focused)

osascript -e "
tell application \"Finder\"
    activate
end tell
" && aerospace move-node-to-workspace "$current_workspace" && aerospace workspace "$current_workspace"
```

Is there a more efficient way to achieve this? Any improvements or guidance would be appreciated.

```
aerospace CLI client version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd                                                
```
```
AeroSpace.app server version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd 
```

**Comment by nikitabobko** [comment]
Please don't ignore the checklist
