### ISSUE TITLE
Cant move using arrow keys or arrow keys dont work

### ISSUE THREAD

**Issue by Anastand** [nikitabobko/AeroSpace#450]
**I want to remap the default keys to foucs windows to arrow keys but they aren't working**
my config ->
> ctrl-h= 'focus left'
ctrl-j = 'focus down'
ctrl-k = 'focus up'
ctrl-l = 'focus right'

i want to make it like ->
> ctrl-left= 'focus left'
ctrl-down = 'focus down'
ctrl-up = 'focus up'
ctrl-right = 'focus right'
-- here left , down , up, right is arrow key in mac os

### suggestion
- i can help make the documentation better in writing things in simple words , pls let me know if you want me to do it.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - arrow move
  - arrow
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
```
<!-- aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201 output -->
```

**Comment by nikitabobko** [comment]
Works for me

Please make sure that bindings don't conflict with other software that listens to global keys (e.g. skhd, karabiner)
