### ISSUE TITLE
Feature Request: Animated Windows

### ISSUE THREAD

**Issue by gitultra75848** [nikitabobko/AeroSpace#452]
As the Title says, I think having an Animated Windows functionality would be cool. (For example, opening an app would have an animation, same with closing an app, similar to yabai. As you can infact do this in i3, it would be cool to be able to do it here.)

## Checklist

- [x] I've searched for duplicates. My search queries were:
  - animation
  - feature request
 
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - window animations
  - animations

**Comment by nikitabobko** [comment]
Goes against project values

> Provide practical features. Fancy appearance features are not practical (e.g. window borders, transparency, etc)

**Comment by Bellavene** [comment]
Off topic
> Provide practical features. Fancy appearance features are not practical (e.g. window borders, transparency, etc)
Window borders are just fancy on a window manager? First time I hear that. Not a problem, there is jankyborders if someone needs them. But this is so false, those features allow you to see where is your active window, thats practical. In fact it is even better when they are shaded, without borders or transparency, like in hazeover.app
