### ISSUE TITLE
Feature request: group/bind workspaces for multi monitor setup

### ISSUE THREAD

**Issue by hwamil** [nikitabobko/AeroSpace#454]
When I am working with two or more monitors it would be nice to group/bind workspaces on each monitor to one another so that switching to one of them would change the workspaces on the other monitor(s) automatically.

For example, I have all lettered workspaces on `main` and all numbered spaces on `secondary`. Sometimes I like to work with a set of two apps side-by-side on each monitor, but then switch to another set of two apps, and etc.

Right now, to achieve this, I have to memorize two workspaces and also the combination so that I can open the desired workspace on each monitor. It is really no issue for the lettered workspaces since that's where assigned applications live, but for the numbered workspaces which I use as support, it is difficult to keep track of.

It would be ideal if I could manually group/ungroup workspaces through a `service` keybind of sort so that I don't have to commit to a hard-coded configuration (e.g., alt+; & g when desired workspaces are living on each monitor).

## Checklist

- [ x ] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - group workspaces
  - workspace(s)
  - grouping
- [ x ] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [ x ] I've searched in the documentation. My search queries were:
  - workspace
  - group(s)

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by hwamil** [comment]
After writing this, I remembered that you could have a list of commands in the config to have something like this:

`alt+t = ['workspace T', 'workspace 1']`

But the problem is that, when using a single monitor (e.g., macbook while traveling) this bind will trigger both commands where you would end up with `workspace 1` instead of `workspace T`.

I also realize that you can make a custom mode to accomplish this, but I think it is a good quality of life improving feature if shipped by default.

Thanks for hearing me out.

**Comment by nikitabobko** [comment]
> But the problem is that, when using a single monitor (e.g., macbook while traveling) this bind will trigger both commands where you would end up with workspace 1 instead of workspace T.

You can do the following:
```
alt-t = ['workspace 1', 'workspace T']
alt-1 = ['workspace T', 'workspace 1']
```

It won't even flicker, because AeroSpace commands macOS to only focus the final state

**Comment by hwamil** [comment]
> > But the problem is that, when using a single monitor (e.g., macbook while traveling) this bind will trigger both commands where you would end up with workspace 1 instead of workspace T.
> 
> You can do the following:
> 
> ```
> alt-t = ['workspace 1', 'workspace T']
> alt-1 = ['workspace T', 'workspace 1']
> ```
> 
> It won't even flicker, because AeroSpace commands macOS to only focus the final state

Hey, thank you for this awesome tool! I've tried both Amethyst and Yabai - uninstalled them immediately after trying Aerospace. After using this for a while, I don't even understand why this is not default for ALL computers out there.

That said, I am doing something similar to your suggestion by using a custom mode:
```
[mode.mm.binding]
esc = ['reload-config', 'mode main']
b = ['workspace 0', 'workspace B', 'mode main']
m = ['workspace 9', 'workspace M', 'mode main']
...
```

Which isn't half bad, since I still have the flexibility of changing individual workspace, but I still, at specific moments, have a want for the ability to group the *currently visible* workspaces together.

But at the same time I can understand why you may think this is redundant and lacks actual utility since Aerospace is about flexibility, and adding something will make it more rigid in a way.

The custom mode method is about 98% working for me, so I'll just close this FR.

Thanks again!

**Comment by hwamil** [comment]
Oh, one thing I forgot to mention:

Two things that are not quite right with this method are:
- Invoking two workspaces instead of one means that focus will be on the workspace that is at the end of the list
- `workspace-back-and-forth` does not invoke the "group" of workspaces, but just the last workspace used, so it can become a bit fatiguing having to go back-and-forth with the custom mode commands.
