### ISSUE TITLE
Feature Request: Include which space a window is located

### ISSUE THREAD

**Issue by albertilagan** [nikitabobko/AeroSpace#458]
when running `aerospace list-windows --all` it results to this,

|  |     |     |
| :---:   | :---: | :---: |
| 483 | Amie | Amie |
| 466 | Arc | New Issue · nikitabobko/AeroSpace |
| 474 | Discord | #releases | Luxor Corp - Discord |
| 605 | WezTerm | t ~ |

it would be nice if we include the `space` where the `window` is located as part of the table/output.
| |  |     |     |
| :---:   | :---: | :---: | :---: |
| 1 | 483 | Amie | Amie |
| 2 | 466 | Arc | New Issue · nikitabobko/AeroSpace |
| 3 | 474 | Discord | #releases | Luxor Corp - Discord |
| 4 | 605 | WezTerm | t ~ |

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - include space
  - list-windows
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - include space
  - list-windows

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
Please read the documentation more carefully

`aerospace list-windows --all --format '%{window-id} %{workspace}'`
