### ISSUE TITLE
Feature request: Query current mode

### ISSUE THREAD

**Issue by vramdal** [nikitabobko/AeroSpace#459]
The app's menu bar item includes an indication of the current mode, so that if I trigger mode `join`, the menu bar displays `[j]`:
<img width="197" alt="image" src="https://github.com/user-attachments/assets/f0608938-d754-413c-9f1e-162952cc593f">

Now I use Sketchybar, and I'd like to do the same thing there.

To do so, I would need some way of querying AeroSpace about the current mode.

A query command like
```
aerospace get-mode
```
would be great.

**Comment by nikitabobko** [comment]
Please don't ignore the checklist
