### ISSUE TITLE
[BUG] Multiple Windows of the same application cannot really be on different workspaces

### ISSUE THREAD

**Issue by apasias** [nikitabobko/AeroSpace#461]
**Description:**

When using multiple windows of the same application (e.g., 2 VSCode windows, 2 browser windows, or 2 Finder windows) across different workspaces, the following issue occurs:

I move the first window to Workspace 1 and the second window to Workspace 2.
I hide the application (using the "Hide" option instead of "Minimize" since there is no shortcut for unminimize).
Upon unhiding the application, both windows reappear in the current workspace, rather than each window reappearing in its assigned workspace.

**Expected Behavior:**

When unhiding the application, only the window that was originally assigned to the current workspace should reappear. Other windows should remain in their respective workspaces.

**Aerospace version:** v0.14.2-Beta

**Comment by nikitabobko** [comment]
Please don't ignore the checklist

**Comment by apasias** [comment]
> Please don't ignore the checklist

@nikitabobko Hi, sorry I just updated the checklist and thanks for the great work.

**Comment by apasias** [comment]
@nikitabobko Hi, is this really fixed?
