### ISSUE TITLE
Some apps issues on dropdown opening

### ISSUE THREAD

**Issue by sndrgb** [nikitabobko/AeroSpace#466]
Hello everyone,
I've been trying Aerospace lately, and I really like it. However, there's something strange that I can't figure out:
Some dropdowns in different apps flicker, almost as if the focus is constantly changing. I also notice that when I type into input fields, my cursor keeps flickering. I'm trying to understand why this happens. At first, I thought it might have something to do with the dialog heuristics mentioned in the documentation, but these aren't dialogs, right?

Here some screens:
https://github.com/user-attachments/assets/4cdb123d-af56-46cf-a8e7-bc7421c2818c
https://github.com/user-attachments/assets/e4895d5a-50e5-40c2-bd57-2760112f097d

- [x] I've searched for duplicates. My search queries (in many combinations) were:
  - chrome
  - illustrator
  - adobe
  - focus
  - autofocus
  - dropdown

- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands

- [x] I've searched in the documentation. My search queries were:
  - dropdown
  - dialog

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
Do you run query commands in background? (e.g. for sketchybar) #317

**Comment by sndrgb** [comment]
This is true. Sorry I try a lot but yes it was a query command in background. Now I investigate on #317  on how to resolve
