### ISSUE TITLE
[Feature Request] : Enhanced Zoom functionality for Multi-Window management

### ISSUE THREAD

**Issue by danfbfern** [nikitabobko/AeroSpace#470]
### Description
The current zoom options, `fullscreen` and `macos-native-fullscreen`, while effective for many use cases, lack flexibility when managing 3 or more windows simultaneously. There is no current capability for intermediate zoom states beyond the full-screen or multiple visible windows without any priority.

### Current Behavior
Currently, the options allow either a single application to occupy the full screen or multiple applications to share the screen without any prioritization. This binary choice does not support scenarios where visibility of more than one but not all windows is desirable.

### Proposed Feature
Introduce a new zoom feature that allows one of the windows in a multi-window container to be temporarily expanded to fill its parent container, making it the focal point while still keeping at least one other window visible. 
This feature would be similar to zoom-parent in `Yabai`, allowing for dynamic resizing of windows within their current containers to better manage screen real estate, especially in complex multi-window setups.

### Example Configuration
An example of how windows are currently organized:
```
h_tiles
├── window 1
└── v_tiles
    ├── window 2
    └── window 3
```
    
Desired behaviour after implementing the feature:
```
h_tiles
├── window 1 (visible)
└── v_tiles
    ├── window 2 (not visible - behind window 3)
    └── window 3 (visible - zoomed)
```
    
In this configuration, while window 3 is in focus, it can be toggled to 'zoom' and fill the container size, pushing window 2 into the background, similarly to how fullscreen works but within a smaller scope.

### Additional Context
This functionality is inspired by the zoom-parent feature in Yabai, which proved extremely useful for managing multiple windows efficiently and it was actually my main zoom option since it would behave the same as the `fullscreen`when only 2 windows were being displayed.
Here's how I had the configuration in Yabai:

```
alt - f : yabai -m window --toggle zoom-parent
ctrl + alt - f : yabai -m window --toggle zoom-fullscreen
shift + ctrl + alt - f : yabai -m window --toggle native-fullscreen
```

This feature would significantly enhance usability in environments with extensive multitasking demands.

**Comment by nikitabobko** [comment]
While the request makes sense, I doubt that the feature will bring enough value. Alternatively, you can just the `accordion` layout

```
h_tiles
├── window 1 (visible)
└── v_accordion
    ├── window 2 (not visible - behind window 3)
    └── window 3 (visible)
```

**Comment by nikitabobko** [comment]
> Meaning that I would not have the ability of pressing the same key to toggle that fake fullscreen.

You can use it in "toggle" style

```toml
alt-f = 'layout accordion tiles'
```

**Comment by danfbfern** [comment]
> > Meaning that I would not have the ability of pressing the same key to toggle that fake fullscreen.
> 
> You can use it in toggle style
> 
> ```toml
> alt-f = 'layout accordion tiles'
> ```

Thanks it works great, didn't knew this was an option.
Since this works and is able to replicate the original request close enough even though a bit different, probably does not make much sense to keep this feature request if you feel lke it does not add any benefits.
