### ISSUE TITLE
Failing to use norwegian letter for key-mapping.key-notation-to-key-code

### ISSUE THREAD

**Issue by torarvid** [nikitabobko/AeroSpace#473]
Hi there, and thanks for an awesome app 🚀

I saw in the docs:

> If you use different layout, different alphabet, or you just want to have a fancy alias for the existing key, you can use key-mapping.key-notation-to-key-code.

And I thought I would be able to use my norwegian keys in bindings. But when trying this, I get an error (screenshot below).

This is the same error I get if I simply try to use `alt-ø = ['fullscreen']` as a binding directly.

<img width="967" alt="image" src="https://github.com/user-attachments/assets/95f02315-2a74-4b39-b830-7bf26ca670f1">

Maybe I misunderstood the docs, but my interpretation made me think this should work 🧐 

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - key-notation
  - æøå
  - non-us
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [ ] I've searched in the documentation. My search queries were:
```
AeroSpace v0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
It should be vice versa:
```
[key-mapping.key-notation-to-key-code]
'ø' = 'f'
```

**Comment by torarvid** [comment]
Hi, and thanks for the response. But I still don't understand if it's possible to do what I want, which is "when I press alt-ø" on my norwegian keyboard, I'd like to execute the command 'fullscreen'.

From your reply, I tested setting:

```toml
[key-mapping.key-notation-to-key-code]
'ø' = 'f'
```

and this works. However, I cannot do:

```toml
[mode.main.binding]
alt-ø = ['fullscreen']
```

Then I get this:

<img width="421" alt="image" src="https://github.com/user-attachments/assets/d1578f4e-34f4-48c0-aae9-71866cff0ea5">

And if I leave it as
```toml
[mode.main.binding]
alt-f = ['fullscreen']
```

Then neither `alt-f` nor `alt-ø` runs the 'fullscreen' cmd.

**Comment by nikitabobko** [comment]
```
alt-ø = ['fullscreen']
```

This is invalid TOML syntax. Please put quotes around your key:
```
'alt-ø' = ['fullscreen']
```

**Comment by torarvid** [comment]
That gives me this error:

<img width="848" alt="image" src="https://github.com/user-attachments/assets/0892b5c6-8c7f-4a1b-93f5-ccf61744f709">

**Comment by cardaria** [comment]
@torarvid Did you find any solution? I'm encountering the same error when using 'ä'.

**Comment by torarvid** [comment]
No @cardaria, it is unclear to me why this issue was closed.

**Comment by apoll2000** [comment]
I found out how it works for me, I'm hoping it's the same for you.

Aerospace actually seems to interpret the key inputs from non-US keyboards as if they were from US keyboards. So to test what Aerospace sees when you type an umlaut or any other letter, just change your keyboard layout to US in the macOS System Preferences and type anywhere. For me, when I now type an 'ü', it produces a '[' (which checks out with the physical location of the key if you google images of US keyboard layouts). So, to use an 'ü' in the Aerospace config, simply use the 'leftSquareBracket' shortcut that already exists. This should transfer to other non-US keyboards, I believe.

Let me know if this works for you.

**Comment by JDuffe** [comment]
@acpoll Thanks for your comment on this, I was having the same problem and your solution did work for me. 
However, I would prefer a more “intuitive” solution (maybe I also just don't understand the custom key-mappings correctly).

I think that it would be very handy if, in the future, other layouts (in addition to QWERTY and Dvorak) could be implemented as presets (like QWERTZ etc.) @nikitabobko.
