### ISSUE TITLE
on-window-detected with multiple app-ids 

### ISSUE THREAD

**Issue by loeschg** [nikitabobko/AeroSpace#477]
Is there a way to configure the floating layout for multiple app-ids in the `on-window-detected` hook?

I have several applications that I'd like aerospace to ignore / just float without needing to duplicate all the boilerplate

```
[[on-window-detected]]
if.app-id = ['com.apple.finder', 'com.apple.MobileSMS', 'com.apple.Preview', 'us.zoom.xos']
check-further-callbacks = true
run = ['layout floating']
```

The above syntax fails given the array type.

**Comment by jakenvac** [comment]
That array syntax is not supported. But the behavior you're looking for should be possible. If you checked the [guide](https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback) you'd have seen that you can use a regex match for the window title or app name. Have you tried this?

**Comment by loeschg** [comment]
I did see that, and I can (and probably should instead) use that! Feels a bit like a workaround to chain regex together for a situation I’d assume to be common, though. I guess consider this a feature request. 

Appreciate the comment!
