### ISSUE TITLE
Going fullscreen on an app makes other monitors go black

### ISSUE THREAD

**Issue by gservat** [nikitabobko/AeroSpace#485]
I'm running Aerospace on a 3 monitor set-up and whenever I go into fullscreen mode in an app like Chrome or Firefox, it goes into fullscreen mode correctly on the monitor that the app with the workspace is on, but it hides all other windows in the other 2 monitors leaving them just black.

Ideally the app would go fullscreen on the workspace it's on but the other monitors keep showing their apps. I'd like to be able to leave the app running in fullscreen mode and still be able to use my shortcuts to switch to other workspaces at least on the other monitors, but it would be brilliant if I could switch workspaces even on the monitor that the app is running fullscreen on.

Is this a bug or a feature request or [PEBKAC](https://en.wiktionary.org/wiki/PEBKAC)?

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - fullscreen
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - fullscreen
```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by hwamil** [comment]
This is expected behavior since all monitors/desktops share one and the same MacOS space.

**Comment by gservat** [comment]
> This is expected behavior since all monitors/desktops share one and the same MacOS space.

Yep, understand that. As I'm not familiar with the code, I wondered if this is just a limitation of Aerospace due to the nature of virtual workspaces or if there is any way around it.

**Comment by gservat** [comment]
I guess this limitation is covered in:

https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces

**Comment by nikitabobko** [comment]
Yes, it's a macos limitation https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces

You can enable `Displays have separate Spaces` back, but there are possible drawbacks. See the table and choose
