### ISSUE TITLE
How to disable tiling completely?

### ISSUE THREAD

**Issue by boronine** [nikitabobko/AeroSpace#49]
I'm currently using yabai as a solution to the slow workspace switching problem. AeroSpace seems to have a better solution, but I cannot figure out how to disable tiling or just put all windows in floating mode. I assume this is possible?

I suspect there's other users like me, so it might be good to mention this in the docs.

Thank you for your work!

**Comment by nikitabobko** [comment]
```
[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'
```

It's mentioned in the docs https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#on-window-detected-callback

You might also want to disable all default bindings:
```
mode.main.binding = {}
```
