### ISSUE TITLE
"cmd-backspace" not captured when mapped

### ISSUE THREAD

**Issue by iovis** [nikitabobko/AeroSpace#493]
I was trying to map the following:

```toml
ctrl-alt-cmd-backspace = 'workspace-back-and-forth'
```

But it wasn't working, the following did work:

```toml
ctrl-alt-backspace = 'workspace-back-and-forth'
```

So I'm guessing that `cmd-backspace` may not be visible to AeroSpace somehow?

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - backspace
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - backspace

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
Can't reproduce

Most probably there is another software that intercepts this global shortcut

**Comment by iovis** [comment]
In case someone else stumbles upon this in the future, I figured out why this happens. `ctrl-alt-cmd-backspace` is a reserved (non-modifiable) keybind in macOS to disconnect all devices currently connected through Universal Control: https://support.apple.com/en-mide/102459
