### ISSUE TITLE
F-keys (NOT Fn) are just working until F12 and in combination with only modifiers

### ISSUE THREAD

**Issue by martinengelke** [nikitabobko/AeroSpace#498]
Hello,

unfortunately AeroSpace isn't recognise F-keys above F12 and also not in combination with standard keys, only modifiers 
If I bind them I get following errors:

> mode.main.binding.shift-f18-h: Can't parse modifiers in 'shift-f18-h' binding
> mode.main.binding.shift-f18-h: Can't parse modifiers in 'shift-h-f18' binding

same for:

> mode.main.binding.shift-f1-h: Can't parse modifiers in 'shift-f1-h' binding
> mode.main.binding.shift-f1-h: Can't parse modifiers in 'shift-h-f1' binding

shift-f1 ... shift-f12 are compiling and working, as far as I can test on my MBP, which just has 12 F-keys.

Background: 
I bound my Hyperkey (⌘⇧⌥⌃) to F18 which now lays on my Caps Lock (KeyUtils), which also acts as ESC if nothing else is triggered (Hammerspoon)

So I would like to do things like: 

1. Caps Lock (literally F18, literally ⌘⇧⌥⌃) + HJKL --> Focus
2. ⌘+Caps Lock (literally F18, literally ⌘⇧⌥⌃) + HJKL --> Expand
3. ⇧+Caps Lock (literally F18, literally ⌘⇧⌥⌃) + HJKL --> Move
4. ...

For now I solved the problem by triggering AeroSpace via shell from Hammerspoon, where I bound the Keys properly. 

Integration of F-keys would be anyway useful.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - F-keys F keys
  - F1 
  - Can't parse modifiers

- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - F-keys F keys
  - F1 
  - Can't parse modifiers

```
<!-- AeroSpace v0.13.4-Beta ae7340ab50f654546dc5523fd7fa5c81faa3d313 -->
```

**Comment by nikitabobko** [comment]
F-keys can't act as modifiers. It's macOS restriction

**Comment by martinengelke** [comment]
But Shift is actually one, so shift and F-Key should work then? Shift f1,f2... at least does.
