### ISSUE TITLE
How to make window fill display? 

### ISSUE THREAD

**Issue by stackingsaunter** [nikitabobko/AeroSpace#502]
![CleanShot 2024-09-09 at 21 17 31@2x](https://github.com/user-attachments/assets/5eb9598e-3c9d-439e-92e4-f20de0f07e7b)

Is it possible to make aerospace fill display and don't have that padding? I have accordiong padding set to 0

**Comment by agenttank** [comment]
depending on what you mean:  

you can use this:

`cmd-shift-f = 'macos-native-fullscreen'`

or disable the gaps in the config file:

```
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       0
outer.right =      0
outer.bottom =     0
outer.top = 0
```
