### ISSUE TITLE
How to focus or open specific apps with shortcuts

### ISSUE THREAD

**Issue by nerap** [nikitabobko/AeroSpace#511]
# Focus or Open specific app with shortcut

I recently started to use `aerospace` (coming from `yabai` & `skhd`), and I was struggling to find a way to open / focus specific apps

So I you have such need here my way of doing it, just replace APP_NAME by yours with your custom keybing, and it will be work for most app.
AeroSpace is using the .app name, so it's pretty straightforward, work just fine

> ⚠️ If for some reason your app is not the same as 'list-windows' output, you might want to change this a bit, and not using"APP_NAME" ⚠️ 

I was wondering if there is any easier way of doing it too (optimal way) ?

```
ctrl-cmd-g = 'exec-and-forget APP_NAME="Arc" && (aerospace focus --window-id "$(aerospace list-windows --all | awk -F"|" "/$APP_NAME/ {print \$1}" | awk "{print \$1}")" || open -n /Applications/$APP_NAME.app)'
ctrl-cmd-i = 'exec-and-forget APP_NAME="Alacritty" && (aerospace focus --window-id "$(aerospace list-windows --all | awk -F"|" "/$APP_NAME/ {print \$1}" | awk "{print \$1}")" || open -n /Applications/$APP_NAME.app)'
ctrl-cmd-s = 'exec-and-forget APP_NAME="Slack" && (aerospace focus --window-id "$(aerospace list-windows --all | awk -F"|" "/$APP_NAME/ {print \$1}" | awk "{print \$1}")" || open -n /Applications/$APP_NAME.app)'
ctrl-cmd-d = 'exec-and-forget APP_NAME="Discord" && (aerospace focus --window-id "$(aerospace list-windows --all | awk -F"|" "/$APP_NAME/ {print \$1}" | awk "{print \$1}")" || open -n /Applications/$APP_NAME.app)'
ctrl-cmd-n = 'exec-and-forget APP_NAME="Notion" && (aerospace focus --window-id "$(aerospace list-windows --all | awk -F"|" "/$APP_NAME/ {print \$1}" | awk "{print \$1}")" || open -n /Applications/$APP_NAME.app)'
ctrl-cmd-l = 'exec-and-forget APP_NAME="Linear" && (aerospace focus --window-id "$(aerospace list-windows --all | awk -F"|" "/$APP_NAME/ {print \$1}" | awk "{print \$1}")" || open -n /Applications/$APP_NAME.app)'
ctrl-cmd-o = 'exec-and-forget APP_NAME="Obsidian" && (aerospace focus --window-id "$(aerospace list-windows --all | awk -F"|" "/$APP_NAME/ {print \$1}" | awk "{print \$1}")" || open -n /Applications/$APP_NAME.app)'
```  

Hope it will help some of you 🙏

**Comment by gservat** [comment]
@nerap: doesn't `open` already either open the app (if it's not open) or give focus to it? it does for me...

**Comment by nerap** [comment]
Sometimes is does for some apps, but not all of them, you will have this popup `$APP is already open`

![image](https://github.com/user-attachments/assets/9dcaf2c8-37ff-406f-b17d-68c9110921a4)

You can also have the scenario (iTerm if I'm not wrong), where open will create a new window every time
But I think you can't avoid this behavior with `open` options

**Comment by gservat** [comment]
@nerap: ah yeah, sorry, `-n` is what creates a new window of whatever app. If you remove that, it should either open the app or give focus to it. At least that's how it behaves with every app I've tried.

**Comment by btctrl** [comment]
maybe this can be done without a work-around through the api?
I wonder if this can gain some traction if put as a feature request

**Comment by btctrl** [comment]
related:
https://github.com/nikitabobko/AeroSpace/issues/510#issuecomment-2439585933
