### ISSUE TITLE
Windows are hidden when switching workspaces

### ISSUE THREAD

**Issue by gregwebs** [nikitabobko/AeroSpace#52]
This happens a lot to me when using [Arc Browser](https://arc.net/) in its own workspace (#2). It doesn't show up, the workspace is empty!

When it does show up, when I switch to workspace #3, the windows in that workspace don't show up!

It seems Aerospace is having trouble with my basic setup. Is there a debug mode where more information is available to help figure this out?

I saw this before and after upgrading to 14.2. I also tried toggling the Dock & Display settings listed in the README. I didn't notice any difference.

**Comment by nikitabobko** [comment]
> This happens a lot to me when using [Arc Browser](https://arc.net/)

"This" - what exactly?

> When it does show up, when I switch to workspace https://github.com/nikitabobko/AeroSpace/issues/3, the windows in that workspace don't show up!

I don't understand the sentence. What is the cause and what is the effect here? I see two conditions in the sentence

---

Sorry, the issue is unclear. Please report one more time but include the following:
- What steps you took to observe the undesired behaviour (commonly known as "steps to reproduce")
- What is the actual behaviour (undesired)
- What is the expected behaviour (desired)

**Comment by gregwebs** [comment]
Should I keep engaging this issue if it is marked as completed? Other projects use a tagging system so they can tag issues as waiting for feedback. Others may be having this issue and looking for open issues.

"This" refers to the issue title. The window is hidden and doesn't show up at all. All I see is the Mac Desktop wallpaper. If I switch around between workspaces, I can get the window to show up again, but then when I switch to a different workspace, those windows aren't showing up.

* What is the actual behaviour (undesired) - window is hidden
* What is the expected behaviour (desired) - window is shown
* What steps you took to observe the undesired behaviour (commonly known as "steps to reproduce")

I put programs in different workspaces
* #1 notesnook
* #2 Arc Browser
* #3 Warp Terminal & VSCode (vertical split)

When switching to #2, Arc Browser is hidden most of the time. The times that it does show up, if I then switch to #3, those windows are hiden.

I should also mention that this happens with and without an external monitor.

**Comment by lautarocolazo** [comment]
It's sad they closed this one. It has happened the same to me since using the software on different MacBooks. The only fix I have found is to reboot the computer and pray that won't happen again (it usually, randomly does).
