### ISSUE TITLE
Completely disable numbered workspace

### ISSUE THREAD

**Issue by twio142** [nikitabobko/AeroSpace#523]
I wish to only use letters as workspace names, so I deleted all the keybindings of `workspace <digit>` and `move-node-to-workspace <digit>`. But when there's an external monitor, the secondary one is still named as `1`.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - workspace name number
  - default workspace name
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - workspace

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
Workspace `1` is a "phantom" workspace as soon as you move another workspace to your external monitor, phantom workspaces will disappear. See #222
