### ISSUE TITLE
Is it possible to modify custom config location?

### ISSUE THREAD

**Issue by xavierchen0** [nikitabobko/AeroSpace#529]
![image](https://github.com/user-attachments/assets/105c1fd2-3b84-4bca-a2aa-a428b153f50b)

The above is the locations that Aerospace will look for my custom config file. However, instead of `~/.aerospace.toml`, i will like to save it in `~/.config/aerospace/.aerospace.toml`. I also do not want to modify `XDG_CONFIG_HOME` env variable.

I am on macOS.

Thank you!

**Comment by kjvdven** [comment]
I have saved it in `~/.config/aerospace/aerospace.toml` and it works just fine. 
Only difference I see, is the dot in front of the file name.

**Comment by xavierchen0** [comment]
Oh my mistake.
