### ISSUE TITLE
Small artifact on the bottom right of the screen

### ISSUE THREAD

**Issue by junereycasuga** [nikitabobko/AeroSpace#532]
There are small window artifacts on the bottom right of the screen. I know they are windows because of the window borders showing (using JankyBorders)

<img width="1800" alt="Screenshot 2024-09-24 at 17 15 54" src="https://github.com/user-attachments/assets/705f9462-65db-42cd-8996-100834e111a2">

Here's a closer look:

<img width="282" alt="Screenshot 2024-09-24 at 17 15 54" src="https://github.com/user-attachments/assets/a82a0351-3fec-4f46-b267-c5e6fed742ee">

interestingly, one of these window artifacts has the active border (which is kitty located in my space 1)

i'm running on MacOS Sequoia

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - artifacts
  - bottom right
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands).

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
https://nikitabobko.github.io/AeroSpace/guide#emulation-of-virtual-workspaces

> The idea is that if the workspace isn’t active then all of its windows are placed outside the visible area of the screen, in the bottom right or left corner. Once you switch back to the workspace, (e.g. by the means of [workspace](https://nikitabobko.github.io/AeroSpace/commands#workspace) command, or cmd + tab) windows are placed back to the visible area of the screen.

> For better or worse, macOS doesn’t allow to place windows outside the visible area entirely. You will still be able to see a 1 pixel vertical line of "hidden" windows in the bottom right or left corner of your screen.

#66
