### ISSUE TITLE
Question: is there a way to configure an application type to start as floating?

### ISSUE THREAD

**Issue by justinyhuang** [nikitabobko/AeroSpace#536]
Hi,

Not sure if it is already supported, but I think this is a quite common use case: when I start an application (manually, or started by another application), I want its window to be floating to begin with.

Is there a way to do that today?

Cheers,

**Comment by ahmed2m** [comment]
You probably should go through https://nikitabobko.github.io/AeroSpace/guide#configuring-aerospace

**Comment by gservat** [comment]
@justinyhuang: I suspect this issue will get label `issue-template-ignored` as this is in the documentation:

https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
