### ISSUE TITLE
Focus {l,r,u,d} does not work when focused on text input

### ISSUE THREAD

**Issue by emergenz** [nikitabobko/AeroSpace#538]
Focus {left,right,up,down} does not work when focused on text input

## Checklist

- [X] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - text input
  - text focus
- [X] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [X] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). 
```
aerospace CLI client version: 0.14.0-Beta 96ae7a761f5f969b21e00345629558e005d125c5
AeroSpace.app server version: 0.14.0-Beta 96ae7a761f5f969b21e00345629558e005d125c5

```

**Comment by nikitabobko** [comment]
Most probably there is another software that intercepts global shortcuts

**Comment by nikitabobko** [comment]
Or it's because the text input is a password field. It's macOS security feature that disallows apps to capture to global shortcuts with `opt` key while the password field is in focus

**Comment by emergenz** [comment]
Ah yes, I think that is it. Thanks for the clarification.

**Comment by emergenz** [comment]
Though I am using `cmd`, not `opt`, but same issue (only while focusing password fields)
