### ISSUE TITLE
how to not show those 0-9 a-z workspace? i want to use my named workspace only

### ISSUE THREAD

**Issue by woodgear** [nikitabobko/AeroSpace#544]
i want to give workspace a name such like work-1 play-xx
## Checklist
1. use aerospace workspace work-1 create a new workspace and it show this name in menu bar.
2. close all window in this workspace and switch to other workspace and this work-1 workspace disapeard.

- [v] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - https://github.com/nikitabobko/AeroSpace/issues/542
    - in fact if the name could show in menu bar if could be great
  - https://github.com/nikitabobko/AeroSpace/issues/523
    - the built-in workspace are two long. in fact i want to delete them all... 
- [v] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [v] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - workspace

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by ParisTheProgrammer** [comment]
Can you run the command below in a terminal and post the output? This will at least show what aerospace has processed as usable workspaces from your config file.

`aerospace list-workspaces --all`

You should be able to remove default workspaces (for example a-z) by commenting out the "alt-1 = 'workspace 1'" lines in your aerospace.toml (you may also need to comment out the "move-node-to-workspace" lines as well). I've disabled all of the letter workspaces in my config, and now all that show up automatically are the numbered workspaces (which is what i wanted).

Can you post what you have configured?

**Comment by xbunax** [comment]
> Can you run the command below in a terminal and post the output? This will at least show what aerospace has processed as usable workspaces from your config file.
> 
> `aerospace list-workspaces --all`
> 
> You should be able to remove default workspaces (for example a-z) by commenting out the "alt-1 = 'workspace 1'" lines in your aerospace.toml (you may also need to comment out the "move-node-to-workspace" lines as well). I've disabled all of the letter workspaces in my config, and now all that show up automatically are the numbered workspaces (which is what i wanted).
> 
> Can you post what you have configured?

I have only set the workspace 1~ 10 in configure, however aerospace still have other workspace
```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/414230eb-7b55-462d-83e6-ca1b732f2909">
