### ISSUE TITLE
Suggestion: Include QWERTZ Layout for EU Users

### ISSUE THREAD

**Issue by FaskyCode** [nikitabobko/AeroSpace#546]
Just ignore this issue... I found a workaround sorry for the disturbance...

Hy I would highly appreciate if the QWERTZ Layout gets implemented into Aerospace.
I love the tool and use it every day but because I am from Germany and use the QWERTZ layout I can't type things like the "[" , "]"  because it needs the alt combination which is not recognized while using Aerospace.

**Comment by dschense** [comment]
how do you use the german layout with this?

**Comment by Speed1** [comment]
I’m also interested in the workaround :)

**Comment by janpfischer** [comment]
Anyone found a solution? For me aerospace is quite unusable with QERTZ.

**Comment by Speed1** [comment]
I found 2 ways to use aerospace with a german QWERTZ layout:
- You can use a tool like Karabiner to map for example the left alt key or capslock to a so called Hyperkey that combines Control+Option+Command and change the config of aerospace (replace "alt" with "alt-cmd-ctrl") - actual solution
- remove all workspace key combinations that you need for the special characters. In my case I only used numeric workspace 1,2,3,4  and the rest I put on letters (excluding L as needed for @, N as needed for ~) - former solution

**Comment by janpfischer** [comment]
Thanks, @Speed1, great hint. I am using Karabiner-Elements now to map CAPS to Hyperkey. 
FTR if someone stumbles across this. I was able to configure the CAPS key to behave like normal if pressed alone and as Hyper if not alone: 
```
{
    "manipulators": [
        {
            "description": "Change caps_lock to command+control+option.",
            "from": {
                "key_code": "caps_lock",
                "modifiers": { "optional": ["any"] }
            },
            "to": [
                {
                    "key_code": "left_command",
                    "modifiers": ["left_control", "left_alt"]
                }
            ],
            "to_if_alone": [
                {
                    "hold_down_milliseconds": 100,
                    "key_code": "caps_lock"
                },
                { "key_code": "vk_none" }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by hettiger** [comment]
Why close this though? It would still be much better if there was qwertz support without workarounds / hacks with additional apps?

**Comment by itsamemarkus** [comment]
this made me not use AeroSpace :( Just as a feedback. Out of the box even some of the most important command for initial testing of AeroSpace don't work without remapping on most EU layout.

I really hope the "closed as not panned" changes one day

**Comment by itsamemarkus** [comment]
Maybe something useful after my last salty comment. If you're on a German keyboard with the default config you can use the keys in the comment for the specific function to work:

```bash
    alt-shift-semicolon = 'mode service' # German equivalent: alt+shift+ö

    alt-minus = 'resize smart -50' # German equivalent: alt + ? 
    alt-equal = 'resize smart +50' # German equivalent: alt + ´

    alt-slash = 'layout tiles horizontal vertical' # German equivalent: alt + -
```

**Comment by leonlatsch** [comment]
And here I end up.

I love aerospace but this makes it quite unusable. For the German layout you need the option to for typing characters like: 

{}, ~, |, etc... (had to disable aerospace for typing these out, because I was going insane)

I really want to use it, but there should be an option to change the option->alt mapping to any other key (fn?)

**Comment by saesch20** [comment]
Would love to see this too! Workarounds are okay but not the real deal 🙂
