### ISSUE TITLE
Apps spawning in native macos workspaces

### ISSUE THREAD

**Issue by H0fes** [nikitabobko/AeroSpace#551]
First of all thank you for this great project and the approach to completly ditch the macos workspaces 👍

Since mid of august i am playing around with aerospace. My workflow for work is based on using Microsoft Remote Desktop, or now called "Windows App". I am using 3 Monitors and the RDP client will open 3 Monitors, but in macos workspaces.

``` 
~ ❯ aerospace list-windows --all
4983 | Firefox                          | New Issue · nikitabobko/AeroSpace
3760 | Microsoft Teams (work or school) | Activity | Microsoft Teams
6455 | WezTerm                          | zsh
5044 | Windows App                      | 192.168.31.125
4325 | Windows App                      | Devices
```

Windows App | Devices is the control center where i can connect to my windows machine
Windows App | 192.xxxx is the connection itself. When focusing on that, all displays will appear.
My goal is to have 3 different windows which i can focus.

This issue cant be fixed by making aerospace changes, but maybe someone else has the same problem using different apps which creates native macos workspaces?

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - app opening in native macos workspace

- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - displays have separate spaces
  - focus native

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by ParisTheProgrammer** [comment]
So i actually use the new Windows App as well (horrible name but then again Microsoft always had a knack for naming things) and i don't have any issues using it with aerospace. Are you using the "Devices" tab or are those "Apps" connections that your having an issue with?

![CleanShot 2024-10-03 at 08 10 02](https://github.com/user-attachments/assets/350426e9-5b6d-43f9-a150-a55c4cae365b)

**Comment by H0fes** [comment]
- I am using the Devices tab. I also configured the connection to use all monitors. Therefore in every monitor a new fullscreen window will spawn in the native macos workspace... It was pretty good using yabai. I had 3 workspaces on every monitor. When i connected to a windows machine each monitor had 4 workspaces.

**Comment by ParisTheProgrammer** [comment]
I assumed that might be your use case, so thanks for sharing that info. I use the devices tab as well, but I'm purposefully not using the fullscreen / all monitors option and I'm able to cycle through multiple RDP connections using the accordion layout. I chose to sacrifice the "immersive" full-screen experience for easier rotation through multiple connections.

I'm reading over your initial issue, and you nailed it by saying that this is not something that an aerospace configuration can fix (as MacOS implements it's own native space for fullscreen apps) so what is it that you'd like to see happen?

**Comment by H0fes** [comment]
I would totally sacrifice the fullscreen feature if there where an option to spawn 3 or 2 indipendent windows. Maybe theres another application which fit this usecase.

**Comment by ParisTheProgrammer** [comment]
If you uncheck "Use all monitors" and also "Start session in full screen", you will get independent RDP connection windows that will tile automatically. I usually leave my Windows App on workspace 6, and I use the horizontal accordion layout, which then let's me cycle between all current RDP connections. I think this would solve your use case unless I'm missing something

![CleanShot 2024-10-03 at 15 32 34](https://github.com/user-attachments/assets/fd3c3d11-2a11-4710-a6a9-10bf0a1c61c7)

**Comment by H0fes** [comment]
Thank you for sharing your approach! I really appreciate it. Thats what i want, but the only downside of this is, that i cant spawn two windows. I only get one. And i cant tick "use all monitors" without enabling "start session in full screen".

**Comment by ParisTheProgrammer** [comment]
You are correct, each RDP window will be limited to 1 instance. Unfortunately, this isn't something Aerospace can solve, that's something that the RDP program would have to allow (I'm not sure I've seen an RDP application that does this though).

**Comment by H0fes** [comment]
Thats true, aerospace is not the problem here. I will adapt my workflow to only use one window RDP session.
