### ISSUE TITLE
Aerospace stops controlling option binding when used with default macOS Terminal

### ISSUE THREAD

**Issue by nweinberg-via** [nikitabobko/AeroSpace#555]
The issue occurs when you have the default mac terminal app open and try and move to another aerospace workspace with 'alt-{workspace-key}' eg 'alt-1'. The terminal app ignores aerospaces shortcut and simply inputs '¡'. This is fine on its own, as you can simply exit out of terminal with the Aerospace menu icon (by moving to another workspace), and Aerospace continues to work fine if you do that. 

However, if you stop the terminal, it breaks the aerospace keybindings in all windows/workspaces. After closing the terminal app, alt+{key} simply enters the alternative version of that key or does the associated default macOS shortcut based on the key combo. The only way I have found to rectify this state is to first disable aerosapce, then reset my keyboard in System Setting -> Keyboard -> Input Sources -> Edit and changing to another keyboard then back to the default then re-enabling aerospace. This happens with my config and the default config, but doesn't happen with terminal emulators (Iterm is fine).

output of aerospace --version: 
```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by ParisTheProgrammer** [comment]
Can you look and see if 'Secure Keyboard Entry' is checked? If it is, this might be your issue, as I use the default mac terminal every day and I've never experienced that issue.
 
![CleanShot 2024-10-02 at 16 04 17](https://github.com/user-attachments/assets/1b52e060-12c2-4f6d-a541-05c473e41e64)

**Comment by nweinberg-via** [comment]
It is, and I can't disable it (every time I click it it gets re-enabled) I think because my laptop is managed by my organization. Not sure why it would only cause problems in other apps once terminal is closed though...

**Comment by ParisTheProgrammer** [comment]
I also recommend Wezterm if you're comfortable with the terminal's configuration being 100% text based (config file). I use it cross-platform between linux, mac, and windows, config is the same between each, and it hasn't let me down yet! (Not to mention Wez seems like a cool dude).

If you'd rather change terminal settings in a gui, iTerm2 is a solid option as jakenvac said

**Comment by nweinberg-via** [comment]
Yeah I already actually use Iterm, so it wasn't a problem for me, but I was showing my friend Aerospace and he was having this issue. I just reported this in case it was a bug that needed to be fixed, but it seems like more of an issue on his end. Thank you! Marking this as closed.

**Comment by nellinux** [comment]
I have the same problem with kitty terminal.  Any suggestions?

**Comment by jakenvac** [comment]
Does Kitty support secure input? If not, it's probably not the same issue

**Comment by gislik** [comment]
> I have the same problem with kitty terminal with Sequoia; no problem with previous osx releases.

Same issue here. AeroSpace would supersede Kitty when it came to option-movements but now Kitty captures the key combo and I'm stuck in that workspace.

**Comment by gislik** [comment]
Turned out to be a Secure Keyboard Entry issue.

Unchecking fixed the issue for me.

<img width="251" alt="image" src="https://github.com/user-attachments/assets/b1c17bcc-a7e3-414f-be59-988aff8536fa" />
