### ISSUE TITLE
Is it possible to add keyboard shortcut to launch kitty ?

### ISSUE THREAD

**Issue by zobi** [nikitabobko/AeroSpace#557]
Hello with yabai combinate with shkd, I had the possibility to launch my term (kitty) with keyboard shortcut (cmd - return)
Is it possible to make the same with aerospace ? 
thanks a lot

**Comment by luathn** [comment]
Try this: `alt-enter = 'exec-and-forget open -na Kitty'`

**Comment by zobi** [comment]
thanks for your reply, unfortunatly it did nothing i try with "Kitty" or "kitty" with or without "open -na" and for sure reload the config but nothing append.
Maybe because i've an azerty french keyboard ?

**Comment by luathn** [comment]
@zobi Oh, It's weird. I just test and it works for me.

**Comment by zobi** [comment]
oh my god, it work's i'm so stupid ...
You need to put this line in good section [mode.main.binding] ! And when it's in good section, it work's ;) Thanks a lot for your help
