### ISSUE TITLE
fail to configure workspace - with alt-minus, move node to workspace - with alt-shift-minus

### ISSUE THREAD

**Issue by potatochick2020** [nikitabobko/AeroSpace#572]
I try to configure extra workspace on - = [ ] , 3 of them work, minus does not work.
Below config will pop error, after comment out the 2 line related to - it will work again.

![CleanShot 2024-10-08 at 10 22 43](https://github.com/user-attachments/assets/8a3a453d-f613-4cb0-8087-0e1ade292f62)

```
Failed to parse /Users/myuser/.config/aerospace/aerospace.toml

mode.main.binding.alt-minus: ERROR: Unknown flag '-'
ERROR: Argument '(<workspace-name>|next|prev)' is mandatory

mode.main.binding.alt-shift-minus: ERROR: Unknown flag '-'
ERROR: Argument '(<workspace-name>|next|prev)' is mandatory
```

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - minus
  - workspace minus
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands).

**Comment by nikitabobko** [comment]
Yes, it's by design. Minus is a reserved workspace name, please use different character
