### ISSUE TITLE
It is not possible to distinguish between left-alt and right-alt modifiers

### ISSUE THREAD

**Issue by matt-maguire** [nikitabobko/AeroSpace#579]
When specifying the "alt" modifier, this causes aerospace to react regardless of whether the left alt or right alt key is used.

This is an issue for non-english speakers, who often use rhe right alt key (aka AltGr key) to compose "special" letters )such as those with diacritics), eg. àéíûĉŝĵĝßŭçüäö . An example of such a keyboard mapping in macOS is the "ABC - Extended" keyboard.

In aerospace config, it should be possible to specify a modifier (eg. lalt) that corresponds to only the left alt key, so that the right alt key can be used to type these special characters without triggering aerospace actions. 

## Checklist

- [X] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - right alt

- [X] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [X] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - right
  - alt

```
 $ aerospace --version
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by matt-maguire** [comment]
duplicate of nikitabobko/AeroSpace#28

resolved by using Karabiner Elements to map left-option key to "Meh" key.

**Comment by tim-hilde** [comment]
Would like to reopen this as I have a different key mapped to "meh", but still have the issue described in the original issue

**Comment by tokisuno** [comment]
sorry for necro but i have the same issue. cannot type the polish letter ł or anything that would require alt + hjkl keys

**Comment by gpoleze** [comment]
I have the same issue of typing accents in Portuguese on the macos as it requires a combination of left-alt plus other keys (i.e: e, i, c and n).

**Comment by notflip** [comment]
It would be so good to be able to use right-alt please (Karabiner is not a solution because then you lose left+right alt. I need right-alt for some specific software I'm using. Thank you.
