### ISSUE TITLE
Unbinding default keys requires a restart, reload does not work

### ISSUE THREAD

**Issue by isker** [nikitabobko/AeroSpace#58]
Hi.  The [default bindings](https://nikitabobko.github.io/AeroSpace/config-examples.html#default-config) bind `alt-[a-z]` and I'd like those to become unbound so that they're passed through to the actual software I'm using.

So, I created an .aerospace.toml file that redefines all of `[mode.main.binding]` without these bindings.  I reloaded the config, and this resulted in the A-Z workspaces disappearing from the dropdown list, but hitting e.g. `alt-b` in fact still switched to workspace B, which then appeared in the list.  Switching back to workspace 0 made it disappear from the list.

Restarting aerospace entirely got the desired effect, where aerospace is not intercepting `alt-[a-z]`.

**Comment by isker** [comment]
I couldn't find anything in the documentation that states how to undo default bindings in general - I was not sure that my `[mode.main.binding]`s would not be merged with the default ones.  Due to this bug, I was initially convinced that there was such a merge and that it was not possible to unbind any of the defaults.

So, documenting how this works might be helpful to others.

**Comment by isker** [comment]
Thanks!

**Comment by nikitabobko** [comment]
Released in 0.7.0-Beta
