### ISSUE TITLE
Callback for Entering / Leaving Floating Layout

### ISSUE THREAD

**Issue by chasingtheflow** [nikitabobko/AeroSpace#580]
Is there a callback of some kind I can use to identify when a window begins or stops floating? What I'm trying to do is build upon the "Goodies" example that enables JankyBorders and give floating windows a distinct border so they're easier to see.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - Float layout
  - Float callback
  - ...
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - layout
  - float
  - ...

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment]
Callback for entering / leaving floating layout is too much specific.

I don't mind having a `on-workspace-redraw` callback #316 Inside the `on-workspace-redraw` you can check if the focused window is floating
