### ISSUE TITLE
0.15.0 regression: `list-workspaces --focused` issue show multiple monitors and not just one

### ISSUE THREAD

**Issue by zobi** [nikitabobko/AeroSpace#582]
Command `aerospace list-workspaces --focused` : show multiple monitor and not only one with new 0.15.0 beta (it work's with old version)

`❯ aerospace list-workspaces --focused
1
2
3
4
5
6
❯ aerospace --version
aerospace CLI client version: 0.15.0-Beta e3936aac3b39f7fd242d89ebbda7f6691f5bbdf8
AeroSpace.app server version: 0.15.0-Beta e3936aac3b39f7fd242d89ebbda7f6691f5bbdf8`

**Comment by nikitabobko** [comment]
Fixed in 0.15.1
