### ISSUE TITLE
Focus <direction> no longer wraps after upgrading to 0.15.x

### ISSUE THREAD

**Issue by antonk52** [nikitabobko/AeroSpace#593]
After upgrading to 0.15.2 the focus window no longer wraps at workspace boundary

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - Focus wrap
  - Manually go through recent issues
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - focus

## Repro steps

- `aerospace layout v_accordion`
- have more than 1 window
- use keymap bound do `focus down` multiple times
- **expected** focus moves from the bottom most window to the top most window
- **actual** focus is stuck at the bottom most window

I have verified that the expected behaviour works in 0.14.2 and stopped working after updating to 0.15.2

**Comment by nikitabobko** [comment]
Yes, this is a breaking change mentioned in the release notes https://github.com/nikitabobko/AeroSpace/releases/tag/v0.15.0-Beta

You can return the wrapping by explicitly passing `--boundaries-action wrap-around-the-workspace` to the `focus` command

**Comment by antonk52** [comment]
My bad, this is a documented behaviour and the only breaking change in 0.15 changelog. Sorry about the issue
