### ISSUE TITLE
is possible disable the tiles?

### ISSUE THREAD

**Issue by m1guer** [nikitabobko/AeroSpace#595]
**YOUR TEXT**
is possible disable the tiles and use just the workspaces?

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - workspaces only
  - disable tiles
- [X] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [X] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - dvorak
  - monitor
  - ...

```
aerospace CLI client version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
AeroSpace.app server version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
```

**Comment by ParisTheProgrammer** [comment]
So from your question I can understand that you would like to avoid using the "Tiling" layout for windows, which is definitely doable. The only 2 remaining options are the "Accordion" layout or using floating windows. What is it, that you're looking to do?

https://nikitabobko.github.io/AeroSpace/guide#layouts

**Comment by nikitabobko** [comment]
You can do this in your config:

```toml
[[on-window-detected]]
run = 'layout floating'
```

It will float all the windows by default, effectively, leaving you only with the fast workspaces

**Comment by m1guer** [comment]
thx

**Comment by jeredwong** [comment]
Is it possible to switch focus between floating windows only (in the event all windows are floating windows)? 
Understand that it is possible to do so between floating windows and windows part of tiling tree.
