### ISSUE TITLE
Can accordion padding be resizable with the resize command?

### ISSUE THREAD

**Issue by bchang** [nikitabobko/AeroSpace#600]
Following on my request for accordion-padding to allow a percentage of the screen size, it would go along way if I can simply dynamically change the padding.

It seems the `resize` command only works in the `tiles` layout and has no effect in `accordion` - seems it would be a very elegant solution if `resize` could function in this context by modifying the accordion-padding value?

**Comment by nikitabobko** [comment]
Resize command is not ignored inside `accordion`

Consider the following examples:
```toml
h_tiles // (1)
  window1
  v_tiles // (2)
    window2
    h_accordion
      window3
      window4
```

An attempt to resize horizontally window3 will resize (2)
