### ISSUE TITLE
Bug: When using 'focus-left' and 'focus-right' on a secondary monitor, focus regularly gets sent back to primary monitor undesirably

### ISSUE THREAD

**Issue by mackenzie-3spread** [nikitabobko/AeroSpace#613]
Primary Monitor (Workspace 0): I have one application open, taking up the full screen.
    Secondary Monitor (Workspace 1): I have multiple applications stacked horizontally.

When my focus is on Workspace 1 (Secondary Monitor) and I try to navigate between applications using the 'focus-left' and 'focus-right' keybinds, my focus unexpectedly shifts back to the Primary Monitor (Workspace 0).

This issue doesn’t happen every time—I can sometimes navigate a few times successfully—but it almost always redirects to the Primary Monitor within the first few attempts.

I’m loving the app! It’s made navigating macOS feel intuitive, and I just wish I’d tried it sooner. This minor issue is the only thing holding back my workflow.

```
aerospace CLI client version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
AeroSpace.app server version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
```

**Comment by mackenzie-3spread** [comment]
This appears to be resolved by disabling "displays have separate spaces".

**Comment by Melkeydev** [comment]
> displays have separate spaces

Where did you disable this?
