### ISSUE TITLE
0.15.2 - Floating windows appear on corner and are stuck to workspace when hidden instead of closing the window

### ISSUE THREAD

**Issue by jmml97** [nikitabobko/AeroSpace#641]
**Describe the bug**

I have several applications set to toggle visibility on a certain key combination using Raycast. For example, alt-T shows Telegram. 

I have configured Aerospace so that the windows of those apps always float.

On version 0.14.2 when I trigger the shortcut to show any of these apps:

- they show where I last placed them on the screen
- they show in the current workspace

On version 0.15.2, when I do the same:

- they show on the bottom left corner of the screen
- my workspace switches to the workpace they were first launched, instead of floating on the current workspace (this does not happen if I close the window instead of hiding it with the shortcut)

I would like to preserve the behaviour Aerospace has on version 0.14.2, since it makes more sense for the use I give floating windows: they can be summoned on any workspace and appear where you place them.

**Related issues you could find**

I have not found any related issue.

**Comment by nikitabobko** [comment]
Apparently, you use "hide application" shortcut `cmd-h` and refer to this issue #425 Yes, it's planned change.

If you want to be able to keep windows "attached" to the monitor while switching workspaces, please upvote/follow #2 

> they show on the bottom left corner of the screen

I confirm this is a bug and extracted it to a separate issue: #642

**Comment by jmml97** [comment]
Thanks! Will follow #2.
