### ISSUE TITLE
Native Window close (cmd + w) leads to an unfocused window

### ISSUE THREAD

**Issue by Adriel-M** [nikitabobko/AeroSpace#65]
On a workspace with 2 windows, doing `cmd + w` on one of the windows doesn't result in focusing on the remaining window. So far, I can only reproduce this on [cyberduck](https://cyberduck.io/).

I don't have `cmd + w` bound to anything on aerospace but `option + w` (`alt-w` on the config file) is set to `'close'`.

I've attached a video to showcase it. The first instance of closing cyberduck is using `cmd + w` where it doesn't focus on the other window while the second instance is using the aerospace `close` shortcut.

https://github.com/nikitabobko/AeroSpace/assets/20115135/0274432c-99f4-4087-b6c2-6e31dc729c1d

**Comment by Adriel-M** [comment]
It does look like it happens on yabai as well but I've gotten around that by using: https://github.com/koekeishiya/yabai/issues/485#issuecomment-617953545

**Comment by nikitabobko** [comment]
Released in 0.8.0-Beta
