### ISSUE TITLE
Workspaces get moved and are not reachable when adding & removing monitors

### ISSUE THREAD

**Issue by volker-fr** [nikitabobko/AeroSpace#651]
**Describe the bug**

**Bug summary:**

When adding/removing monitors
1. workspaces get moved between monitors
2. workspaces beyond the configured workspace numbers are created. No shortcut to these workspaces exist

**How to reproduce**

Starting point:
0. AeroSpace v0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
1. monitor1: workspace 10
3. monitor2: workspace 8
4. laptop lid: closed
5. no other workspaces exists
6. Configuration parts:
```
...
[workspace-to-monitor-force-assignment]
8 = 'Monitor2'

[mode.main.binding]
alt-0 = 'workspace 10'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
```

7. Open the Macbook lid

Results in:
monitor1: workspace 11 (not reachable via shortcut)
monitor2: workspace 8
laptop screen: workspace 10 (moved from monitor1)

Issues:
1. workspace 10 should have stayed on monitor1 and not moved
2. workspace 11 can't be reached via keybinding, the other workspaces (1-7 and 9) are unassigned.

Same setting & steps above:
8. I close the laptop lid

Result:
1. monitor1: keeps workspace 11
2. monitor2: workspace 8 & 10. workspace 10 is the active workspace. Before workspace 8 was active and should have stayed active

Continuing with above flow:
9. opening macbook display

Result:
1. monitor1: gets workspace 10 (that was previously on monitor2)
2. monitor2: gets workspace 8 (that is pinned to this monitor)
3. laptop display: gets workspace 11 (that was on monitor1 before)

**Related issues you could find**

N/A

**Comment by Melkeydev** [comment]
I am also facing this issue.
I have two monitors, and when I shift focus between one node to the other in a different monitor, I can't go back

**Comment by nikitabobko** [comment]
> workspace 10 should have stayed on monitor1 and not moved

You Macbook built-in monitor is configured as main monitor in system settings, that's why it happens

> workspaces beyond the configured workspace numbers are created

Works as expected. Please search for "phantom workspaces" in the issue tracker, it was answered numerous times
