### ISSUE TITLE
Informational: Endpoint Detection and Response Alert

### ISSUE THREAD

**Issue by tylerwhardy** [nikitabobko/AeroSpace#664]
**Describe the bug**
EDR alerts on this installation with the following detection telemetry:
Initiated By: Agent Policy
Engine: Behavioral AI
Detection type: Dynamic
Classification: Malware

Path: /Applications/AeroSpace.app/Contents/MacOS/AeroSpace
Command Line Arguments: N/A
Publisher Name: N/A
Originating Process: launchd
SHA1: 864e916bb80aa207626af7a7d6e140c3568c4e6f

Sandbox analysis describes the following:
- Process added a suspicious property list to achieve persistency; 
- Process achieved persistency through launchd job

This file was NOT detected on VirusTotal:
https://www.virustotal.com/gui/file/883076ecdeddc5497815d8d159c0bc7cc22845dfa831f9d56ef5a47663480334

This is provided as information to the developer and to assist SOC analysts with triaging endpoint detection and response results.

**Comment by nikitabobko** [comment]
spam

**Comment by tylerwhardy** [comment]
@nikitabobko Just wanted you to know that AV was blocking your software.
