### ISSUE TITLE
Split screen bug in Numbers, Keyshot, Pages apps

### ISSUE THREAD

**Issue by blindfox0** [nikitabobko/AeroSpace#668]
In the case of Apple applications - Pages, Numbers, Keyshot - opening new documents in the tabs (not new windows) is treated as opening new windows. For example - on an empty desktop, opening a sheet in Numbers will correctly fill the entire screen. But opening a new document in a new tab will cause the application to take up only half of the screen.

Here is screen recording with the bug:

https://github.com/user-attachments/assets/152cc003-86d0-461e-88ca-8bf1d2a42fc3

**Comment by renke** [comment]
See https://github.com/nikitabobko/AeroSpace/issues/68
