### ISSUE TITLE
Allow using macOS Spaces instead of Aerospace Workspaces

### ISSUE THREAD

**Issue by Kha1r0** [nikitabobko/AeroSpace#676]
At the moment, Aerospace Workspaces replace macOS Spaces.
My Problem is that while they are better in some ways, they are inferior in others as i've explained [here](https://github.com/nikitabobko/AeroSpace/discussions/645).
I like the window tiling functionality, but I'd like to keep using macOS Spaces for virtual Desktop Management instead of Aerospace's Workspaces.

**Comment by nikitabobko** [comment]
Please search for duplicates before posting

**Comment by Kha1r0** [comment]
...where

**Comment by Kha1r0** [comment]
wheres the original post i looked through them

**Comment by Kha1r0** [comment]
great.
