### ISSUE TITLE
Double clicking the window title should enter fullscreen

### ISSUE THREAD

**Issue by thalesmello** [nikitabobko/AeroSpace#686]
**Describe the bug**
In macOS, double click a window title will usually maximize the window.
When you click the window title with Aerospace running, it flickers the screen:
- macOS resizes the window to span the whole area of the display
- Aerospace resizes it back to it's original size

I would expect to see the window enter fullscreen, than could then be toggled off via command or by double clicking the window again.

As a workaround, I configured my BetterTouchTool to execute the relevant aerospace command when the window title is double clicked. It still flickers, but it does the expected behavior.

**Related issues you could find**
Please make sure to search for duplicates.
If you couldn't find the duplicates, linking related issues is helpful anyway.

**Comment by Etheryte** [comment]
Fyi, you can disable the native double click behavior by going System Settings → Desktop & Dock → Double-click on a window's title bar to → Do nothing.

**Comment by thalesmello** [comment]
@Etheryte Thank you for sharing, that works really well with my Better Touch Tool

But my point is that, just like dragging the border of a window will resize the size of the panes in Aerospace, it would also make sense that double clicking a window to maximize it would make sense gorAerospace enter a "Fullscreen" state

**Comment by nikitabobko** [comment]
It is not possible to make it work the way you describe it
