### ISSUE TITLE
Fibonacci style tiling

### ISSUE THREAD

**Issue by seagoj** [nikitabobko/AeroSpace#696]
Aerospace is a fantastic project and *nearly* everything I want. I was curious if implementing Fibonacci style tiling was in scope or if manually moving tiles is core to the project?

Thanks for all the work!

**Comment by seagoj** [comment]
@nikitabobko could you please point out the other issue? I can't seem to find it. Thanks!

**Comment by pszypowicz** [comment]
For anyone landing here looking for the original: this was closed as a duplicate of #260 (*Feature proposal: More sophisticated per-workspace normalizations to replicate dynamic twm*), which is the umbrella issue tracking dynamic tiling layouts like BSP, Amethyst-style `tall`/`wide`, and similar. Fibonacci/spiral tiling fits in that family - see also #384, which was explicitly marked as a duplicate of #260.
