### ISSUE TITLE
Support fullscreen command

### ISSUE THREAD

**Issue by nikitabobko** [nikitabobko/AeroSpace#7]
https://i3wm.org/docs/userguide.html#_toggling_fullscreen_mode_for_a_window

Status: use cases collection. Please post your use cases

**Comment by axelfahy** [comment]
I use it a lot to focus on a single app in fullscreen, do stuff, and then go back to my tilings. An alternative is stacking, but then you have to find the window you want in all the stacked windows; so it's easier to go fullscreen on the window having the focus.

**Comment by vitor-alves** [comment]
I use fullscreen a ton. It's often easier to use fullscreen than to changed to stacked/tabbed modes or move the app to an empty workspace. 
To me this feature is high priority, because it's an important part of my workflow.

**Comment by nikitabobko** [comment]
Fixed in 0.3.0-Beta
