### ISSUE TITLE
Feature : Switch back and forth between the previously focused workspace when focusing the current workspace.

### ISSUE THREAD

**Issue by AmineDjeghri** [nikitabobko/AeroSpace#709]
Switch back and forth between the previously focused workspace when focusing the current workspace. instead of using : 
` alt-tab = 'workspace-back-and-forth'`

for example : 
If i am on workspace 1, i select alt+3 for workspace 3, if i click again on alt+3, it will take me back to the previous workspace '1'
`  toggle_workspace_on_refocus: true`

**Comment by nikitabobko** [comment]
It is already possible. Please read the documentation

**Comment by AmineDjeghri** [comment]
Thank you for your response. Can you please send me the link to where i can find this ?
i finished setting up aerospace, and it's the only thing that i'm missing in my config. I didn't find it when looking in the docs

**Comment by Atrate** [comment]
I'd like to ask for this to be implemented for the `move-node-to-workspace` command as well. `i3` has that functionality.
