### ISSUE TITLE
Resize functionality 

### ISSUE THREAD

**Issue by yuxb2** [nikitabobko/AeroSpace#714]
Hi, would it be possible to add the **resize** option in the [on-window-detected] ? I would love to use it to set certain apps that are in floating to a certain size on my screen. 
A simple option to center elements would also be great. I'm using Hammerspoon right now to re-center all the floating windows at the moment, but it would be much easier if you could add a **'center-window'** option, furthermore than the **resize** option. 
Thanks a lot, keep up the great work!

**Comment by Jaaco** [comment]
In case anybody else also finds this issue first and doesn't find what it is a duplicate of:

**Resize floating windows** PR:
https://github.com/nikitabobko/AeroSpace/pull/1156

**Center floating windows** issue:
https://github.com/nikitabobko/AeroSpace/issues/494
