### ISSUE TITLE
Ideas to improve movement

### ISSUE THREAD

**Issue by diocletiann** [nikitabobko/AeroSpace#73]
I'm trying to have two stacked columns, and automatically nest new windows in a vertical accordion. The best workflow I've figured out is:
```
default-root-container-layout = 'tiles'
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true
```

1. open second window (column 2) - tiles to the right
2. open third window - tiles to the right
3. `join-with` third window into second window - creates vertical tiles container
4. change layout of container to accordion
5. repeat for first window (column 1)

Is it possible to automate some of this? Thanks for the amazing app!

**Comment by diocletiann** [comment]
I found a faster way:
- bind ['split vertical', 'layout v_accordion']
- run on root container windows (desired stacked columns)

It seems if `on-window-detected` had a "root node leaf" condition, this could be done automatically (once more `run` commands are supported).

**Comment by diocletiann** [comment]
Another option could be to use `enable-normalization-flatten-containers = false` with `move-through` and allow for a callback if it nests to run `'layout v_accordion']`.

**Comment by diocletiann** [comment]
Another option would be to provide for a layout change after a successful `join-with` to toggle `v_accordion`. That would allow use of `enable-normalization-flatten-containers = true`.

**Comment by nikitabobko** [comment]
Closing this issue in favor of #260
