### ISSUE TITLE
Accordion layout despite no hotkey set for it and default-root-container-layout = 'tiles'

### ISSUE THREAD

**Issue by mrkskk** [nikitabobko/AeroSpace#734]
I don't use Accordion layout. I don't have a hotkey to toggle it. 

I default to: 
```
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

```

Still sometimes Aerospace default to accordion layout for all my windows and the following hotkeys do not work to enter tile mode: 

`ctrl-alt-cmd-comma= 'layout floating tiling'` 
will toggle floating and back to accordion
`ctrl-alt-cmd-semicolon =  'balance-sizes' ` will do nothing 

Only fix it going to the terminal and entering `aerospace layout tiles`

What am I'm missing?

**Comment by denysav** [comment]
Same issues as @alextremblay. 

I have the following in my config:
```
 default-root-container-layout = 'accordion'
 default-root-container-layout = 'accordion'
```

Some workspaces are in the vertical accordion layout as expected, but some are always in vertical tiles.

**Comment by nikitabobko** [comment]
https://github.com/nikitabobko/AeroSpace/issues/775#issuecomment-2516931688

#905
