### ISSUE TITLE
`gaps.outer.top` vs the notch

### ISSUE THREAD

**Issue by johnallen3d** [nikitabobko/AeroSpace#74]
Long, _long_ time Yabai user here trying out AeroSpace. After about one day I'm pretty sure I'm a convert. Brilliant work @nikitabobko!

That said, I have a question regarding `gaps.outer.top`. It seems that on the display with a "notch", the padding is in relation to the bottom of the notch. Whereas displays without a notch, the padding is in relation to the actual top of the display. This makes the gap between the top of a window and my bar (SketchyBar) drastically larger/smaller on each display. Is there any way to account for this (eg. display specific setting)?

Maybe a screenshot will help illustrate better than my description. The left side is my MacBook Pro and the right is my external.

![CleanShot 2023-12-29 at 18 24 53@2x](https://github.com/nikitabobko/AeroSpace/assets/184915/1306976a-1a15-44ac-8e5f-38318cc569a4)

**Comment by nikitabobko** [comment]
> Is there any way to account for this (eg. display specific setting)?

Now it's not possible. But I agree that it'd be nice to have display specific settings for the gaps

**Comment by johnallen3d** [comment]
Ok, I'm glad to know there wasn't something I was missing. 

I will say, for my use case, an option to disregard the notch would also suffice. I'd take a crack at a PR but I have _zero_ experience with Swift to date.

**Comment by wojciech-kulik** [comment]
Alternatively, it would be nice to be able to change gaps using hotkey. It would be useful when I'm using 2 displays and I switch to 1.

**Comment by nikitabobko** [comment]
> Alternatively, it would be nice to be able to change gaps using hotkey. It would be useful when I'm using 2 displays and I switch to 1.

What is the use case for workspace-specific gaps?

In my head, there are two use cases for gaps:
1. Aesthetics. In this case, users use the same gaps on all workspaces
2. Practical. To make it easier to distinguish between windows

**Comment by wojciech-kulik** [comment]
@nikitabobko to solve the problem mentioned in this issue. When I work on two displays I don't mind much that the top gap is bigger on my side (built-in)  display, but when I switch to mac only then the gap is annoying and takes to much space, so I need to adjust my config to reduce it.

As you said, right now it's not possible to fix this bug, so it could work as a workaround temporarily. If the bug is fixed, then changing gaps dynamically is not needed either.

**Comment by wojciech-kulik** [comment]
@johnallen3d I fixed it here: #98

**Comment by wojciech-kulik** [comment]
@johnallen3d I fixed it here: https://github.com/wojciech-kulik/AeroSpace/commit/51a2ca70021ef1f9b969161932d5240c3e504fbb 

If you can build the project manually, you can try my fork before it's properly fixed here :). 
I'm using this solution with sketchybar and it works well :).

**Comment by nikitabobko** [comment]
Per-monitor gaps are released in 0.8.0-Beta

**Comment by johnallen3d** [comment]
Work perfectly, thanks @wojciech-kulik and @nikitabobko!
