### ISSUE TITLE
Windows of newly launched apps by exec-and-forget are not focused when kitty is currently focused

### ISSUE THREAD

**Issue by sschuldenzucker** [nikitabobko/AeroSpace#754]
**Describe the bug**

A bit of a weirdly specific one.

For testing , consider the following config:

```toml
[mode.main.binding]
alt-shift-m = 'exec-and-forget open -a Terminal'
```

Trigger this from a situation where the Terminal app is not running (as in, quit, no windows visible and app is not running in the background) and you are currently focused on a kitty window.

**Expected behavior:** The app is started, a new window is opened, and the new window is focused.

**Actual behavior:** The app is started, a new window is opened, but the new app's window is *not* focused: the previously-focused kitty window remains focused.

I have no idea why this only happens when a kitty window is currently focused. I see the expected behavior when other apps (e.g., my web browser or slack) have focus. Could kitty have some weird property where it's "greedy" for focus?

If it's relevant, in my setup, kitty is also started by aerospace using the following config:

```toml
alt-shift-enter = 'exec-and-forget cd; /Applications/kitty.app/Contents/MacOS/kitty --single-instance'
```

NB this isn't breaking anything for me right now, I just noticed it while experimenting, but I could imagine some setup where it becomes a blocker.

**Comment by nikitabobko** [comment]
Can't reproduce. 

- Sonoma 14.7 (23H124)
- kitty 0.37.0
- AeroSpace custom build from 0ab5fdea88b0ecde5ce5671a69ae76aea84bd540

I launched kitty with the following command: `/Applications/kitty.app/Contents/MacOS/kitty --single-instance`

I have the following line in my config:
```toml
alt-period = 'exec-and-forget open -n /Applications/Alacritty.app'
```

And Alacritty receives focus as expected if I run it with `alt-period`, even if kitty is focused
