### ISSUE TITLE
Support for Sketchybar Events

### ISSUE THREAD

**Issue by MatthiasGrandl** [nikitabobko/AeroSpace#76]
https://felixkratz.github.io/SketchyBar/config/events#creating-custom-events

Sketchybar uses notifications through `NSDistributedNotificationCenter` to support live updating of items. Would be cool if AeroSpace workspace changes would send such notifications.

**Comment by MatthiasGrandl** [comment]
@nikitabobko I already implemented and tested this. I'll open a PR!

**Comment by nikitabobko** [comment]
A follow-up is to introduce a real `on-workspace-changed` callback #87. Having `NSDistributedNotificationCenter` is nice, but it's Apple proprietary API and other CLI might not be good at integrating with it
