### ISSUE TITLE
Hi, it happened when i was watching video on youtube, it just suddenly crached

### ISSUE THREAD

**Issue by hevzy86** [nikitabobko/AeroSpace#786]
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("hevzy@MacBook-Pro:~/.config/yabai")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'nil', modal: 'Optional("false")', windowId: 'Optional("6881")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000102483648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x00000001023229bc $s9AppBundle8TreeNodeC16unbindFromParentAA11BindingDataVyF + 236
2   AeroSpace                           0x000000010231d1d0 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 136
3   AeroSpace                           0x00000001023079f8 $s9AppBundle9gcWindowsyyF + 500
4   AeroSpace                           0x0000000102302ed4 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 644
5   HIServices                          0x00000001919fda80 _XXMIGPostNotification + 896
6   HIServices                          0x0000000191a2efa0 _XPostNotification + 356
7   HIServices                          0x00000001919de368 mshMIGPerform + 212
8   CoreFoundation                      0x000000018b1422c8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
9   CoreFoundation                      0x000000018b1421e8 __CFRunLoopDoSource1 + 524
10  CoreFoundation                      0x000000018b140b48 __CFRunLoopRun + 2248
11  CoreFoundation                      0x000000018b13fbc4 CFRunLoopRunSpecific + 588
12  HIToolbox                           0x00000001965aff64 RunCurrentEventLoopInMode + 292
13  HIToolbox                           0x00000001965b5d54 ReceiveNextEventCommon + 636
14  HIToolbox                           0x00000001965b5eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
15  AppKit                              0x000000018ec6ba08 _DPSNextEvent + 660
16  AppKit                              0x000000018f5abe0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
17  AppKit                              0x000000018ec5eae0 -[NSApplication run] + 480
18  AppKit                              0x000000018ec35364 NSApplicationMain + 888
19  SwiftUI                             0x00000001b92e4340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
20  SwiftUI                             0x00000001b9754ee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
21  SwiftUI                             0x00000001b9acdf24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
22  AeroSpace                           0x00000001022a53ec main + 36
23  dyld                                0x000000018acd8274 start + 2840

**Comment by logkirk** [comment]
I just got what (I think?) is a similar crash. I'm not sure precisely when the crash happened because of the way the windows were overlayed, but here's what happened.

I copied a huge amount of text from my terminal and attempted to paste it into BBEdit. BBEdit hung, then I tried to switch to switch to another workspace with opt+1. Then, I clicked on another app's window and tried the same command again. Finally, it seemed as if the workspace switch worked, but then I saw the crash message.

I did a search for similar "...is already unbound" issues, and found the following issues that may or may not be related:

* https://github.com/nikitabobko/AeroSpace/issues/771
* https://github.com/nikitabobko/AeroSpace/issues/445

Below is the error. Thanks!

```
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("untitled text 6")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'Optional("_NS:69")', modal: 'Optional("false")', windowId: 'Optional("24131")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x000000010488b648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x000000010472a9bc $s9AppBundle8TreeNodeC16unbindFromParentAA11BindingDataVyF + 236
2   AeroSpace                           0x00000001047251d0 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 136
3   AeroSpace                           0x000000010470f9f8 $s9AppBundle9gcWindowsyyF + 500
4   AeroSpace                           0x000000010470c4d0 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9A41Bundle12activateModeyySSSgFyycfU0_yyXEfU_SSAA13HotkeyBindingVTf1nnnnc_n + 656
5   AeroSpace                           0x000000010491cee0 $s6HotKey0A14KeysControllerC17handleCarbonEventys5Int32Vs13OpaquePointerVSgFZTf4nd_n + 336
6   HIToolbox                           0x00000001a08deb3c _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1256
7   HIToolbox                           0x00000001a08dc894 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 356
8   HIToolbox                           0x00000001a08dc724 SendEventToEventTarget + 40
9   AppKit                              0x00000001998eaa80 -[NSApplication(NSEventRouting) sendEvent:] + 1288
10  AppKit                              0x00000001994f889c -[NSApplication _handleEvent:] + 60
11  AppKit                              0x0000000198f9eb08 -[NSApplication run] + 520
12  AppKit                              0x0000000198f75364 NSApplicationMain + 888
13  SwiftUI                             0x00000001c3625340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
14  SwiftUI                             0x00000001c3a95ee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
15  SwiftUI                             0x00000001c3e0ef24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
16  AeroSpace                           0x00000001046ad3ec main + 36
17  dyld                                0x0000000195018274 start + 2840
```
