### ISSUE TITLE
Firefox isn't effected by aerospce shortcuts

### ISSUE THREAD

**Issue by nailik-1** [nikitabobko/AeroSpace#789]
**Describe the bug**
Firefox window is acting as it were floating, I also can't move it to another workspace with keyboard shortcuts - only the other window in that workspace is moved. I can't fullscreen it with shortcuts, as well as move it to one side of the screen with an other application on the other side - firefox will just float over the other window, which will be fullscreen. It's like firefox isn't recognized as a window by aerospace and therfore nothing effects it.
**Related issues you could find**
Please make sure to search for duplicates.
If you couldn't find the duplicates, linking related issues is helpful anyway.

**Comment by nikitabobko** [comment]
Can't reproduce
