### ISSUE TITLE
Resource usage due to rendering of non-visible workspaces

### ISSUE THREAD

**Issue by lintglitch** [nikitabobko/AeroSpace#790]
**Describe the bug**
In my testing non-visible workspaces have roughly the same performance cost as visible ones, or in other words: non-visible workspaces still seem to have the full rendering cost. I tested by starting graphically intensive processes (tested with video-playing Firefox and VLC) either on a separate non-visible AeroSpace workspace or a separate macOS Space, and then looking at the CPU usage in htop.

The CPU usage is always significantly lower when the GPU heavy application runs in the background of a macOS space instead of a AeroSpace workspace (in my testing as high as 0.2% vs 8%).

Not sure how fixable it is, since it seems macOS rendering optimization might rely heavily on macOS Spaces.

**Related issues you could find**
Related to #128. I tried with the [same GPU stress test](https://www.matthew-x83.com/online/gpu-test.php) they linked and could reproduce my findings above.

**Comment by nikitabobko** [comment]
There is nothing AeroSpace can do about it. It's not a bug

**Comment by KasselMarc** [comment]
I've experienced the same: If you're on a laptop, battery usage matters and for me aerospace has constantly a battery impact of about 80% of the app which I use the most and which has the highest battery impact. This makes it somewhat unsuitable for when working from a laptop (on a desktop pc it doesn't matter of course).

**Comment by NMAC427** [comment]
> There is nothing AeroSpace can do about it, if it's true. It's not a bug

Wouldn't it be possible to hide applications that aren't part of the current workspace? This is how the [FlashSpace](https://github.com/wojciech-kulik/FlashSpace) project manages manages its spaces. While it is only possible to hide applications (and not individual windows), Aerospace could still use this to hide applications that don't have any windows in the current workspace to reduce resource usage.
