### ISSUE TITLE
almost fail every single time wake from sleep

### ISSUE THREAD

**Issue by jeremy0719** [nikitabobko/AeroSpace#811]
Message: Window(title: 'Optional("Daqman-11-21-2024")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'Optional("_NS:154")', modal: 'Optional("false")', windowId: 'Optional("7030")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000100dab648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x0000000100c5b324 $s9AppBundle33restoreClosedWindowsCacheIfNeeded19newlyDetectedWindowSbAA0K0C_tF + 2548
2   AeroSpace                           0x0000000100c48c28 $s9AppBundle9MacWindowC3get3app02axD07startupACSgAA0cA0C_So14AXUIElementRefaSbtFZTf4nnnd_n + 1648
3   AeroSpace                           0x0000000100c44fa0 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlFSaySo14AXUIElementRefaG_9AppBundle6WindowCTg503$s9f55Bundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6h15CGSb_tFAGSgSo14D9RefaXEfU_AI0kF0CSbTf1cn_nTf4ngn_n + 248
4   AeroSpace                           0x0000000100c3d7ac $s9AppBundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6WindowCGSb_tF + 256
5   AeroSpace                           0x0000000100c2d5d0 $s9AppBundle41detectNewWindowsAndAttachThemToWorkspaces33_9D4CAE07A16011BB7304F8F5007BD739LL7startupySb_tF + 384
6   AeroSpace                           0x0000000100c2af30 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 736
7   AeroSpace                           0x0000000100bcf824 $s9AppBundle14GlobalObserverC7onNotif33_F1205CFDC13498282252A689C79131F6LLyy10Foundation12NotificationVFZTf4nd_n + 384
8   AeroSpace                           0x0000000100bceb08 $s10Foundation12NotificationVIeghn_So14NSNotificationCIeyBhy_TR + 116
9   CoreFoundation                      0x00000001816927ec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 128
10  CoreFoundation                      0x000000018172366c ___CFXRegistrationPost_block_invoke + 88
11  CoreFoundation                      0x00000001817235b4 _CFXRegistrationPost + 436
12  CoreFoundation                      0x000000018166143c _CFXNotificationPost + 732
13  Foundation                          0x0000000182809b14 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
14  AppKit                              0x0000000185361668 applicationStatusSubsystemCallback + 728
15  LaunchServices                      0x0000000181b37e84 ___LSScheduleNotificationFunction_block_invoke_2 + 52
16  CoreFoundation                      0x000000018169d8c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
17  CoreFoundation                      0x000000018169d7d0 __CFRunLoopDoBlocks + 356
18  CoreFoundation                      0x000000018169c5b8 __CFRunLoopRun + 824
19  CoreFoundation                      0x000000018169bbc4 CFRunLoopRunSpecific + 588
20  HIToolbox                           0x000000018cb0bf64 RunCurrentEventLoopInMode + 292
21  HIToolbox                           0x000000018cb11d54 ReceiveNextEventCommon + 636
22  HIToolbox                           0x000000018cb11eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
23  AppKit                              0x00000001851c7a08 _DPSNextEvent + 660
24  AppKit                              0x0000000185b07e0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
25  AppKit                              0x00000001851baae0 -[NSApplication run] + 480
26  AppKit                              0x0000000185191364 NSApplicationMain + 888
27  SwiftUI                             0x00000001af841340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
28  SwiftUI                             0x00000001afcb1ee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
29  SwiftUI                             0x00000001b002af24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
30  AeroSpace                           0x0000000100bcd3ec main + 36
31  dyld                                0x0000000181234274 start + 2840

**Comment by nzeh** [comment]
Yup, I have the same issue and was about to post the stack trace from my end.  I can do this if needed, but the error looks exactly the same as reported above, just with a different window title.
