### ISSUE TITLE
0.16.1-beta crashing reliably within 10mintues of launch.

### ISSUE THREAD

**Issue by paulpet** [nikitabobko/AeroSpace#818]
**Describe the bug**
Just installed 0.16.1-beta (from 0.16-0-beta)  and it's crashing reliably within about 10minutes of launching the app. First time it's crashed like this for me since I started using Aerospace a few months back.

**Related issues you could find**
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: 
Version: 0.16.1-Beta
Git hash: 7b88c46da8b00dcde023ec41f9629d19e0024902
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/frozen/closedWindowsCache.swift:48:10 cacheClosedWindowIfNeeded(window:)
recursionDetectorDuringFailure: false
cli: false
Displays have separate spaces: false

Stacktrace:
0   AeroSpace                           0x0000000104b13bc8 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlFs5NeverO_Tg5 + 1100
1   AeroSpace                           0x0000000104b3f328 $s6Common5check__4file4line6column8functionySb_SSyXKSSS2iSStF + 92
2   AeroSpace                           0x00000001049f0564 $s9AppBundle25cacheClosedWindowIfNeeded6windowyAA0E0C_tF + 1116
3   AeroSpace                           0x00000001049d7cf8 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 136
4   AeroSpace                           0x00000001049c2d80 $s9AppBundle9gcWindowsyyF + 500
5   AeroSpace                           0x00000001049c07ac $s9AppBundle2gc33_9D4CAE07A16011BB7304F8F5007BD739LLyyF + 388
6   AeroSpace                           0x00000001049bd574 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup4bodyxSb_SbxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnc_n + 272
7   HIServices                          0x00000001a694d3b0 _XXMIGPostNotification + 896
8   HIServices                          0x00000001a697849c _XPostNotification + 360
9   HIServices                          0x00000001a692f340 mshMIGPerform + 208
10  CoreFoundation                      0x00000001a0515a6c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
11  CoreFoundation                      0x00000001a051598c __CFRunLoopDoSource1 + 524
12  CoreFoundation                      0x00000001a0514350 __CFRunLoopRun + 2244
13  CoreFoundation                      0x00000001a0513434 CFRunLoopRunSpecific + 608
14  HIToolbox                           0x00000001aacbe19c RunCurrentEventLoopInMode + 292
15  HIToolbox                           0x00000001aacbdfd8 ReceiveNextEventCommon + 648
16  HIToolbox                           0x00000001aacbdd30 _BlockUntilNextEventMatchingListInModeWithFilter + 76
17  AppKit                              0x00000001a3d72cc8 _DPSNextEvent + 660
18  AppKit                              0x00000001a45694d0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
19  AppKit                              0x00000001a3d65ffc -[NSApplication run] + 476
20  AppKit                              0x00000001a3d3d240 NSApplicationMain + 880
21  SwiftUI                             0x00000001cbf0d3b8 OUTLINED_FUNCTION_12 + 13968
22  SwiftUI                             0x00000001cc676ddc OUTLINED_FUNCTION_3 + 196
23  SwiftUI                             0x00000001cca71e0c OUTLINED_FUNCTION_0 + 140
24  AeroSpace                           0x0000000104960fd0 main + 36
25  dyld                                0x00000001a00ab154 start + 2476

**Comment by nikitabobko** [comment]
Fixed in 0.16.2
