### ISSUE TITLE
AeroSpace Crashes Constantly 

### ISSUE THREAD

**Issue by b1kjsh** [nikitabobko/AeroSpace#820]
When I launch Aerospace it will randomly crash after about 10 minutes of using any application regardless if I interact with Aerospace directly or not.

Here's the dump that appears after the crash:

> ##### AeroSpace Runtime Error #####
> 
> Please report to:
>     https://github.com/nikitabobko/AeroSpace/issues/new
>     Please describe what you did to trigger this error
> 
> Message: 
> Version: 0.16.1-Beta
> Git hash: 7b88c46da8b00dcde023ec41f9629d19e0024902
> Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/frozen/closedWindowsCache.swift:48:10 cacheClosedWindowIfNeeded(window:)
> recursionDetectorDuringFailure: false
> cli: false
> Displays have separate spaces: true
> 
> Stacktrace:
> 0   AeroSpace                           0x000000010258bbc8 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlFs5NeverO_Tg5 + 1100
> 1   AeroSpace                           0x00000001025b7328 $s6Common5check__4file4line6column8functionySb_SSyXKSSS2iSStF + 92
> 2   AeroSpace                           0x0000000102468564 $s9AppBundle25cacheClosedWindowIfNeeded6windowyAA0E0C_tF + 1116
> 3   AeroSpace                           0x000000010244fcf8 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 136
> 4   AeroSpace                           0x000000010243ad80 $s9AppBundle9gcWindowsyyF + 500
> 5   AeroSpace                           0x00000001024387ac $s9AppBundle2gc33_9D4CAE07A16011BB7304F8F5007BD739LLyyF + 388
> 6   AeroSpace                           0x0000000102435574 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup4bodyxSb_SbxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnc_n + 272
> 7   HIServices                          0x00000001994d53b0 _XXMIGPostNotification + 896
> 8   HIServices                          0x000000019950049c _XPostNotification + 360
> 9   HIServices                          0x00000001994b7340 mshMIGPerform + 208
> 10  CoreFoundation                      0x000000019309da4c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
> 11  CoreFoundation                      0x000000019309d96c __CFRunLoopDoSource1 + 524
> 12  CoreFoundation                      0x000000019309c330 __CFRunLoopRun + 2244
> 13  CoreFoundation                      0x000000019309b414 CFRunLoopRunSpecific + 608
> 14  HIToolbox                           0x000000019d84619c RunCurrentEventLoopInMode + 292
> 15  HIToolbox                           0x000000019d845fd8 ReceiveNextEventCommon + 648
> 16  HIToolbox                           0x000000019d845d30 _BlockUntilNextEventMatchingListInModeWithFilter + 76
> 17  AppKit                              0x00000001968facc8 _DPSNextEvent + 660
> 18  AppKit                              0x00000001970f14d0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
> 19  AppKit                              0x00000001968edffc -[NSApplication run] + 476
> 20  AppKit                              0x00000001968c5240 NSApplicationMain + 880
> 21  SwiftUI                             0x00000001bea953b8 OUTLINED_FUNCTION_12 + 13968
> 22  SwiftUI                             0x00000001bf1feddc OUTLINED_FUNCTION_3 + 196
> 23  SwiftUI                             0x00000001bf5f9e0c OUTLINED_FUNCTION_0 + 140
> 24  AeroSpace                           0x00000001023d8fd0 main + 36
> 25  dyld                                0x0000000192c33154 start + 2476

**Comment by dagrlx** [comment]
immediately version 0.16.2 was released because of this same problem.

https://github.com/nikitabobko/AeroSpace/releases/tag/v0.16.2-Beta

**Comment by nikitabobko** [comment]
Please update to 0.16.2
