### ISSUE TITLE
Unable to invoke environment variables in calling `move-node-to-workspace`

### ISSUE THREAD

**Issue by FAL0258** [nikitabobko/AeroSpace#822]
**Describe the bug**
I was trying to move node to previous focused workspace, but unfortunately, it doesn't work if it is called by hotkeys. It works when it is called in zsh. It could probably caused by parsing the command incorrectly like using `'` instead of `"` in bash script, and so it treated the env var as a plain text.

The config is as follows:
```toml
# Send node to prev workspace
    alt-shift-tab = ['move-node-to-workspace $AEROSPACE_PREV_WORKSPACE', 'workspace $AEROSPACE_PREV_WORKSPACE']
```

<img width="492" alt="image" src="https://github.com/user-attachments/assets/0fd5736f-6aee-4fb8-8464-ac8853a5b86e">

While typing `aerospace move-node-to-workspace $AEROSPACE_PREV_WORKSPACE` in zsh works.

**Comment by nikitabobko** [comment]
It's not a bug. TOML string is not shell. And even if it was, nobody told that those environment variables would be accessible there

Related: #278
