### ISSUE TITLE
Left alt/option doesn't work

### ISSUE THREAD

**Issue by wojciech-kulik** [nikitabobko/AeroSpace#84]
How can I set bindings using left option? I see that default bindings work only with right alt :(.

Btw. this project is amazing ❤️ so much better than Yabai which requires disabling SIP, virtual workspaces are awesome. And it's written in Swift 🔥 

Please consider enabling discussions in this repository for such questions like this one :).

**Comment by nikitabobko** [comment]
Please try to relaunch AeroSpace or `aerospace reload-config` in CLI. It should work for both `alt`s

I suspect that it's the same bug as #46

**Comment by nikitabobko** [comment]
> Please consider enabling discussions in this repository for such questions like this one :)

I never used Discussions on GH. What value does it bring? I don't see problems that people are asking questions in issues. If there is a question then there is always something to improve

For example, your question about `alt` is not a question. It's an issue

- I'm afraid that people will misuse Discussions
- Two places to search for help/information is worse than one place

**Comment by wojciech-kulik** [comment]
It turned out that it was my old hotkey for Yabai, set using shkd, so I just had a conflict. Now it works as expected! Thank you for the help!

**Comment by wojciech-kulik** [comment]
> > Please consider enabling discussions in this repository for such questions like this one :)
> 
> I never used Discussions on GH. What value does it bring? I don't see problems that people are asking questions in issues. If there is a question then there is always something to improve
> 
> For example, your question about `alt` is not a question. It's an issue
> 
> * I'm afraid that people will misuse Discussions
> * Two places to search for help/information is worse than one place

Makes sense. I like discussions for some topics like discussing ideas or Q&A. However, as you mentioned, a disadvantage of this approach is that you have then two sources of "tickets". If you prefer to stay with issues, it's not a problem either :).
