### ISSUE TITLE
Active Window Border

### ISSUE THREAD

**Issue by JacquesvanWyk** [nikitabobko/AeroSpace#85]
I know that some people dont like this at all but I would like if there is normal border and  active border and color option in config that can be configured.

Started using this Aerospace today and loving it. Thanks for considering.

**Comment by nikitabobko** [comment]
It's too much dark magic to implement. It goes against values of the project (see readme) to be easily maintainable.

You can use https://github.com/FelixKratz/JankyBorders together with AeroSpace

**Comment by nikitabobko** [comment]
Even the darkest macOS hackers decided to drop this functionality in yabai, because it's impossible to maintain https://github.com/koekeishiya/yabai/issues/1889

**Comment by jsonMartin** [comment]
To solve this, I personally use **HazeOver**..it dims all windows not currently in the foreground. Great to help focus on the active window at hand, especially with multi-monitors.

**Comment by zachdaniel** [comment]
@jsonMartin thanks for the tip

**Comment by thuvasooriya** [comment]
while using jankyborders with aerospace i can observe the borders of windows from other spaces in my bottom right corner, can this be circumvented somehow?

**Comment by Ding-Fan** [comment]
I'm using [on-focus-changed-callbacks](https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks) to help me track the current window

**Comment by anarqist** [comment]
> while using jankyborders with aerospace i can observe the borders of windows from other spaces in my bottom right corner, can this be circumvented somehow?

I experienced the same on my Mac mini on macOS 26.0.1. any solution for this?

**Comment by thuvasooriya** [comment]
@anarqist i have stopped using jankyborders altogether because i couldn't stand it. i don't think this could be fixes since it's how aerospace works, as it places windows on the corner of the desktop. but i haven't looked into this for a while so i'm not sure.
