### ISSUE TITLE
Error with chrome and swapping between two monitors.

### ISSUE THREAD

**Issue by ulmentflam** [nikitabobko/AeroSpace#855]
AeroSpace Crashed with the following runtime error. I was switching between monitors when chrome became half-sized like another app was about to pop up, then AeroSpace crashed.

##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("")', role: 'nil', subrole: 'nil', identifier: 'nil', modal: 'Optional("")', windowId: 'Optional("473")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000104b0b648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x00000001049bb324 $s9AppBundle33restoreClosedWindowsCacheIfNeeded19newlyDetectedWindowSbAA0K0C_tF + 2548
2   AeroSpace                           0x00000001049a8c28 $s9AppBundle9MacWindowC3get3app02axD07startupACSgAA0cA0C_So14AXUIElementRefaSbtFZTf4nnnd_n + 1648
3   AeroSpace                           0x00000001049a4fa0 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlFSaySo14AXUIElementRefaG_9AppBundle6WindowCTg503$s9f55Bundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6h15CGSb_tFAGSgSo14D9RefaXEfU_AI0kF0CSbTf1cn_nTf4ngn_n + 248
4   AeroSpace                           0x000000010499d7ac $s9AppBundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6WindowCGSb_tF + 256
5   AeroSpace                           0x000000010498d5d0 $s9AppBundle41detectNewWindowsAndAttachThemToWorkspaces33_9D4CAE07A16011BB7304F8F5007BD739LL7startupySb_tF + 384
6   AeroSpace                           0x000000010498af30 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 736
7   HIServices                          0x00000001974a4abc _XXMIGPostNotification + 896
8   HIServices                          0x00000001974d5fdc _XPostNotification + 356
9   HIServices                          0x00000001974853a4 mshMIGPerform + 212
10  CoreFoundation                      0x0000000190b44e28 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
11  CoreFoundation                      0x0000000190b44d48 __CFRunLoopDoSource1 + 524
12  CoreFoundation                      0x0000000190b436a8 __CFRunLoopRun + 2248
13  CoreFoundation                      0x0000000190b42724 CFRunLoopRunSpecific + 588
14  HIToolbox                           0x000000019c09a530 RunCurrentEventLoopInMode + 292
15  HIToolbox                           0x000000019c0a0348 ReceiveNextEventCommon + 676
16  HIToolbox                           0x000000019c0a0508 _BlockUntilNextEventMatchingListInModeWithFilter + 76
17  AppKit                              0x00000001946ad034 _DPSNextEvent + 660
18  AppKit                              0x00000001950112d4 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
19  AppKit                              0x00000001946a0060 -[NSApplication run] + 480
20  AppKit                              0x0000000194676854 NSApplicationMain + 888
21  SwiftUI                             0x00000001bf793a6c $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
22  SwiftUI                             0x00000001bfc073f8 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 140
23  SwiftUI                             0x00000001bff82f38 $s7SwiftUI3AppPAAE4mainyyFZ + 224
24  AeroSpace                           0x000000010492d3ec main + 36
25  dyld                                0x00000001906dc274 start + 2840

**Comment by nikitabobko** [comment]
Please update to 0.16.2
