### ISSUE TITLE
Feature request: introduce `focus-monitor (left|down|up|right|next|prev)` command

### ISSUE THREAD

**Issue by wojciech-kulik** [nikitabobko/AeroSpace#86]
I would like to switch focus between displays (internal & external). 

I know that it works by default if I switch to a specific workspace, but it requires me to check what is the current workspace id first and then use the associated shortcut. I would like to have it simplified.

I tried:
```
aerospace focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left
```

but it doesn't seem to work. I also checked the whole documentation but I couldn't find anything on this topic. Thanks in advance (excuse me for spamming with issues)

**Comment by nikitabobko** [comment]
What version do you use? I can't reproduce it in the latest version from homebrew `v0.7.1-Beta`, but I can reproduce it snapshot build from `main` branch

**Comment by wojciech-kulik** [comment]
Yes, I'm using `main` branch and I build the app locally

**Comment by nikitabobko** [comment]
It's a bug

**Comment by wojciech-kulik** [comment]
👌 but what is the expected way to switch focus between displays? The command that I sent?

**Comment by nikitabobko** [comment]
There is no such command yet. It needs to be implemented

`aerospace focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left` can be used as such, but it will work as you want only if you don't have any intermediate windows between your currently focused window and the display

**Comment by nikitabobko** [comment]
i3 uses the `focus` command for that purpose (https://i3wm.org/docs/userguide.html#_focusing_moving_containers), but I think that I will introduce a separate `focus-monitor (left|down|up|right)` command

**Comment by wojciech-kulik** [comment]
Great, thank you for your work! 🔥

**Comment by GraemeARobinson** [comment]
@wojciech-kulik Thank you for sharing this project there! I absolutely love it! Also @nikitabobko thank you for making this tool, it is fantastic!!!!

**Comment by nikitabobko** [comment]
Just a random note

Technically speaking, right now it's possible to focus different monitors with:
```
aerospace list-workspaces --monitor all --visible | aerospace workspace next
```
but it's not directional `(left|down|up|right)`, and `(next|prev)` is in alphabetical order of workspaces, but `focus-monitor (next|prev)` is expected to cycle monitors in their natural left-to-right order

**Comment by carlosflorencio** [comment]
I'm using a temporary script to navigate between the left and right monitors:

aerospace-next-monitor:
```sh
#!/bin/bash

export PATH="/opt/homebrew/bin:$PATH"
arg="$1"

aerospace list-monitors --focused | \
    awk -v arg="$arg" '{if (arg=="next") print $1+1; else print $1-1}' | \
    xargs -I {} aerospace list-workspaces --monitor {} --visible | \
    xargs -I {} aerospace workspace {}
```

~/.aerospace.toml
```toml
# focus monitors
ctrl-alt-cmd-shift-u = 'exec-and-forget ~/scripts/aerospace-next-monitor prev'
ctrl-alt-cmd-shift-o = 'exec-and-forget ~/scripts/aerospace-next-monitor next'
```

**Comment by nikitabobko** [comment]
`focus-monitor` is introduced in 0.9.0
