### ISSUE TITLE
Tabs in Ghostty treated as visible windows

### ISSUE THREAD

**Issue by lukeberry99** [nikitabobko/AeroSpace#887]
**Describe the bug**
When creating new tabs in Ghostty, they're treated as additional windows on the page - which just serves to shrink the current visible window.

I believe this is related to the native tabs issue below?

**Related issues you could find**
https://github.com/nikitabobko/AeroSpace/issues/68

**Comment by lukeberry99** [comment]
Closing, as I've found a few issues that are identical to this that are already closed

https://github.com/nikitabobko/AeroSpace/issues/778

**Comment by pix2D** [comment]
Just for reference if anyone else runs into this. My workaround is this in the AeroSpace config:

```
[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
check-further-callbacks = true
run = "layout floating"
```

Reload the config, this needs to be in place **before** Ghostty is started (so if you just added it, reload the AeroSpace config and then restart Ghostty). It will then always start in floating mode, and when you unfloat it (`opt-shift-semicolon f` by default) everything works fine.

The key seems to be that it starts floating. If you start it normally, and then float and unfloat it does not work.

**Comment by crierr** [comment]
The reason it looks like it works is because only one of the tabs is tiled. While using this as a workaround, you should remember which tab is the tiled layout and not close it.
