### ISSUE TITLE
[feature request] Consider lua (or another scriptable language) based configs

### ISSUE THREAD

**Issue by thalesmello** [nikitabobko/AeroSpace#889]
As much as I find the `aerospace.toml` very clean and well thought out, it has limitations, so it would be nice to be able to customize my Aerospace config in a scriptable language like it's possible with Neovim or Emacs

Lua seems simple enough to embed (see references), and the API could be exposed to the scriptable language. Then it should be possible to create keymaps and callbacks in a much more flexible manner, as well as organize the config into multiple parts.

# Motivation

This thought came out of the frustration of trying to configure some specific tasks, and then having to resort to other tools to pull it off.

A few examples of things I tried to do that were limit by the current configs:

- Have different rules apply to my work and personal computers configs while maintaining the same code base (unsolved)
- Auto close / minimize the "Zoom" login window it appears (solved with BetterTouchTool)
- Move Chrome's floating window on workplace changes (solved by external script)

# Resources

https://github.com/weyhan/lua4swift
https://github.com/SwiftyLua/SwiftyLua?tab=readme-ov-file

**Comment by nikitabobko** [comment]
https://github.com/nikitabobko/AeroSpace/discussions/622
