### ISSUE TITLE
add an option to remove title bar

### ISSUE THREAD

**Issue by glepnir** [nikitabobko/AeroSpace#90]
as title said. it's nice to have an option to remove title bar.

**Comment by nikitabobko** [comment]
What is title bar? Do you mean tray icon in the top right corner?

**Comment by glepnir** [comment]
emm i mean left top corner close max min . unsure it should handle by aerospace. at least it not shown on yabai hyprland i3 etc wm which i used.

**Comment by nikitabobko** [comment]
That would be too much dark magic to implement. I want AeroSpace to be easily maintainable. See values in README.md

**Comment by glepnir** [comment]
this is i3 have and yabai also hide titlebar.  I'm not familiar with mac's api but as a tiling I thought it would be worth trying
```
default_border pixel 0
default_floating_border pixel 0
```

**Comment by zippeurfou** [comment]
@nikitabobko is your stance still the same here? I have been looking for this option as well for a while expecting aerospace to have it for what it is worth.
 @glepnir did you end up finding a workaround?

**Comment by albinahlback** [comment]
@nikitabobko can you change the status of this issue to "not planned"?
