### ISSUE TITLE
Chaining multiple commands together for performance

### ISSUE THREAD

**Issue by wheee** [nikitabobko/AeroSpace#902]
Perhaps there's a solution for this, but my use case is follows:

I have multiple monitors (4 in my case) and with MacOS, I would use Spaces to be able to cycle from:
Displays Setup #1 - browsing/chat/email/etc
Displays Setup #2 - IDE, mulitple terminal windows, browsers windows
Displays Setup #3 - Production server - running servers, tailing logs, browsers, etc.

And I would use yabai+skhd to instantly switch from Display Setup #1 to #3 without the annoying animation, etc.  It's not perfect - I've been noticing memory leaks and things do get a bit slower over time - not sure if it's yabai or anything else.  

As such, I've been trying out Aerospace and aside from the Display arrangement issue with 4 monitors to mimic my current setup, I have been able to get something working.

I can assign workspaces to my monitors, and then I can then issue multiple 'aerospace workspace #' commands together, so if I were to press CTRL-1 (via skhd), then I can switch the workspaces on 4 monitors at once.

This works, but it's slow because I have to issue 4 separate 'aerospace workspace #' commands for each monitor and it's very noticeable.

Some thoughts:
1. It would be nice to be able to configure and group workspaces together into a "workspace set" so you can switch from one set to another.
2. More immediately as a short-term fix, be able to pass in multiple workspace #s to the aerospace workspace command.
3. Perhaps as a more generic solution, be able to pass a file to aerospace, and the file would consist of multiple lines where each line is a command and aerospace can process each line within the same process.

ie. 
file "switch-workspaces.commands" would look like this:
workspace 1
workspace 2
workspace 3
workspace 4

and you can run it by:
aerospace --file=switch-workspaces.commands

**Comment by nikitabobko** [comment]
Chaining commands is already covered by `eval` in existing proposal #278
