### ISSUE TITLE
After switching to another Space and back, layout never spans full screen

### ISSUE THREAD

**Issue by Stooovie** [nikitabobko/AeroSpace#91]
Happens in 100% of the cases.

1) run aerospace
2) open some windows, fine
3) switch to another MacOS Space and back
4) windows never span the entire screen again

Sonoma 14.2.1, MBP M1 Pro

https://github.com/nikitabobko/AeroSpace/assets/10572373/27510546-f2d0-49a7-8d07-6de143a1a22e

**Comment by nikitabobko** [comment]
Please see https://nikitabobko.github.io/AeroSpace/guide.html#emulation-of-virtual-workspaces
