### ISSUE TITLE
Whenever split horizontal is triggered, window is "pushed" down

### ISSUE THREAD

**Issue by Nikki1993** [nikitabobko/AeroSpace#96]
I am having hard time describing it well so I've recorded a video. 

I got 2 keybinds. 

```
cmd-alt-ctrl-h = 'split horizontal'
cmd-alt-ctrl-period = 'split vertical'
```

Whenever I want to split horizontally window gets pushed. Then I switch back to split vertical and it goes back up. If I trigger split horizontally and then close the window to the right and re-open it again, window gets correctly positioned from top to bottom. If I open another, it also correctly splits horizontally. But if I were to open a new window when the previous one is "pushed" down, the second window will also appear "pushed" down.  

https://github.com/nikitabobko/AeroSpace/assets/1446529/1c6057df-080f-4ee4-b40a-6e5a29428e47

**Comment by fmasa** [comment]
@Nikki1993 This is because split creates new implicit horizontal container and the window is moved inside.

In default config, there is a `indent-for-nested-containers-with-the-same-orientation = 30` which automatically idnets nested containers with the same orientation.

**Comment by nikitabobko** [comment]
I just got an idea that it would make sense to create paddings from all 4 sides for windows that are **the only** child of their parent container, regardless of the containers orientations

All 4 paddings would be a better visualization

Example 1:
```
h_tiles
  window1
  v_tiles
    window2  <- create all 4 paddings
```

Example 2
```
h_tiles
  window1
  h_tiles
    window2  <- create all 4 paddings
```

And apply `indent-for-nested-containers-with-the-same-orientation` only in cases when there are several children

Example 3
```
h_tiles
  window1
  h_tiles      <-- "indent" the container. indent-for-nested-containers-with-the-same-orientation
    window2
    window3
```

Example 4
```
h_tiles
  window1
  v_tiles      <-- no indentation
    window2
    window3
```

**Comment by nikitabobko** [comment]
Idea No. 2

When a window is the only child of its parent then pretend that there is a second child in the container. It would create a "gap" in the tiles. But the gap will make it clear what orientation the parent has.

**Given this layout:**
```
h_tiles
  window1
  h_tiles
    window2
```
It would be rendered as if window2 had a sibling:
```
h_tiles
  window1
  h_tiles
    window2
    fake_sibling_window
```

**Given this layout:**
```
h_tiles
  window1
  v_tiles
    window2
```
It still would be rendered as if window2 had a sibling:
```
h_tiles
  window1
  h_tiles     <-- additionally the indentation (indent-for-nested-containers-with-the-same-orientation) is applied
    window2
    fake_sibling_window
```

Correct me if I'm wrong, but the only reason why people create containers that have only a single child is to later add another window as a sibling. The empty gap in tiles would make this intention clear

And this idea makes it possible to use `split` command with `enable-normalization-flatten-containers`. `enable-normalization-flatten-containers` could be dropped. Effectively it would always be enabled

**Comment by nikitabobko** [comment]
**Breaking change.** `indentForNestedContainersWithTheSameOrientation` is confusing, so I dropped it in 0.10.0

**Comment by azuline** [comment]
> Correct me if I'm wrong, but the only reason why people create containers that have only a single child is to later add another window as a sibling. The empty gap in tiles would make this intention clear

This is true for me, and is most often how i create my layouts. Every other time I end up in a one-child container (on i3) it is an accident and I undo it by hand.

I just spent a while hunting on how to do this, then found this issue which mentioned splits. Bless!
