### ISSUE TITLE
feature: aerospace-sensible-terminal to open Terminal via AppleScript

### ISSUE THREAD

**Issue by rpn32** [nikitabobko/AeroSpace#97]
The example config currently suggests to open a new Terminal using the following command:

`open -n /System/Application/Utilities/Terminal.app`

However, every time this command is run the Dock becomes more polluted with Terminal icons, which doesn't go away, even if you exit out of a Terminal.

A better example would be to use AppleScript to open Terminal like so:

`
osascript -e 'if application "Terminal" is running then' -e 'tell application "terminal"' -e 'do script ""' -e 'activate' -e 'end tell' -e 'else' -e 'tell application "Terminal"' -e 'activate' -e 'end tell' -e 'end if'
`

This has a couple of advantages:

1. Only one Terminal icon will be in the Dock at all times.
2. If you check 'Command Key' visibility in the title by going to Terminal->Settings->Profiles->Window->Title, you'll be able to jump between Terminal windows, even in a tabbed or stacked layout, by using the keyboard shortcut ⌥⌘N, where N is the Terminal number.

The disadvantage is that you now have ugly AppleScript within the config.

i3 has the script i3-sensible-terminal to launch a terminal based on what is defined in $TERMINAL and I think aerospace would benefit to have this feature as well.

You could hide the details of opening Terminal with AppleScript inside of it and the example config would then simplify to:

alt-enter = 'exec-and-forget aerospace-sensible-terminal'

**Comment by nikitabobko** [comment]
Thanks for the well-written issue!
And special thanks for listing the AppleScript monster. I'd not bother trying to write it/Google myself

Your idea makes sense, but I'm not sure that I want to abstract the AppleScript monster in a special `aerospace sensible-terminal` command. The potential problem is that this monster might not be handling all the cases, and further bugfixes would need to be done in the script

**Comment by rpn32** [comment]
No problem. Thanks for all your effort in making MacOS actually usable for those of us used to working in i3.

I'll leave the expanded AppleScript below in case anyone finds this issue and wants to add it to their bin directory:

```
#!/usr/bin/osascript

if application "Terminal" is running then
    tell application "terminal"
        do script ""
        activate
    end tell
else
    tell application "Terminal"
        activate
    end tell
end if
```

**Comment by matiasandrade** [comment]
I find this confusing, when a terminal (using Ghostty here, not sure if that's an issue) is open in a workspace and I run my command to supposedly open a new window using your AppleScript, I just switch workspace to the existing Ghostty window instead of opening a new window in the workspace I'm currently on. Am I missing something? Is there a better way to do this? I have seen examples for yabai also opening the new window on the workspace where the existing terminal window is instead of the currently selected workspace. https://github.com/ghostty-org/ghostty/discussions/3563
